### ISSUE TITLE
Dúvida: Disclaimer | Ferramenta não suportada

### ISSUE THREAD

**Issue by denisonsoares** [killerall/advpl-vscode#100]
Olá, Senhores!

Possuo uma dúvida, caso este não seja o lugar correto me avisem.

Na página do plugin advpl-vscode, há o seguinte disclaimer:

> Atenção! Essa extensão não é desenvolvida ou suportada pela TOTVS. Utilize por sua conta e risco.

Gostaria de saber se em algum momento o advpl-vscode poderá se tornar uma ferramenta suportada pela Totvs?

Obrigado,
Denison

**Comment by killerall** [comment]
No momento, não existe nenhuma intensão disto.
