### ISSUE TITLE
Erro ao iniciar debug

### ISSUE THREAD

**Issue by gabrielaluche** [killerall/advpl-vscode#104]
Bom dia, 

Comecei a utilizar o vscode, mas ao testar a funcionalidade do debug, encontrei problemas. Por alguma razão, ao chamar o smartclient, ocorre erro de sincronismo, como se o serviço tivesse caído, ou a configuração do server estivesse incorreta.
![erro](https://user-images.githubusercontent.com/28983850/28463843-f1722432-6df8-11e7-91d5-f1d8970403ca.png)

Poderiam me ajudar, por gentileza?

**Comment by killerall** [comment]
Bom dia.

você esta usando appserver local, ou em outra maquina?

Consegue compilar normalmente?

Isto começou a ocorrer quando? Ou nunca conseguiu rodar?

**Comment by gabrielaluche** [comment]
Olá. 
Estou conseguindo compilar normalmente. O meu appserver não é local, fica no servidor, mas o smartclient é local sim.

Nunca consegui fazer funcionar o debbug.

**Comment by killerall** [comment]
Ative no seu settings,

advpl.logger , "true"

Vai gerar um arquivo chamado AdvplDebugBridge.log
Dentro da sua pasta Temp. 
Por exemplo:

C:\Users\rodrigo.antonio\AppData\Local\Temp

Poste ele aqui

**Comment by gabrielaluche** [comment]
Thread[1] - 20/07/2017 11:46:56: Start.
Thread[1] - 20/07/2017 11:46:56: {"selectedEnvironment":"Developer1","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 11:46:58: End.
Thread[1] - 20/07/2017 11:48:08: Start.
Thread[1] - 20/07/2017 11:48:08: {"selectedEnvironment":"Developer1","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 11:48:10: End.
Thread[1] - 20/07/2017 11:49:16: Start.
Thread[1] - 20/07/2017 11:49:16: {"selectedEnvironment":"Developer1","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 11:49:18: End.
Thread[1] - 20/07/2017 11:51:14: Start.
Thread[1] - 20/07/2017 11:51:14: {"selectedEnvironment":"Developer1","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 11:51:16: End.
Thread[1] - 20/07/2017 11:51:58: Start.
Thread[1] - 20/07/2017 11:51:58: {"selectedEnvironment":"Developer1","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 11:52:00: End.
Thread[1] - 20/07/2017 11:52:25: Start.
Thread[1] - 20/07/2017 11:52:25: {"selectedEnvironment":"Developer1","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 11:52:27: End.
Thread[1] - 20/07/2017 11:53:24: Start.
Thread[1] - 20/07/2017 11:53:24: {"selectedEnvironment":"Developer1","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 11:53:26: End.
Thread[1] - 20/07/2017 12:50:01: Start.
Thread[1] - 20/07/2017 12:50:01: {"selectedEnvironment":"Developer1","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 12:50:10: End.
Thread[1] - 20/07/2017 14:57:58: Start.
Thread[1] - 20/07/2017 14:57:58: {"selectedEnvironment":"Developer1","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 14:58:05: End.
Thread[1] - 20/07/2017 15:32:46: Start.
Thread[1] - 20/07/2017 15:32:46: {"selectedEnvironment":"Developer1","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer2","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer3","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer4","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 15:32:50: End.
Thread[1] - 20/07/2017 15:35:24: Start.
Thread[1] - 20/07/2017 15:35:24: {"selectedEnvironment":"Developer4","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer2","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer3","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer4","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 20/07/2017 15:35:31: End.
Thread[1] - 21/07/2017 08:27:23: Start.
Thread[1] - 21/07/2017 08:27:23: {"selectedEnvironment":"Developer4","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer2","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer3","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer4","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|res)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 21/07/2017 08:27:34: End.
Thread[1] - 21/07/2017 08:41:39: Start.
Thread[1] - 21/07/2017 08:41:39: {"selectedEnvironment":"Developer4","environments":[{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer1","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer2","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer3","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="},{"smartClientPath":"C:\\Protheus 11\\smartclient - developer\\","environment":"Developer4","includeList":"C:\\CP Eletronica\\include\\","server":"10.161.83.88","port":"2500","user":"SESA406020","passwordCipher":"RitHemFFTmovK3BFK2tOS1Mwd05xWFA0TU9kUE4vNW4wbGxvR3VkZ2tVc0NoY3QyVXFRa0dBRlZLaEtUNXB1UjhzN3Zia0VPUXpjWk1DUGc1ZXpnVE5oVkxrTk5rZ0VDSlZjSVJuaXJUdkJPZjkrb1cvK3FINzVSZVRMNzNzYzg="}],"startProgram":"SIGAMDI","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|res)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":true,"debug_showPublic":true,"debug_showStatics":false,"compile_force_recompile":true,"logger":true}.
Thread[1] - 21/07/2017 08:41:43: End.

**Comment by killerall** [comment]
Pelo log, não ocorreu nenhum erro.
Você conseguiu já debugar em um appserver local? Consegue fazer este teste?

**Comment by gabrielaluche** [comment]
não tentei, mas posso tentar. Será que nao tem nenhuma configuração minha que está errada?

**Comment by gabrielaluche** [comment]
Compilar ele compila sem nenhum problema, agora o debug não funciona.

**Comment by killerall** [comment]
Boa tarde,

Acabei liberar uma versão com 2 correções.

Por favor verifique se resolveu.

Att

**Comment by gabrielaluche** [comment]
Bom dia ,
Atualizei a versão e resolveu o problema. Muito obrigada e parabéns pela iniciativa.
A TOTVS quer nos fazer engolir aquele Developer Studio pesado, chato e cheio de erros, mas graças a sua iniciativa temos um editor descente e menos arcaico que o DevStudio.

**Comment by killerall** [comment]
Obrigado pelo retorno.
Valeu.
