### ISSUE TITLE
Debug não funciona após atualização para 0.6

### ISSUE THREAD

**Issue by edusfc15** [killerall/advpl-vscode#105]
Boa tarde, não estou conseguindo debugar nessa versão, pode me ajudar?

**Comment by killerall** [comment]
Boa tarde,
Consegue detalhar melhor o que ocorre?

Ative no seu settings,

advpl.logger , "true"

Vai gerar um arquivo chamado AdvplDebugBridge.log
Dentro da sua pasta Temp.
Por exemplo:
C:\Users\rodrigo.antonio\AppData\Local\Temp

Poste ele aqui

**Comment by edusfc15** [comment]
Não para nos breakpoints, não exibe mensagem quando dá erro. O arquivo AdvplDebugBridge.log foi gerado, porém vazio.

**Comment by killerall** [comment]
Eu liberei uma nova versão. Por erro de Exception no Debug, ve se funciona para você.

**Comment by edusfc15** [comment]
Não deu certo,
Consegui gerar o advplbridge:


Thread[1] - 25/07/2017 09:21:18: Start.
Thread[1] - 25/07/2017 09:21:18: {"selectedEnvironment":"DEV_EMS","environments":[{"smartClientPath":"D:\\smartclient\\","environment":"DEV_EMS","includeList":"C:\\Users\\EduardoSantana\\Dropbox\\protheus_dev\\HOMOLOG\\include\\","server":"ERPD-DEV","port":"20000","user":"Eduardo.Santana","passwordCipher":"Yko2WU9zaEpBbzRVeXUzaEpGc1l3YjdNY0VLOGxsc2VuSER4alYyT1BaSFZ4bG1UbGVVSkVQcVZ2bmJFakFlcmVBa1pHdWhaL3hyZm5DaGRKVUJIcWVwRXRDNGxsME01WDFReXpKKzBsUTdlRzN2NHJXdkVEWnNVbGszV25YbVo="},{"serverVersion":"131227A","smartClientPath":"D:\\smartclient\\","environment":"DEV","includeList":"C:\\Users\\EduardoSantana\\Dropbox\\protheus_dev\\HOMOLOG\\include\\","server":"ERPH-MASTER","port":"10005","user":"EduardoSantana","passwordCipher":"clVJRWNBZ3pJdVNSSktjYUI3WEFaY3FuWDYvNXlqZmUxei9VZGNrSFJqeHJqUEFETmRwNS9vYWRCQUVvaXpKRnp2MHlpMFJjbk1nRWJKZ2F1VjI5Yjlob3JTSmNmRGRSQmVsVFBYMHBoTXNQV3JjdVNkdU5VRWlBWGJWUkdadkU=","rpoType":"CTREE"},{"serverVersion":"131227A","smartClientPath":"D:\\smartclient\\","environment":"DEVDB","includeList":"C:\\Users\\EduardoSantana\\Dropbox\\protheus_dev\\HOMOLOG\\include\\","server":"ERPP-MASTER","port":"13002","user":"EduardoSantana","passwordCipher":"clVJRWNBZ3pJdVNSSktjYUI3WEFaY3FuWDYvNXlqZmUxei9VZGNrSFJqeHJqUEFETmRwNS9vYWRCQUVvaXpKRnp2MHlpMFJjbk1nRWJKZ2F1VjI5Yjlob3JTSmNmRGRSQmVsVFBYMHBoTXNQV3JjdVNkdU5VRWlBWGJWUkdadkU=","rpoType":"CTREE"},{"serverVersion":"131227A","smartClientPath":"D:\\smartclient\\","environment":"POUDEVDEV_WS","includeList":"C:\\Users\\EduardoSantana\\Dropbox\\protheus_dev\\HOMOLOG\\include\\","server":"ERPD-DEV","port":"11001","user":"Eduardo.Santana","passwordCipher":"YVlhNU1JcGFuVW1oWURkY0FOTjJmaVVzVVV0U0tiUXJVRUZYV3RxTjduZDkzaVhmeHFtZ2UzaHpNaVpzNVBtTFRFc3kzVnMyZFVvZHJCelVjRWMwK2VRR2p5YXhXVDN2Q3A1U1ZueTV0cUUwVVd4b0RzR0Z0MXB1L2hsdGJXelk=","rpoType":"CTREE"}],"startProgram":"SIGAADV","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|res)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":true,"debug_ignoreSourceNotFound":false,"debug_showTables":false,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":false,"logger":true}.
Thread[1] - 25/07/2017 09:21:21: End.

**Comment by killerall** [comment]
O log, não tem erro algum.
No server do protheus ele não fala nada?
Já tentou excluir o launch.json e recria-lo?

**Comment by DudsM** [comment]
Comigo esta ocorrendo o mesmo problema.. Não para em nenhum breakpoint. Já recriei o launch.json também e continua no mesmo.

Porém uma observação, os breakpoints não estão funcionando em ambientes com versão 11 do protheus, se eu estar em ambientes com versão 12 funciona.

**Comment by killerall** [comment]
Humm,
A versão 11 qual a build que esta usando?

**Comment by killerall** [comment]
Acabei de reproduzir aqui com o Server da 11, vou dar uma olhada.

**Comment by DudsM** [comment]
Na v11 estou usando a Build 7.00.131227A

**Comment by edusfc15** [comment]
De fato, não está funcionando na versão 11, testei no 12 e funcionou.
No log do AppServer, não achei nada notável. 
Já tinha feito o processo de apagar o launch.json.
Se precisar de algum teste, ou detalhe para resolver, favor avisar. 

Grato.
