### ISSUE TITLE
Compilar Recursos no RPO

### ISSUE THREAD

**Issue by robsonrosilva** [killerall/advpl-vscode#108]
Boa tarde, gostaria de saber se há algum recurso para a gravação de arquivos (não fonte) no RPO semelhante a o recurso que o TDS tem(http://tdn.totvs.com/pages/viewpage.action?pageId=23887929).

**Comment by killerall** [comment]
O Vscode Compila todos arquivos que estão o regex:
"advpl.compileFolderRegex": ".*\\.(prw|prx|apw|aph|tres|png|bmp|res)",
da match.
Para compilar o resources, então, deve-se notar se a extensão do mesmo esta nesta lista. E se sim, crie uma pasta, coloque os resources la,  e com o botao direito sobre a pasta, mande compilar a mesma.

Att.

**Comment by robsonrosilva** [comment]
tem alguma forma de compilar arquivos com extensão diferente?

**Comment by killerall** [comment]
O comando de compilar funciona com qualquer arquivo aberto.
Para compilar pasta, vc precisa colocar no mesmo Regex, a extensão.
