### ISSUE TITLE
Erro ao enviar JSON para o repositório

### ISSUE THREAD

**Issue by robsonrosilva** [killerall/advpl-vscode#109]
Bom dia, não estou conseguindo aplicar um resource no RPO do tipo JSON ele indica a mensagem: SyntaxError: Unexpected end of JSON input.

Mas já validei o JSON em N ferramentas e o mesmo encontra-se correto.

Segue abaixo o código:

`[
	{
		"label": "Cadastros",
		"icon": "fa-trello",
		"items": [
			{
				"label": "Clientes",
				"icon": "fa-table",
				"routerLink": [
					"home/browser/SA1"
				],
				"command": "command",
				"execauto": "MATA030",
				"tabela": "SA1",
				"tipoFormulario": 1
			},
			{
				"label": "Fornecedores",
				"icon": "fa-table",
				"routerLink": [
					"home/browser/SA2"
				],
				"command": "command",
				"execauto": "MATA020",
				"tabela": "SA2",
				"tipoFormulario": 1
			},
			{
				"label": "Produtos",
				"icon": "fa-table",
				"routerLink": [
					"home/browser/SB1"
				],
				"command": "command",
				"execauto": "MATA010",
				"tabela": "SB1",
				"tipoFormulario": 1
			},
			{
				"label": "Unidades de Medida",
				"icon": "fa-table",
				"routerLink": [
					"home/browser/SAH"
				],
				"command": "command",
				"execauto": "QIEA030",
				"tabela": "SAH",
				"tipoFormulario": 1
			},
			{
				"label": "Locais",
				"icon": "fa-table",
				"routerLink": [
					"home/browser/NNR"
				],
				"command": "command",
				"execauto": "AGRA045",
				"tabela": "NNR",
				"tipoFormulario": 1
			},
			{
				"label": "Grupo de Produtos",
				"icon": "fa-table",
				"routerLink": [
					"home/browser/SBM"
				],
				"command": "command",
				"execauto": "MATA035",
				"tabela": "SBM",
				"tipoFormulario": 1
			},
			{
				"label": "Cond de Pagamento",
				"icon": "fa-table",
				"routerLink": [
					"home/browser/SE4"
				],
				"command": "command",
				"execauto": "MATA360",
				"tabela": "SE4",
				"tipoFormulario": 2
			}
		]
	},
	{
		"label": "Faturamento",
		"icon": "fa-shopping-cart",
		"items": [
			{
				"label": "Cadastros",
				"icon": "trello",
				"items": [
					{
						"label": "Prospeccoes",
						"icon": "fa-table",
						"routerLink": [
							"home/browser/SU5"
						],
						"command": "command",
						"execauto": "TMKA260",
						"tabela": "SU5",
						"tipoFormulario": 1
					},
					{
						"label": "Tabela De Precos",
						"icon": "fa-table",
						"routerLink": [
							"home/browser/DA0"
						],
						"command": "command",
						"execauto": "OMSA010",
						"tabela": "DA0",
						"tabelaCols": "DA1",
						"tipoFormulario": 2
					}
				]
			},
			{
				"label": "Movimentos",
				"icon": "trello",
				"items": [
					{
						"label": "Pedido de Venda",
						"icon": "fa-table",
						"routerLink": [
							"home/browser/SC5"
						],
						"command": "command",
						"execauto": "MATA410",
						"tabela": "SC5",
						"tabelaCols": "SC6",
						"tipoFormulario": 2
					}
				]
			}
		]
	}
]`

**Comment by killerall** [comment]
Você salva esse arquivo como .Json?
Como você faz para enviar isso? Compilando a pasta de resourcE?

**Comment by robsonrosilva** [comment]
salvo ele com extensão .json e tentei compilar com o CTRL+F9 e com a compilação de pasta, mas os dois geram o mesmo erro.

**Comment by killerall** [comment]
Acabei de fazer o teste aqui com a versão 0.7.0; E não tive problemas. Vc esta com a ultima versão?

**Comment by robsonrosilva** [comment]
Sim estou com a versão 0.7.0 e VSCODE Versão 1.15 x64.

**Comment by killerall** [comment]
Você mexeu no "advpl.compileFolderRegex"?

**Comment by robsonrosilva** [comment]
sim adicionei JSON nele "advpl.compileFolderRegex": ".*\\.(prw|prx|apw|aph|tres|png|bmp|res|json|prg)" .

**Comment by killerall** [comment]
Não consigo reproduzir,
Você tentou compilar fontes?

**Comment by robsonrosilva** [comment]
Ontem tinha compilado havia dado certo, mas fui compilar hoje e não compilou mais nada, vi agora.

**Comment by killerall** [comment]
Ative no seu settings,

advpl.logger , "true"

Vai gerar um arquivo chamado AdvplDebugBridge.log
Dentro da sua pasta Temp.
Por exemplo:
C:\Users\rodrigo.antonio\AppData\Local\Temp
Me envie ele.
aproveite e Antes do teste apaga essa pasta Temp.

**Comment by robsonrosilva** [comment]
Descobri que o meu APPSERVER.ini estava corrompido, não estava conseguindo nem entrar no Protheus. quando ajustei o APPSERVER.ini parou de dar problema.

Segue o erro gerado.

Thread[1] - 15/08/2017 11:57:18: Start.
Thread[1] - 15/08/2017 11:57:18: {"selectedEnvironment":"REST_CMP","environments":[{"serverVersion":"131227A","smartClientPath":"D:\\TOTVS\\TOTVS 12\\Microsiga\\Protheus\\bin\\smartclient\\","environment":"P12","includeList":"C:\\Users\\02523197103\\Dropbox\\TRABALHO\\WORKSPACE\\web-erp-advpl\\Projeto_ADVPL_REST\\include\\","server":"localhost","port":"1212","user":"admin","passwordCipher":"dGtIaUJTWTV4blNRWEkrRGJQTWNnR3hNV2NwSnFjL1plSDlBR0l5Ti9qcGNCcHJuRHd5cG5QSFZ5Yyt5djd0dmZ2YnYvWWJGdXA1UlY0dmlrTDd3L1BzWEFvdVY3dlVmOXBnZFN3VzQzQUJFaVd0cUZCMlh2S2Q1S0dLcjR2cjI=","rpoType":"TOP"},{"serverVersion":"131227A","smartClientPath":"D:\\TOTVS\\TOTVS 12\\Microsiga\\Protheus\\bin\\smartclient\\","environment":"REST_CMP","includeList":"C:\\Users\\02523197103\\Dropbox\\TRABALHO\\WORKSPACE\\web-erp-advpl\\Projeto_ADVPL_REST\\include\\","server":"localhost","port":"1212","user":"admin","passwordCipher":"dGtIaUJTWTV4blNRWEkrRGJQTWNnR3hNV2NwSnFjL1plSDlBR0l5Ti9qcGNCcHJuRHd5cG5QSFZ5Yyt5djd0dmZ2YnYvWWJGdXA1UlY0dmlrTDd3L1BzWEFvdVY3dlVmOXBnZFN3VzQzQUJFaVd0cUZCMlh2S2Q1S0dLcjR2cjI=","rpoType":"TOP"},{"serverVersion":"131227A","smartClientPath":"D:\\TOTVS\\TOTVS 12\\Microsiga\\Protheus\\bin\\smartclient\\","environment":"REST","includeList":"C:\\Users\\02523197103\\Dropbox\\TRABALHO\\WORKSPACE\\web-erp-advpl\\Projeto_ADVPL_REST\\include\\","server":"localhost","port":"1213","user":"admin","passwordCipher":"dGtIaUJTWTV4blNRWEkrRGJQTWNnR3hNV2NwSnFjL1plSDlBR0l5Ti9qcGNCcHJuRHd5cG5QSFZ5Yyt5djd0dmZ2YnYvWWJGdXA1UlY0dmlrTDd3L1BzWEFvdVY3dlVmOXBnZFN3VzQzQUJFaVd0cUZCMlh2S2Q1S0dLcjR2cjI=","rpoType":"TOP"}],"startProgram":"SIGAFAT","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|apw|aph|tres|png|bmp|res|json|prg)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":true,"debug_ignoreSourceNotFound":false,"debug_showTables":true,"debug_showPrivates":true,"debug_showPublic":true,"debug_showStatics":false,"compile_force_recompile":false,"logger":true,"compile_threads":4}.
Thread[1] - 15/08/2017 11:57:18: Starting MultiThread Compiler with 4 threads..
Thread[1] - 15/08/2017 11:57:29: IniParser.Exceptions.ParsingException: Unknown file format. Couldn't parse the line: 'ï»¿[NAO_LE]'. while parsing line number 0 with value '' - IniParser version: 2.4.0.0 while parsing line number 1 with value 'ï»¿[NAO_LE]' - IniParser version: 2.4.0.0 ---> IniParser.Exceptions.ParsingException: Unknown file format. Couldn't parse the line: 'ï»¿[a$5*]'. while parsing line number 0 with value '' - IniParser version: 2.4.0.0
   em IniParser.Parser.IniDataParser.ProcessLine(String currentLine, IniData currentIniData)
   em IniParser.Parser.IniDataParser.Parse(String iniDataString)
   --- Fim do rastreamento de pilha de exceções internas ---
   em IniParser.Parser.IniDataParser.Parse(String iniDataString)
   em AdvplDebugBridge.util.AppServerIni..ctor(String ini, String env).

**Comment by killerall** [comment]
Ha blz.
Vou tentar melhorar a massagem de erro que da neste caso. valeu.
