### ISSUE TITLE
Gerar patch com vários fontes

### ISSUE THREAD

**Issue by leandrodefaria** [killerall/advpl-vscode#111]
Bom dia pessoal.

Alguém poderia me dizer como gero patch de vários fontes? Com o plugin só consigo selecionar apenas um. Alguém poderia me dizer?

Obrigado

**Comment by killerall** [comment]
Você deve gerar com o um arquivo txt. Um arquivo por linha.
Neste link você encontra a documentação:
https://github.com/killerall/advpl-vscode/wiki/Trabalhando-com-Patchs
