### ISSUE TITLE
criação de patch em ambiente local

### ISSUE THREAD

**Issue by tigas360** [killerall/advpl-vscode#112]
olá, tentei gerar um patch utilizando ambiente local e apresentou o seguinte erro:
{"Line":1,"Column":0,"Type":0,"Message":"Error ao gerar o patch.System.IO.FileNotFoundException: N�o foi poss�vel localizar o arquivo 'C:\\Users\\tiago.dsantos\\AppData\\Local\\Temp\\ttdp120.ptm'.\r\nNome do arquivo: 'C:\\Users\\tiago.dsantos\\AppData\\Local\\Temp\\ttdp120.ptm'\r\n   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   em System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)\r\n   em System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)\r\n   em advtec.patch.PatchManager.Build(String[] sources)"}

o estranho é que se apontar para um ambiente externo o patch é gerado.

No meu console.log apresentou que gerou o patch em uma pasta temporária não definida nas configurações o VSCode

generating patch file...
  delete TMSA144.PRW 
  delete TMSA250.PRW 
  insert TMSA144.PRW 
  insert TMSA250.PRW 
patch file OK...
------0--c:\p12_teste_sistemico\protheus_data\tmptdsspod2915\tttp120.ptm

tem alguma ideia do que pode ser.

**Comment by killerall** [comment]
No seu ambiente o RPODB deve estar com SQL, 
Mude para TOP e você ira conseguir gerar corretamente.

Vou corrigir isso no proximo update.
