### ISSUE TITLE
F5 ou CTRL + F5

### ISSUE THREAD

**Issue by netocodes** [killerall/advpl-vscode#113]
Olá ótima iniciativa

Consegue me ajudar?

Consegui compilar, mas quando eu aperto F5 e escolho ADVPL Debug, Não se é isso, mas acho que a ideia era abrir o smartClient ? O meu não faz nada, nem mensagem de erro e nada no log.

A versão do vscode é 1.15.1, 32bits

**Comment by killerall** [comment]
Ele criou um arquivo chamado launch.json, dentro da pasta .vscode da sua pasta do vscode.

Lembrando que você precisa abrir uma pasta para conseguir usar a extensão.

**Comment by netocodes** [comment]
Verdade, existe o launch.json, porem desculpe minha ignorância, não compreendi sobre a pasta que eu preciso abrir.

Grato

**Comment by netocodes** [comment]
Deletei o launch.json o vscode recriou e funcionou. Obrigado
