### ISSUE TITLE
Não conecta

### ISSUE THREAD

**Issue by silfar** [killerall/advpl-vscode#114]
Pessoal, estou  testando o mscode com advpl, ainda sou iniciante nos dois, segui o wiki a configuração esta assim:

// Place your settings in this file to overwrite default and user settings.
{
    "advpl.environments":[{
    "smartClientPath": "C:\\totvs\\smartclient\\",
    "environment": "tcp_local",
    "includeList": "N:\\include\\",
    "server": "localhost",
    "port": "5099",
    "user": "Admin",
    "passwordCipher": "dVlKVUM0dXFHWDlGV1lVcUtUd1VINEhSVzBjM2N1ZlZMT1ByenQreVRtNkpoWSt6VjhlWDBXb2hrWnZWTXF4eWZNcEk5T3pQOGhpTUlGR3kraCt5N0hxc3ZYWEdpTG0ySUxqZEt6ek03UG9xTURtTnlDMEsyTFZBbVNXajBrK0E="
    }
],
"advpl.selectedEnvironment": "tcp_local"
}

quando vou compilar 👍 

Compile Start at Fri Sep 01 2017 18:16:19 GMT-0300 (Hora oficial do Brasil)

Can't connect to server with this user:Admin
Compile Finish at Fri Sep 01 2017 18:16:19 GMT-0300 (Hora oficial do Brasil) Elapsed  (0.351 segs.)

Não sei pq não conecta com esse usuario, no tds vai normal. Detalhe esse usuario não tem senha.

**Comment by killerall** [comment]
Olha o log do server do protheus, ele da alguma msg?
Tipo:
 Starting Debugger....

Ou algum erro?

**Comment by silfar** [comment]
Consegui aqui, ele compila beleza, só não sei como fazer o debug rodar quando teclo F5 ele pede um nome do programa. Não teria um tutorial ?

**Comment by killerall** [comment]
Supondo que vc fez o seguinte fonte:
`#include"protheus.ch
User funtion hello()
Conout("ola")
Return
`
Depois de compilar, ao executar, vc digita U_HELLO e da enter,

Você ira conseguir debug e executar.

Por exemplo se quiser abir o modulo de Faturamento, você digita SIGAFAT.

Na internet vc encontra bastante material para iniciar o desenvolvimento em advpl.
