### ISSUE TITLE
Sobre o debug

### ISSUE THREAD

**Issue by silfar** [killerall/advpl-vscode#115]
Cara muito boa sua extensão, muito melhor que usar o TDS. Mas como ainda não tenho muita intimidade vão algumas dúvidas:

advpl.debug_showTables : Mostra as tabelas abertas.
advpl.debug_showPrivates : Mostra as variaveis Privates.
advpl.debug_showPublic : Mostra as variaveis Publicas.
advpl.debug_showStatics : Mostra as variaveis Estaticas .

Estas cpnfigurações devem ficar em que arquivos, e como faço para mostrar esses dados ?

E o log:

 advpl.logger: Crie um log da execução

Onde ele cria esse log.

Mais uma vez parabens.

**Comment by izacsc** [comment]
essas configurações ficam no arquivo de configurações do usuário do vscode.  O atalho pra abrir é ctrl + ,

**Comment by izacsc** [comment]
Na verdade o atalho é ctrl e vírgula ( ctrl + , ). Se não funcionar, procure nos comandos ( pressionando f1) por user settings.

**Comment by silfar** [comment]
Ahh, Valeu. E sobre o log, sabe dizer onde ele gera.

**Comment by killerall** [comment]
Ele gera o log, no diretorio temp da maquina com o Nome AdvplDebugBridge.log, mais ele é apenas para uso de debug da extensão interna. Não tem nada a ver com o protheus.
