### ISSUE TITLE
Erro ao compilar antes do fim da compilação anterior

### ISSUE THREAD

**Issue by edusfc15** [killerall/advpl-vscode#117]
Ao tentar compilar um fonte, no meio do processo, se tentar compilar novamente está aparecendo a mensagem : "SyntaxError: Unexpected end of JSON input"
Não sei se é um problema, se deveria bloquear o atalho enquanto estiver compilando. Mas há casos, que tenho que reiniciar o Vscode para ele voltar ao normal(quando o processo aparentemente trava e fica com a mensagem "Compile Start at" sem completar o processo).

Se possível verificar, grato.

**Comment by killerall** [comment]
duplicate #116
