### ISSUE TITLE
Erro depois de aplicar patch para correção da venda no protheus 12.1.016.

### ISSUE THREAD

**Issue by geansis** [killerall/advpl-vscode#118]
Esta mostrando a seguinte  a mensagem depois de tentar executar o SIGAADV pelo comando Ctrl + F5.
"Impossible to decompress buffer."

Observação: O ambiente está funcionando normalmente quando executo direto pelo smartclient, dados da versão abaixo. 

***  TOTVS S.A.  ***
***  www.totvs.com.br  ***
* TOTVS - Build 7.00.131227A - Jul 21 2017 - 15:20:14 NG
* Build: 32 bits
* RPO Format: 32 bits
* SVN Revision: 9837 - 14595 - 1902
* Build Version: 13.2.3.16

Starting (.P12 - Teste 02)...
Please wait...
*** STARTING SERVER WITH PREIMG CTREE DRIVER TRANSACION MODE

---------------- OS System Info -----------------------------------------------
OS Version .........: Windows Server 2012 R2 [Version 6.3.9600]
OS Platform ........: Windows NT Based (x64)
OS Version Info ....: 
-------------------------------------------------------------------------------

**Comment by killerall** [comment]
Nunca vi este erro.
Tente fazer o seguinte, apague o seu tem
por exemplo:
C:\Users\rodrigo.antonio\AppData\Local\Temp
Ative no seu settings, do vscode
advpl.logger , "true"

Vai gerar um arquivo chamado AdvplDebugBridge.log
Dentro da sua pasta Temp.

Me envie ele.

**Comment by geansis** [comment]
Bom dia,

Consegui resolver o problema acredito  eu, é que corrompeu o RPO, porque peguei outro RPO recompilei e apliquei todos os patchs e está funcionando normalmente.

Obrigado,
