### ISSUE TITLE
Advpl - Compile TXT list of files gera SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by WexleiNGI** [killerall/advpl-vscode#120]
Ao tentar compilar uma lista de fontes a partir da opção _Advpl - Compile TXT list of files_, recebo apenas uma mensagem genérica no Output dizendo o seguinte:

**SyntaxError: Unexpected end of JSON input**

Já tentei recriar o launch.json, alterei algumas das configurações do User settings, no entanto o erro persiste.
Me lembro de já ter utilizado esse recurso uma vez e funcionou.

**Comment by killerall** [comment]
Você esta na 0.7.3?

Acabei de testar aqui e compilou normal.

Como esta montando o txt?

**Comment by WexleiNGI** [comment]
Sim, estou com esta versão mesmo.

O arquivo é montado assim:

![image](https://user-images.githubusercontent.com/32199376/30748057-724659e4-9f85-11e7-8a7f-83f75b0dd7db.png)

Já tentei mudar a extensão do arquivo para TXT só por desencargo, mas também não funciona...

**Comment by killerall** [comment]
Tente fazer o seguinte, apague o seu temp
por exemplo:
C:\Users\rodrigo.antonio\AppData\Local\Temp
Ative no seu settings, do vscode
advpl.logger , "true"

Vai gerar um arquivo chamado AdvplDebugBridge.log
Dentro da sua pasta Temp.

Me envie ele.

**Comment by WexleiNGI** [comment]
Gerou o arquivo, mas vazio.

Tentei compilar a lista, depois abri o sistema, abri uma rotina qualquer, fechei, tentei compilar a lista novamente. Só preencheu quando eu compilei individualmente um fonte.

[AdvplDebugBridge.zip](https://github.com/killerall/advpl-vscode/files/1324777/AdvplDebugBridge.zip)

**Comment by killerall** [comment]
Putz,
Bem tenta fazer o seguinte, reduz a quantidade de arquivos.

Deixa 1 primeiro e veja se vai.

att

**Comment by WexleiNGI** [comment]
Também não funciona. Dá o mesmo erro.

**Comment by killerall** [comment]
Pegue esse anexo, 
Va na sua pasta do vscode, que deve ser algo como:

C:\Users\rodrigo.antonio\.vscode\extensions\KillerAll.advpl-vscode-0.7.3\bin

Renomei o EXE, descompacte o novo e faça o teste novamente com o log habilitado.

[AdvplDebugBridge.zip](https://github.com/killerall/advpl-vscode/files/1324864/AdvplDebugBridge.zip)

**Comment by WexleiNGI** [comment]
Ainda gera o arquivo vazio.

**Comment by killerall** [comment]
Descobri o que ocorre,
Pega esse aqui em anexo.
Vai funcionar.
[AdvplDebugBridge.zip](https://github.com/killerall/advpl-vscode/files/1324887/AdvplDebugBridge.zip)

**Comment by WexleiNGI** [comment]
Funcionou mesmo!

Obrigado!

**Comment by killerall** [comment]
Vou subir oficial na próxima versão vlw.

**Comment by WexleiNGI** [comment]
Mais uma vez, obrigado pelo antedimento rápido.
