### ISSUE TITLE
Exibir variáveis Publicas e Privadas no debug

### ISSUE THREAD

**Issue by vicfsilva** [killerall/advpl-vscode#122]
Boa tarde!

É possivel que as variáveis publicas e privadas sejam exibidas na seção de variáveis no debug? Unica coisa que sinto falta ao realizar o debug no .vscode em relação ao TDS é isso.

Vlw!

**Comment by edusfc15** [comment]
Boa tarde @vicfsilva. Já é possivel exibir essas informações.
Apenas ative no seu settings.json as seguintes diretivas:

   "advpl.debug_showPrivates": true,
    "advpl.debug_showPublic": true,
    "advpl.debug_showStatics": true

**Comment by killerall** [comment]
Como o @edusfc15  confirmou basta apenas habilitar.
Eu atualizei a Wiki, para ficar mais fácil de achar essa informação.
https://github.com/killerall/advpl-vscode/wiki/Execu%C3%A7%C3%A3o-e-Debug

**Comment by vicfsilva** [comment]
@killerall @edusfc15 habilitei aqui! vlw pessoal
