### ISSUE TITLE
Não consigo compilar um fonte

### ISSUE THREAD

**Issue by LeonardoRios** [killerall/advpl-vscode#123]
Eu gerei a senha, mas ao tentar compilar ele fala que a senha é inválida

"Invalid passwordCipher
Compile Finish at Tue Sep 26 2017 17:55:31 GMT-0300 (Hora oficial do Brasil) Elapsed  (1.663 segs.)"

![sem titulo](https://user-images.githubusercontent.com/6351312/30883971-4b3c9a04-a2e4-11e7-89c1-a15202061f56.png)

**Comment by killerall** [comment]
Troque o 
"advpl.passwordCipher"
Por 
"passwordCipher"
E verfique se você colocou a chave até o =, na configuração.

**Comment by LeonardoRios** [comment]
Em relação a compilação só retirar o texto "advpl" funcionou. Obrigado @killerall !
Eu tentei debuggar agora e não consegui. Me apresenta as três mensagens seguintes:
- Ambiente LEONARDO selecionado com sucesso
- Error while processing request 'launch' (exception: Referência de objeto não definida para uma instância de um objeto).
- Please first open a folder in order to do advanced debug configuration.

Pode verificar e me ajudar por favor?
