### ISSUE TITLE
Ajuda na configuração

### ISSUE THREAD

**Issue by raisiqueira** [killerall/advpl-vscode#124]
Estou tentando configurar no MacOS, porém o debug e a aplicação de um fonte não dão certo.

```json
    "advpl.environments": [{
        "smartClientPath": "/Aplications/",
        "environment": "IMEC_HOMOLOG",
        "serverVersion": "131227A",
        "server": "IPDOMEUSERVER",
        "port": "1244",
        "includeList": "/Users/raisiqueira/Documents/TOTVS/totvs_developer_studio_11_3/includes",
        "user": "Admin"

    }],
    "advpl.startProgram": "SIGAFAT"
```
Saída no console:
![captura de tela 2017-10-02 as 18 03 01](https://user-images.githubusercontent.com/2914170/31099315-f7a54bd6-a79b-11e7-9412-b651df097925.png)

**Comment by killerall** [comment]
Você fez isso?
Efetuar o download do [executavel](https://github.com/killerall/advpl-vscode/raw/master/bin/AdvplDebugBridgeMac) 
Copiar o mesmo para a pasta: ~/.vscode/extensions/KillerAll.advpl-vscode-x.x.x/bin Dar acesso a execução no arquivo.

Depois disso precisa rodar o cipher da Senha de Admin, veja se ele gera.

**Comment by raisiqueira** [comment]
Gerou a hash da senha, mas meu ambiente não tem senha, uso apenas 'admin'.

**Comment by raisiqueira** [comment]
Nova saída no console:

```

Compile Start at Mon Oct 02 2017 18:29:59 GMT-0300 (-03)

Property 'smartclientPath' apppre.exe we cant' find  in /Users/raisiqueira/Applications/
Invalid passwordCipher
Include list is wrong, please check your includeList, It is necessary to have \ at the end of each folder.
Compile Finish at Mon Oct 02 2017 18:30:00 GMT-0300 (-03) Elapsed  (0.689 segs.)
```

**Comment by killerall** [comment]
Mesmo a senha sendo em branco, precisa gerar o Cipher.
Pela sua msg esta faltando tambem a configuração do appre correta e o diretorio de include.

**Comment by raisiqueira** [comment]
Isso, o diretórios de `includes` consegui resolver, só o do `smarclient` que não estou conseguindo.

**Comment by killerall** [comment]
Provavelmente vc não tem o appre no diretório Applications.
Se você tiver o tds instalado no MAC, procure pelo appre dentro da pasta do TDS.
Você precisa copiar para a pasta applications.
Algo tipo:
resources\appre\advpl\x86\mac

**Comment by poliestermoreira** [comment]
Olá, boa noite!
Estou com a mesma mensagem do appre, mas já me certifiquei de que ele está no local que está sendo referenciado.
Também já liberei permissão de leitura e escrita.
Mesmo assim a mensagem de que ele não foi encontrado, continua aparecendo.
Como devo proceder?

**Comment by rcarloslima** [comment]
@raisiqueira  Conseguiu configurar? Pode me ajudar?
