### ISSUE TITLE
Erro ao compilar no MacOS

### ISSUE THREAD

**Issue by rodrigopg** [killerall/advpl-vscode#127]
Boa tarde,

Já atualizei o meu Bridge conforme explicado na ultima versão 0.74 e já está funcionando as funções de Abrir o Protheus, debugar, etc...

Mas ainda não consegui compilar no Mac, aparece a seguinte mensagem:

Compile Start at Thu Oct 05 2017 11:04:18 GMT-0300 (-03)

Property 'smartclientPath' apppre.exe we cant' find  in /Applications/
Include list is wrong, please check your includeList, It is necessary to have \ at the end of each folder.
Compile Finish at Thu Oct 05 2017 11:04:18 GMT-0300 (-03) Elapsed  (0.362 segs.)

Meu settings.json está assim:

```
    "advpl.environments": [
        {
            "advpl.smartClientPath": "/Applications/",
            "environment": "teste",
            "includeList": "~/Documents/git/customize/includes",
            "server": "192.168.1.2",
            "port": "1234",
            "user": "rodrigo.goncalves",
            "passwordCipher": ""
        }
    ]
```

**Comment by killerall** [comment]
Provavelmente vc não tem o appre no diretório Applications.
Se você tiver o tds instalado no MAC, procure pelo appre dentro da pasta do TDS.
Você precisa copiar para a pasta applications.
Algo tipo:
resources\appre\advpl\x86\mac

**Comment by rodrigopg** [comment]
Saquei!

Achei na pasta do TDS pra 32 e 64 bits, mas o nome do arquivo é libappre.dylib
tentei jogar o arquivo no /Applications/ mas mesmo assim não deu.

Você tem o arquivo aí no seu mac? pode me enviar?

Obrigado!!

**Comment by rodrigopg** [comment]
Lista dos arquivos que encontrei.

Rodrigos-MacBook-Pro:appre rodrigo$ pwd
/Applications/TDS/plugins/br.com.totvs.tds.externaltools_11.3.6.201710030504/resources/appre
Rodrigos-MacBook-Pro:appre rodrigo$ find . | grep appre
./advpl/x86/win/appre.dll
./advpl/x86/mac/libappre.dylib
./advpl/x86/linux/libappre.so
./advpl/x86_64/win/appre.dll
./advpl/x86_64/mac/libappre.dylib
./advpl/x86_64/linux/libappre.so

**Comment by killerall** [comment]
O TDS passou a usar o appre por library ao inves de execução normal.
Uma solução temporária é conseguir isso de algum MAC que tenha uma versão não atualizada.(Eu não tenho MAC) Ou tentar instalar a  versao 11.2 e ver se tem la.
Esta no nossos planos trocar a maneira pela qual é feito toda essa parte, para conseguir compilar em linux também, porem essa solução vai demorar um pouco pra sair.

**Comment by rodrigopg** [comment]
Instalei a versão 11.2 e realmente tem o arquivo appre, mas acho que ele não funciona mais. nem direto do TDS 11.2 consegui conectar no servidor.

Estou mandando a pasta com os arquivos, se quiserem testar aí. eu não consegui nada ainda.

[APPRE.zip](https://github.com/killerall/advpl-vscode/files/1360700/APPRE.zip)

**Comment by mailsongabriel** [comment]
boa tarde, estou tendo o mesmo problema ao compilar no windows:

"Property 'smartclientPath' apppre.exe we cant' find  in \\192.1.1.185\Smartclient_185"

1) consigo abrir o smartclient via CTRL+F5
2) appre.exe está na pasta
3) limpei a \temp\
4) arquivo AdvplDebugBridge.log é gerado sempre em branco
5) settings:

{
"advpl.environments":[{
        "smartClientPath": "\\\\192.1.1.185\\Smartclient_185",
        "environment": "COMPILA",
        "includeList": "\\192.1.1.185\\INCLUDE\\",
        "server": "192.1.1.185",
        "port": "10239",
        "user": "USER",
        "passwordCipher": "K0EzN0w4dkdWYkdEbTBDL1lPb01IMlFoeDFrZGxkTWJ0TnZ1b0svT3dWdWNCbGxEd0plUHBiRlpIbHo5cWxLa1lzY0pZMzFjeERiV3ZYMFpzeXducmxsdVI3WXd2UlpZRzV6K1dZcHI4K3NETzlWL0huNmwySE8xcFduZ0lnMmE=",
        "advpl.logger": "true",
        "serverVersion": "131227A"
   }]
   ,
"files.encoding": "windows1252",
"advpl.selectedEnvironment": "COMPILA"
}

Obrigado

**Comment by mailsongabriel** [comment]
acabei de notar que a mensagem diz "apppre.exe", quando deveria ser "appre.exe" 

parece estar procurando um arquivo com 3 p´s e não 2.

**Comment by killerall** [comment]
Acredito, que não esta preparado para utilizar caminhos de rede não mapeados.

Tente mapear no windows o seu \\ para uma unidade.

**Comment by mailsongabriel** [comment]
Compilação OK
Compile Finish at Thu Dec 07 2017 15:16:48 GMT-0200 (Horário brasileiro de verão) Elapsed  (10.72 segs.)

Obrigado! Fiz o mapeamento e funcionou :)

**Comment by globsecure** [comment]
Olá,

Estava passando pelo mesmo problema com meu TDS executando no High Sierra após pesquisas e muito me bater,  fiz um stack na execução e identifiquei que o problema do appre que estava acontecendo no TDS era apenas porque o repositório era divido em pastas com acentos. E como o projeto foi criado no WINDOWS as acentuações não são bem-vindas para sistemas UNIX.

**Problema:** 
APPRE pré-build não funcionando devido aos acentos de pastas.

**Soluções:**
Renomear as pastas removendo os acentos.

---

Att

**Comment by killerall** [comment]
Bacana, fica aqui o registro.

**Comment by globsecure** [comment]
@rodrigopg  - No meu caso eu apenas tive que alterar os nomes das minhas pastas que estavam com acentos. De qualquer maneira para garantir eu copiei os arquivos appre que estão dentro do TDS (não visual code) e coloquei nas libs do Mac. Porém a solução só veio quando a renomeação das pastas sem acentos.

**Comment by rodrigopg** [comment]
@globsecure no meu não tem acentos nas pastas! 
Vc jogou o arquivo libappre.dylib dentro de /usr/lib/ ?? 
Na sua pasta /Applications/ não tem o arquivo appre??

Se tiver ele aí pode me passar?

**Comment by globsecure** [comment]
Localização do libappre.dylib - Dentro da pasta do TDS - Plugins:

![screen shot 2018-04-26 at 09 51 38](https://user-images.githubusercontent.com/1958192/39306793-7892af94-4937-11e8-9324-1ea39d9749db.png)


Localização da lib dentro do MAC:
![screen shot 2018-04-26 at 09 52 43](https://user-images.githubusercontent.com/1958192/39306844-9629289e-4937-11e8-85ef-14ec50c23646.png)

**Comment by rodrigopg** [comment]
Já copiei para a pasta indicada...
<img width="858" alt="screen shot 2018-04-30 at 1 04 45 pm" src="https://user-images.githubusercontent.com/5282959/39437524-7c21f53c-4c77-11e8-94b3-dbe6b1a7264a.png">

 mas continuo recebendo o erro quando tento compilar no Visual Code.
<img width="1323" alt="screen shot 2018-04-30 at 1 01 34 pm" src="https://user-images.githubusercontent.com/5282959/39437503-66f9f614-4c77-11e8-8191-001b21190125.png">

Ele está tentando achar o arquivo appre na pasta Applications, inclusive se eu renomear a libappre pra appre o Code tenta utilizar...
<img width="881" alt="screen shot 2018-04-30 at 1 10 39 pm" src="https://user-images.githubusercontent.com/5282959/39437707-035c7b94-4c78-11e8-9bd0-f6939a6d40f9.png">
