### ISSUE TITLE
Erro ao excluir fonte do repositório

### ISSUE THREAD

**Issue by gabrielaluche** [killerall/advpl-vscode#128]
Ao excluir um fonte do repositório, está ocorrendo o seguinte erro:
Advpl Iniciando
Iniciando exclusão do(s) fonte(s) MT410TOK

Compilação OK
TypeError: this.afterCompile is not a function

Gerei um *.txt dos fontes do repositório e verifiquei que o fonte continua lá.

**Comment by killerall** [comment]
Realmente consegui reproduzir aqui.
Vou ajustar aqui.
Obrigado.
