### ISSUE TITLE
Compilar um fonte limpa toda visão de problemas

### ISSUE THREAD

**Issue by izacsc** [killerall/advpl-vscode#134]
Ao compilar qualquer fonte a visão de problemas é limpa.

Ao mesmo tempo não é possível apagar nenhum item da lista de problemas.

**Comment by izacsc** [comment]
Esse comportamento é o desejado? Se quiserem posso fazer um pull request para alterar isso

**Comment by killerall** [comment]
O problema é quando iria limpar se não limpar sempre.
