### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by jerfweb** [killerall/advpl-vscode#135]
Killerall,

Baixei a versão 1.17.2 do Visual Studio Code, configurei de acordo com as informações abaixo e quando tento complilar a seguinte mensagem é exibida:
_Iniciando compilação do fonte e:\GRUPO MARSARO\Projeto Marsaro\FONTES_MARSARO\Producao_ _Loja\Relatorios\REvoluCompCliente.prw_

_Compile Start at Thu Oct 26 2017 14:52:46 GMT-0300 (Hora oficial do Brasil)_

_SyntaxError: Unexpected end of JSON input_
_Compile Finish at Thu Oct 26 2017 14:52:46 GMT-0300 (Hora oficial do Brasil) Elapsed  (0.402 segs.)_

Configuração:
{
    "advpl.environments":[{
        "smartClientPath": "E:\\SmartClient\\",
        "environment": "KS0AVG_TESTE",
        "includeList": "E:\\TOTVS 12\\Microsiga\\Protheus\\include\\",
        "server": "IPDOAMBIENT",
        "port": "2356",
        "user": "jerfferson",
        "passwordCipher": "MINHASENHA"
       },{
        "smartClientPath": "E:\\SmartClient\\",
        "environment": "KS0AVG",
        "includeList": "E:\\TOTVS 12\\Microsiga\\Protheus\\include\\",
        "server": "IPDOAMBIENT",
        "port": "2356",
        "user": "jerfferson",
        "passwordCipher": "MINHASENHA"
    }
],
"advpl.logger": true,
"advpl.compile_force_recompile": true
}

**Comment by killerall** [comment]
Tanto no caminho do SmartClient, quanto do includeList, coloque \\ ao inves de uma\ apenas.

Veja se resolve.

**Comment by jerfweb** [comment]
Eu deixei assim e não compila.
{
"advpl.environments":[{
"smartClientPath": "E:\\SmartClient\\",
"environment": "KS0AVG_TESTE",
"includeList": "E:\\TOTVS 12\\Microsiga\\Protheus\\include\\",
"server": "IPDOAMBIENT",
"port": "2356",
"user": "jerfferson",
"passwordCipher": "MINHASENHA"
},{
"smartClientPath": "E:\\SmartClient\\",
"environment": "KS0AVG",
"includeList": "E:\\TOTVS 12\\Microsiga\\Protheus\\include\\",
"server": "IPDOAMBIENT",
"port": "2356",
"user": "jerfferson",
"passwordCipher": "MINHASENHA"
}
],
"advpl.logger": true,
"advpl.compile_force_recompile": true
}

**Comment by killerall** [comment]
Vc ajustou as \ tipo assim?
"includeList": "C:\\Totvs\\vscode\\wk_12\\AdvplFramework\\src\\include\\;C:\\Totvs\\vscode\\wk_12\\AdvplFramework\\src\\include-lib\\",
"smartClientPath": "C:\\Totvs\\binarios\\P12\\last_tfs\\smartclient\\",

**Comment by jerfweb** [comment]
Inseri \\\ barras duplas no caminho conforme esta descrito no WIKI [https://github.com/killerall/advpl-vscode/wiki/Configura%C3%A7%C3%A3o](WIKI)

**Comment by killerall** [comment]
Veja se gerou o log na pasta temp da usa maquina:
C:\Users\rodrigo.antonio\AppData\Local\Temp
o Arquivo
AdvplDebugBridge.log

Anexa ele aqui.

**Comment by jerfweb** [comment]
Gerou, porem em branco!

**Comment by jerfweb** [comment]
![image](https://user-images.githubusercontent.com/20171106/32070284-a66c95c6-ba6a-11e7-84a7-03c1b1e61fd3.png)

**Comment by killerall** [comment]
Estranho.
A versão do seu appserver é a 131227A?
Você consegue dar Ctrl+F5? E chamar o SmartClient?

**Comment by jerfweb** [comment]
![image](https://user-images.githubusercontent.com/20171106/32070560-8417e812-ba6b-11e7-97dc-24fa46992a4e.png)

**Comment by izacsc** [comment]
Não é necessário informar todas as propriedades?
está faltando rpoType, language, serverversion...  Aliás, esse é um dos pontos que eu ia pedir uma melhoria. ter defaults para as propiedades rpoType, language, server (lolcalhost), server version, user(admin)

**Comment by killerall** [comment]
Faz um tempo que essas propriedades não são mais obrigatórias, ele pega do server.
O que pode estar acontecendo, é algum problema de parser de INI do lado server.

Mais o @jerfweb  não informou se consegue entrar com CTRL+F5 .

Lembrando sempre que precisa ter uma pasta aberta, ( e não apenas um fonte), e o ambiente selecionado no canto inferior esquerdo.

**Comment by jerfweb** [comment]
Killerall, realmente não está pegando o CTRL+F5, quando tento executar aparece a tela abaixo:

![image](https://user-images.githubusercontent.com/20171106/32072702-4d093072-ba72-11e7-8de4-a114fde57a26.png)

**Comment by killerall** [comment]
Sim
Salve esse arquivo, e tente novamente, deve aparecer o uma caixa de dialog para digitar a funcao, tente um sigadv so para ver se fecha a conexao.

**Comment by jerfweb** [comment]
@killerall o IDE chamou o SmartClient, porem chamando a função erra e ainda não conseguir compilar:

![image](https://user-images.githubusercontent.com/20171106/32074429-25b089ca-ba78-11e7-98d5-3806fcea4e05.png)

**Comment by killerall** [comment]
Tenta mover seus includes, para um diretório sem espaço.

**Comment by jerfweb** [comment]
@killerall Ajustei o caminho dos includes e do fonte, conforme imagens abaixo:

![image](https://user-images.githubusercontent.com/20171106/32075040-4446ea94-ba7a-11e7-82e2-ce761338f073.png)

![image](https://user-images.githubusercontent.com/20171106/32075061-56980cb4-ba7a-11e7-8276-08486b0eea9a.png)

**Comment by killerall** [comment]
Cara, no INI do seu server, tem comentario , com #, ou caracteres estranhos

**Comment by afucher** [comment]
Esse password cipher está muito pequeno, você gerou pelo comando de cipher?

**Comment by afucher** [comment]
@jerfweb ainda está com o erro?

**Comment by paulohenriquemoura** [comment]
Tive o mesmo problema é deve ser algo relacionado a workspace, quando mando compilar utilizando o mouse (clicando com o botão direito no fonte) o erro ocorre, já quando estou dentro do fonte e mando compilar pressionando <CTRL>+<F9>, o fonte é compilado com sucesso. Ainda não consegui descobri o real motivo, mas uma alternativa é utilizar o atalho de teclado para compilar.
