### ISSUE TITLE
Não consigo configurar o debug

### ISSUE THREAD

**Issue by gabrielaluche** [killerall/advpl-vscode#140]
Estou com dificuldades para configurar o debug. Poderia me passar as instruções de como configura-lo?
Obrigada!

**Comment by edusfc15** [comment]
@gabrielaluche já deu uma olhada na wiki?

https://github.com/killerall/advpl-vscode/wiki/Execu%C3%A7%C3%A3o-e-Debug

**Comment by alvarocneto** [comment]
Se o ambiente está corretamente configurado, o debug é apenas apertar o F5, na primeira vc escolhe ADVPL.
Exclua o arquivo launch.json na pasta .vscode e faça o procedimento novamente.

**Comment by gabrielaluche** [comment]
Quando pressiono F5 para iniciar o debug, aparece o seguinte erro:
Cannot find runtime 'node' on PATH. Make sure to have 'node' installed.

**Comment by alvarocneto** [comment]
![image](https://user-images.githubusercontent.com/17092119/32604143-bab53ece-c533-11e7-9bc8-e7e692ecbd02.png)
Não chega aparecer esse combo?

**Comment by alvarocneto** [comment]
Você tem q escolher a segunda opção
A primeira Node é para debug de aplicações Node/Javascript

**Comment by edusfc15** [comment]
> Cannot find runtime 'node' on PATH. Make sure to have 'node' installed.

Você deve ter escolhido Node.js na hora do debug, tem que ser Advpl Debug.

**Comment by gabrielaluche** [comment]
Não aparece....

![image](https://user-images.githubusercontent.com/28983850/32604217-04c06e62-c534-11e7-83b2-a98ffe72a6d5.png)

**Comment by alvarocneto** [comment]
Vc apagou o launch.json da pasta .vscode?

**Comment by gabrielaluche** [comment]
Não. Tem que apagar?

**Comment by alvarocneto** [comment]
sim apaga e a lista vai aparecer de novo ai vc seleciona o ADVPL

**Comment by alvarocneto** [comment]
.vscode/launch.json

**Comment by gabrielaluche** [comment]
apaguei e selecionei ADVPL.

**Comment by gabrielaluche** [comment]
obrigada pela ajuda. Funcionou
