### ISSUE TITLE
Erro ao compilar MAC

### ISSUE THREAD

**Issue by Evandroafv** [killerall/advpl-vscode#143]
Versão 0.7.5
Ao compilar no Mac: Error Running the contributed command:'advpl.menucompile' failed.
Ao tentar gerar senha não está gerando.

**Comment by Evandroafv** [comment]
Copiei o executável para pasta. Só não entendi essa parte "Dar acesso a execução no arquivo".

**Comment by Evandroafv** [comment]
Eu fiz o que está aí, mas continuo com o mesmo problema.
No Windows funciona muito bem, mas no Mac está complicado.

**Comment by Evandroafv** [comment]
Bom dia. Conseguiu verificar isso pra mim? Vi que outras pessoas também apresentaram algum problema ao usar o mac. O meu até pra gerar a senha não está aparecendo.

**Comment by killerall** [comment]
Ele não esta gerando por que não esta conseguindo executar o programa.
Não tenho MAC para consegui te ajudar.

**Comment by killerall** [comment]
Versão mac e linux liberada na versao 0.9.0.
