### ISSUE TITLE
Erro ao tentar gerar uma patch

### ISSUE THREAD

**Issue by brunoluizsa** [killerall/advpl-vscode#146]
Boa tarde!

Pessoal,

não estou conseguindo gerar uma patch, consigo compilar o fonte, debugar mas quando vou tentar gerar uma patch aparece o erro: "It was not possible to read the RPOVersion, Language or RpoDB information in INI file."

Configurações do meu appserver.ini:

RpoDB=top
RpoLanguage=portuguese
RegionalLanguage=BRA
RPOVersion=120

Configurações do ambiente no VS Code:

"smartClientPath": "C:\\Amb\\Ret12\\Protheus\\bin\\smartclient\\",
"name": "Ret12",
"environment": "Ret12",
"rpoType": "TOP",
"includeList": "C:\\Includes\\",
"server": "127.0.0.1",
"port": "1030",
"user": "Admin",
"passwordCipher": "K0NuU2YxMHVkeWllOWwzU25yYkdVZHZ0bENBNWp3ZkNsemY3Rk5vejI2ek9renpCMFVLQlVSeEdValpwakpSZUtuUE8yZFRDQmsxNmJzMFhxeVZFNmFXQWVmcnB0LzFOSks4akJVcUE1Q21ySWFGU1NlNG5TN0xFVjE1c0hiSHQ=",
"RPOLANGUAGE":"Portuguese",
"RPOVERSION":"120"

"advpl.compile_force_recompile": true,
"advpl.authorization_generation": "20171128",
"advpl.authorization_validation": "20180226",
"advpl.authorization_permission": "1",
"advpl.authorization_code": "015EBF032BVHB74A1E7671248",
"editor.fontSize": 12,
"files.encoding": "windows1252",    
"advpl.debug_ignoreSourceNotFound": true,
"workbench.iconTheme": "vs-minimal",
"workbench.activityBar.visible": true,
"editor.minimap.enabled": false,
"advpl.debug_multiThread": false,
"advpl.compile_threads": 4,
"advpl.pathPatchBuild": "C:\\Pacotes\\",
"window.zoomLevel": 0,
"workbench.colorTheme": "Visual Studio Light"

O meu arquivo com a lista dos fontes criei dentro do mesmo diretório onde esta os meus fontes, revisei permissões de diretórios e mesmo assim não consigo gerar.

Por favor, podem me ajudar ?

obrigado.

**Comment by killerall** [comment]
É provavel que exite algum caracter invalido no seu ini
Adicione "advpl.logger": true

Veja se gerou o log na pasta temp da usa maquina:
C:\Users\USUARIO\AppData\Local\Temp
o Arquivo
AdvplDebugBridge.log

Poste ele aqui.

**Comment by brunoluizsa** [comment]
Bom dia!

segue o arquivo.

obrigado.
[AdvplDebugBridge.log](https://github.com/killerall/advpl-vscode/files/1538832/AdvplDebugBridge.log)

**Comment by killerall** [comment]
Esta dando no parser do seu ini:
Thread[1] - 07/12/2017 09:23:58: IniParser.Exceptions.ParsingException: Unknown file format. Couldn't parse the line: 'ï»¿'. while parsing line number 0 with value '' - IniParser version: 2.4.0.0 while parsing line number 1 with value 'ï»¿' - IniParser version: 2.4.0.0 ---> IniParser.Exceptions.ParsingException: Unknown file format. Couldn't parse the line: 'ï»¿'. while parsing line number 0 with value '' - IniParser version: 2.4.0.0
   em IniParser.Parser.IniDataParser.ProcessLine(String currentLine, IniData currentIniData)

Veja no INI com algum editor tipo notepad++, se esse caracteres no inicio do INI.  'ï»¿'

**Comment by brunoluizsa** [comment]
Godinho,

apenas para informar, copiei todo o conteúdo do meu appserver.ini joguei em um arquivo novo do notepad++ e salvei novamente. O problema foi resolvido.

Muito obrigado pela ajuda.

Abraços.
