### ISSUE TITLE
Can't connect to server with this user

### ISSUE THREAD

**Issue by poliestermoreira** [killerall/advpl-vscode#147]
Sou novato com a ferramenta!
Fiz todos os passos referentes a criação dos ambientes e principalmente os passos da geração do cipher da senha.
Mas, infelizmente, sempre que tento compilar algum fonte recebo o retorno de: Can't connect to server with this user:admin
Já tentei com Admin, admin e nada...
Já copiei o cipher da senha com o sinal de "=" no fim, e também sem ele. E nada...
Certifiquei-me, diversas vezes, de ter digitado a senha correta. E ela está correta!
Lembrei-me também que no TDS tinha uma característica de que se você não tivesse conectado naquele ambiente naquele dia para poder criar as moedas x calendário, o TDS não permitia a conexão. Lembrando-me disso fiz o acesso ao ambiente para realizar a criação das moedas x calendário e mesmo assim, nada...
Não consigo compilar!

**Comment by killerall** [comment]
Poste aqui o json que vc configurou.

**Comment by poliestermoreira** [comment]
Vou inibir os endereços de IP e os nomes dos clientes...

{
    "advpl.selectedEnvironment": "",
    "advpl.environments": [{
        "smartClientPath": "C:\\Chaus\\Cliente1\\SmartClient_P11_Prod\\",
        "environment": "Cliente1 - P11",
        "includeList": "C:\\Install\\include\\",
        "server": "123.12.12.12",
        "port": "2312",
        "user": "Administrador",
        "passwordCipher": "R0cvY0Exem5XdmVXeUF4K0tsYTR1L3diSlVkcDh6d2xvZ0N0THl0dVB3MSs3NkZIdFRPUGUwQW1GcDlQL1pTYXBYQUVta0k4ejQraFNZTTcxOFl2TlJoYXIydk5weHZwMms5Y2ZPRlFuYUEzeVBQNmcyZXRXeFl6UkowbmpteTY=",
        "language": "protuguese",
        "rpoType": "TOP"
    },
{
    "smartClientPath": "C:\\Chaus\\Cliente2\\SmartClient_P12\\",
    "environment": "Cliente2 - P12",
    "includeList": "C:\\Install\\include\\",
    "server": "123.12.12.123",
    "port": "7854",
    "user": "Administrador",
    "passwordCipher": "N2Jua3ZnRVgvOEJVNWlHWmw3aXFPRzRhZXU1SDh0cDNld0xCN3N2aVBOWlpjYTBsR09jYTNVTVJtRE01TFhhenlrVEpGRXZ5dXBvREtYTFc5bTRwNEtmcERuL0FrNmxvUlhTNnJzZ2hpRHlNMGt6TFJTb2RRSG54QXZNQ1V1dkc=",
    "language": "protuguese",
    "rpoType": "TOP"
},
{
    "smartClientPath": "C:\\Chaus\\Cliente3\\smartclient_teste\\",
    "environment": "Cliente3 - Teste",
    "includeList": "C:\\Install\\include\\",
    "server": "123.12.12.123",
    "port": "1244",
    "user": "chaus",
    "passwordCipher": "NWxub1F3TTBWSHdIWGU2WXVoMXVqcTcrQ1hneXFqemRodnlZZE5KbzdZQjB4RitmSzlMU3JyN0lsTm1RN2x2Z1I5dCt6eGpSYU8rbFpqbmd2WGEwcVdBREtHSS81bWpWSldjMTlnV05haDlMMlF0V2tQNUpUSU4wVFppeTQrR0g=",
    "language": "protuguese",
    "rpoType": "TOP"
},
{
    "smartClientPath": "C:\\Chaus\\Cliente4\\smartclient\\",
    "environment": "Cliente4",
    "includeList": "C:\\Install\\include\\",
    "server": "10.1.1.230",
    "port": "1250",
    "user": "chaus",
    "passwordCipher": "NWxub1F3TTBWSHdIWGU2WXVoMXVqcTcrQ1hneXFqemRodnlZZE5KbzdZQjB4RitmSzlMU3JyN0lsTm1RN2x2Z1I5dCt6eGpSYU8rbFpqbmd2WGEwcVdBREtHSS81bWpWSldjMTlnV05haDlMMlF0V2tQNUpUSU4wVFppeTQrR0g=",
    "language": "protuguese",
    "rpoType": "TOP"
}
],
"advpl.startProgram": "SIGAMDI",
"advpl.pathPatchBuild": "c:\\temp\\",
"advpl.debug_ignoreSourceNotFound": true,
"advpl.debug_showTables": true,
"advpl.debug_showPrivates": true,
"advpl.debug_showPublic": true,
"advpl.debug_showStatics": true
}

**Comment by izacsc** [comment]
Poliester, tem alguns erros no seu Json.

Toda vez que vc for escrever "\" ela deve ser escrita como "\\", ou seja todos os seus caminhos estão errados. Ex: "advpl.pathPatchBuild": "c:\temp\" deve ser "advpl.pathPatchBuild": "c:\\temp\\".

Você acabou escrevendo errado "protuguese" em vez "portuguese" todas as vezes.

Inicialmente foi o que pude notar. Abraço

**Comment by poliestermoreira** [comment]
izacsc, as barras já estão duplas, mas na hora de copiar e colar aqui elas vieram como simples.
vou corrigir o portuguese e tentar novamente....

**Comment by poliestermoreira** [comment]
Acabei de corrigir o portuguese e certifiquei-me de que as barras estao \\
Mesmo assim, a mensagem persiste.

**Comment by killerall** [comment]
Adicione a seguinte chave no seu json:
"advpl.logger": true

Veja se gerou o log na pasta temp da usa maquina:
C:\Users\USUARIO\AppData\Local\Temp
o Arquivo
AdvplDebugBridge.log

Poste ele aqui.

**Comment by poliestermoreira** [comment]
Olá, bom dia!

Segue o log coletado, antes de postar aqui eu fiz a substituição de duas coisas: 1) O nome do cliente 2) O endereço de IP do servidor.

Thread[1] - 08/12/2017 06:41:51: Start.
Thread[1] - 08/12/2017 06:41:51: {"selectedEnvironment":"Cliente1 - P12","environments":[{"smartClientPath":"C:\\Chaus\\Cliente1\\SmartClient_P12\\","environment":"Cliente1 - P12","includeList":"C:\\Install\\include\\","server":"123.12.12.123","port":"7854","user":"Administrador","passwordCipher":"Z24za3gwYnE4dHRjemFuTU10L3NibDRiNzhSOEs3bzVtQWRUNll5V0p0Z2o2MmRDZkY1Rk9UUEF0SVRtWndBMXBJT2lDdUJYaTZGbkJPU3l1ZG0wVWs0M3NSdE83RFZ2bUdZbjltTkJmOWFFNnAvSVp4WDRzUGFPeWgvYmtCVmU=","language":"portuguese","rpoType":"TOP"}],"startProgram":"SIGAMDI","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|prg|apw|aph|tres|png|bmp|res)","pathPatchBuild":"c:\\temp\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":true,"debug_showPublic":true,"debug_showStatics":true,"compile_force_recompile":false,"logger":true,"compile_threads":4}.
Thread[1] - 08/12/2017 06:41:51: Starting MultiThread Compiler with 4 threads..
Thread[1] - 08/12/2017 06:41:56: {"msgs":[{"Key":"NOSOURCE","Value":[{"Line":1,"Column":0,"Type":0,"Message":"Can't connect to server with this user:Administrador"}]}]}.
Thread[1] - 08/12/2017 06:41:56: End.

**Comment by killerall** [comment]
Qual a versão do seu binario?

131227A  ou 170117A
?

**Comment by poliestermoreira** [comment]
700131227A - Protheus 12

**Comment by killerall** [comment]
Não consigo ver o por que esta dando isso.
O server e o vscode estão na mesma maquina?

**Comment by poliestermoreira** [comment]
O server está no cloud.

**Comment by killerall** [comment]
faz um teste, Tenta montar um server local, e configurar tudo.

**Comment by samaronybarros** [comment]
Isso já aconteceu comigo.

Verifica se é a chave de acesso.

"user": "Administrador",
"passwordCipher": "R0cvY0Exem5XdmVXeUF4K0tsYTR1L3diSlVkcDh6d2xvZ0N0THl0dVB3MSs3NkZIdFRPUGUwQW1GcDlQL1pTYXBYQUVta0k4ejQraFNZTTcxOFl2TlJoYXIydk5weHZwMms5Y2ZPRlFuYUEzeVBQNmcyZXRXeFl6UkowbmpteTY="

Pode ser que a senha informada no `>cipher` não esteja correta.

**Comment by wfsouza** [comment]
Estava com o mesmo problema, fui no monitor e exclui a pessoa que estava usando o ambiente (eu mesma..kkkk) e depois foi normal.
