### ISSUE TITLE
Valores que não são alterados.

### ISSUE THREAD

**Issue by poliestermoreira** [killerall/advpl-vscode#148]
Seguindo um excelente tutorial disponibilizado pela Gabriela, consegui realizar as configurações dos servers. Mas, pude perceber um detalhe, que não sei se é normal, ou se não é.
Após alterar os valores, do lado direito da tela do print, e salvá-los, pude observar que, do lado esquerdo, eles não foram gravados.
Já reiniciei diversas vezes o vscode e mesmo assim essa característica continua.
Como disse em outro post, sou novato na ferramenta, logo, essa dúvida poderá ser algo bastante idiota. Mas é uma dúvida... rsrsrs
Obrigado!

![image](https://user-images.githubusercontent.com/23110260/33713155-3f7b915e-db31-11e7-944f-ae7e344376bc.png)

**Comment by izacsc** [comment]
Poliester esse comportamento é normal.

No lado esquerdo estão os padrões da ferramenta e na direita estão configurações de usuário. As informações da esquerda não serão substituídas pelas da direita, mas isso não quer dizer que as informações da direita não estão sendo utilizadas.

Sempre que você tiver uma configuração de usuário ela será usada em vez da configuração default.

**Comment by afucher** [comment]
@poliestermoreira por curiosidade, qual tutorial? Onde acho?

**Comment by poliestermoreira** [comment]
Essas aqui...

Poliester Moreira
poliester.m@gmail.com
poliester.moreira@hotmail.com
Goiania - Go.

2017-12-13 23:30 GMT-02:00 Arthur Fücher <notifications@github.com>:

**Comment by afucher** [comment]
@poliestermoreira acho que ficou faltando o link..

**Comment by poliestermoreira** [comment]
Eu tinha respondido direto do gmail e tinha enviado os anexos por lá, mas não vieram... rsrsrs
Agora acho que vai dar certo!
[Tutoriais de configuracao.zip](https://github.com/killerall/advpl-vscode/files/1558945/Tutoriais.de.configuracao.zip)

**Comment by afucher** [comment]
@poliestermoreira deletei o comentário pois vi que possui informações que acho que não são muito interessantes ficarem públicas.
Achei o conteúdo bem interessante, se possível veja com a Gabriela se ela não quer contribuir com a Wiki e documentações que temos aqui no repositório.
Qualquer coisa meu e-mail é arthurfucher@gmail.com
