### ISSUE TITLE
Replace in settings ao invés de Edit

### ISSUE THREAD

**Issue by poliestermoreira** [killerall/advpl-vscode#149]
Ao posicionar o mouse sobre o lápis para poder editar o arquivo de configuração, aparece a opção Replace in settings ao invés de Edit.
E ao clicar, a configuração é jogada para o lado direito e depois de alterar e pressionar CTRL+S ela não fica salva do lado esquerdo.

![image](https://user-images.githubusercontent.com/23110260/33714126-0352950c-db35-11e7-8fb1-3b5c3ac1be40.png)

**Comment by killerall** [comment]
@poliestermoreira Isso é uma feature do VsCode, não da extensão.

Ele nunca salva o do lado de esquerdo. isso é o Default.
