### ISSUE TITLE
Error in 64 bits version

### ISSUE THREAD

**Issue by eternauta123** [killerall/advpl-vscode#150]
Sei que a 64 nao esta liberada oficialmente, mas da este erro ao tentar compilar

SyntaxError: Unexpected end of JSON input

**Comment by eternauta123** [comment]
Perfeito... Obrigado... 
Poderia melhorar a mensagem so para entender e resolver... 
Abraco!

**Comment by vlopes11** [comment]
Mesmo problema aqui e corrigido após setar 

`"advpl.environments":[{ (...) "serverVersion": "170117A", (...) }],`

A colocação do @eternauta123  está correta, não há qualquer pista de que o erro está na serverVersion. Eu escreveria uma mensagem mais amigável em resposta a essa Issue, mas o AdvplDebugBridge.exe está no modo caixa preta. @killerall , seria possível incluirmos o source dele aberto aqui como parte do projeto?

**Comment by vlopes11** [comment]
Issue duplicada #136

**Comment by killerall** [comment]
Será corrigido em breve a mensagem.
