### ISSUE TITLE
Troca do Compiler Auth ID

### ISSUE THREAD

**Issue by ShinyTotvs** [killerall/advpl-vscode#151]
É possível efetuar a troca do Auth ID?
Minha autorização de compilação foi gerada para minha unidade E:, onde instalei o VsCode, porém ao executar a função Compiler Auth ID, retorna o ID da minha unidade C: .

Como faço?

**Comment by killerall** [comment]
Como assim?
Não entendi.

**Comment by ShinyTotvs** [comment]
Minha autorização de compilação foi gerada para minha unidade E:, onde instalei o VsCode, porém ao executar a função Compiler Auth ID, retorna o ID da minha unidade C: .

**Comment by killerall** [comment]
Entendi,
Não é possivel,

Você vai precisar reinstalar o vscode, no E:  ou pedir outro chave.

**Comment by killerall** [comment]
é verdade,
Por que a extensão é instalada na pasta de usuário, que fica no C:\
Ou você vai ter que gerar realmente uma chave pro C:, ou trocar a pastas de usuario da sua maquina para o E, que não é simples nem recomendo.

**Comment by ShinyTotvs** [comment]
Valew KillerAll...
