### ISSUE TITLE
Fonte para Patch em pasta.

### ISSUE THREAD

**Issue by robsonrosilva** [killerall/advpl-vscode#158]
Gostaria de saber se há alguma forma de gerar um patch com arquivos de diferentes pastas, tentei usando o arquivo base para o patch com o seguinte conteúdo:

SIGAFAT/BSFATA01.prw
GERAL/PUTSX1.prw

O patch foi gerado vazio.

**Comment by killerall** [comment]
vc deve colocar apenas o nome do fonte. ele nao olha pasta. apenas o nome do fonte, e extensao igual ao que esta no rpo.

**Comment by robsonrosilva** [comment]
Ele gera a partir do fonte do RPO, achei que fosse do fonte que está no projeto. 

Tentei gerar mas aparece esse erro: It was not possible to read the RPOVersion, Language or RpoDB information in INI file."

**Comment by killerall** [comment]
Deve ter algum caracter de errado no seu ini.
habilita o advpl.logger  ele vai gerar no temp do seu usuario um arquivo AdvplDebugBridge.log la deve dar a linha de erro no ini.

**Comment by alwisnhe** [comment]
Estava com o mesmo problema e habilitando o advpl.logger consegui encontrar o problema no arquivo INI.
