### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by vlopes11** [killerall/advpl-vscode#163]
With our increasing base of English speaking users, there is the need to implement localized string resources to provide feedback messages with extensible languages (PT-BR, EN, RU, etc.)

For this, we should follow the i18n pattern according to the following examples:
`const message = localize('sayHello.text', 'Hello')`
https://github.com/Microsoft/vscode-extension-samples/blob/master/i18n-sample/src/extension.ts#L14

https://github.com/Microsoft/vscode-extension-samples/blob/master/i18n-sample/i18n/jpn/package.i18n.json

All fixed message strings should be changed to call the localize function.

**Comment by eternauta123** [comment]
I suggest to use RESX microsoft format for i18n, with this format my team can colaborate with translations.

**Comment by vlopes11** [comment]
Available @ https://github.com/killerall/advpl-vscode/pull/182
