### ISSUE TITLE
ADVPL - NO DEBUG - Executável

### ISSUE THREAD

**Issue by aco-augusto** [killerall/advpl-vscode#169]
Para versão MAC foi passada a orientação abaixo, mas o arquivo vaio num formato .dms. Tem como mandar em um mais comum (zip, rar, dmg) ? Caso não, por gentileza, passe o link do programa que consegue abrir essa extensão. Obrigado.

Efetuar o download do executavel Copiar o mesmo para a pasta: ~/.vscode/extensions/KillerAll.advpl-vscode-x.x.x/bin Dar acesso a execução no arquivo.

**Comment by killerall** [comment]
Estamos reescrevendo a versão MAC e linux. Em breve teremos novidades.

**Comment by killerall** [comment]
Versão mac e linux liberada na versao 0.9.0.
