### ISSUE TITLE
MacOs - Compiler Cipher

### ISSUE THREAD

**Issue by willianvilhena** [killerall/advpl-vscode#171]
Bom dia, 
instalei a extensão no MacOS versão High Sierra v. 10.13.3, ao solicitar a geração pelo Cipher a senha criptografada não aparece no Output da IDE.

fiz conforme instrução:
Efetuar o download do executavel Copiar o mesmo para a pasta: ~/.vscode/extensions/KillerAll.advpl-vscode-x.x.x/bin Dar acesso a execução no arquivo.

Mesmo assim não consigo gerar a senha Criptografada.

**Comment by killerall** [comment]
Bom dia,
É provável que não funcione por conta da versão que foi compilado o Bridge.
Estou terminando de portar o código fonte para C++ puro, que ira funcionar com linux e Mac de forma nativa.
Peço um pouco de paciência, mais em breve teremos uma versão nativa em ambas as plataformas.

**Comment by willianvilhena** [comment]
Obrigado Pela Resposta Rápida, vou aguardar pela atualização, estou doido pra sair do TDS 😆

**Comment by ederneo** [comment]
@willianvilhena boa tarde,

Você poderia compartilhar conosco a sua configuração para MAC OS, gostaria de saber como ficam os caminhos para o Remote. Obrigado.

**Comment by willianvilhena** [comment]
Boa tarde Ederneo, eu não montei o arquivo de configuração, porque nenhum comando da Extensão funcionou para mim :/, por exemplo o comando "ADVPL - Cria environment para Conexão" retorna o erro 'command 'advpl.addAdvplEnvironment' not found', você conseguiu fazer os comandos das extensões funcionar no seu MAC OS?

**Comment by ederneo** [comment]
Então @willianvilhena o meu também está apresentando essa mesma mensagem! estou com a ultima versão do visual code! @killerall Alguma dica para o mensagem assim? No caso dos diretórios do MAC como apontar o remote do MAC? Obrigado!

**Comment by killerall** [comment]
@ederneo e @willianvilhena 
Boa tarde,
Como disse acima, estou rescrevendo a parte Mac/Linux para funcionar corretamente.
Em MAC OS, a versão atual até consegue rodar, em versões especificas de macos(e antiga), instalando mono, e fazendo um monte de coisa. 
Peço um pouco mais de paciência, que logo teremos a versão que funciona nas 3 plataformas de forma satisfatória.

**Comment by afucher** [comment]
Em relação aos comandos, abram qualquer fonte com extensão de advpl, prw
por exemplo. Isso força a ativação da extensão e dos comandos.

**Comment by endersonmaia** [comment]
@killerall também tenho o mesmo problema reportado nesta issue, e aguardo a solução

mas fico me perguntando, estes binários todos que vc disponibiliza no repositório, têm o código aqui no repositório ou outro local, pois permitiria que colaborássemos também, e daria mais transparência no que estamos instalando em nossas máquina 😉

**Comment by Carraro-BH** [comment]
Willian, bom dia!
Talvez já tenha resolvido o problema (pois o tópico não é tão recente), mas tenho o VS em MAC e a extensão funciona perfeitamente, exceto para compilação (em razão do appre.exe ter sido alterado para uma dll, portanto aguarda publicação da alteração do projeto). Consigo realizar debug normalmente, bem como seleção de ambientes, cipher, leitura de conteudo do RPO, entre outros. Para tanto é necessário que o arquivo AdvplDebugBridgeMac.dms baixado (que deve ser colocado no caminho ~/.vscode/extensions/KillerAll.advpl-vscode-x.x.x/bin) passe por dois passos:
1) Renomea-lo, retirando o .dms do final e deixando-o sem extensão
2) Modificar as permissões deste arquivo com o comando "sudo chmod 755 [arquivo]" (deixando-o como -rwxr-xr-x@) através do terminal.

Espero ter ajudado.

Carraro

**Comment by killerall** [comment]
Versão mac e linux liberada na versao 0.9.0.
