### ISSUE TITLE
Utilizando VSCODE no Kubuntu 16.04

### ISSUE THREAD

**Issue by fernandosalvatori** [killerall/advpl-vscode#172]
Prezados, trabalho com PYTHON para desenvolvimento de automações, e em algumas delas, vou precisar desenvolver alguns fontes em ADVPL.

Minha estação de trabalho é LINUX KUBUNTU 16.04 com VSCODE instalado e extensão PYTHON (funcionando 100%)

Meu problema é para instalar o complemento ADVPL, onde estou com uma tremenda dificuldade de conseguir compilar um fonte e configurar um settings.json.

OBS: No Windows eu consegui configurar tranquilo.

Sabem me dizer se o VSCODE/ADVPL está funfando no LINUX , se sim, alguem tem uma configuração exemplo?

Grato,
Fernando

**Comment by killerall** [comment]
A versão atual ainda não tem suporte ao Linux.
Dentro em breve devo disponibilizar uma versão Betao para Linux.

**Comment by fernandosalvatori** [comment]
Obrigado pelo retorno !!
#Acompanhando 

Abs,
Fernando

**Comment by jerfweb** [comment]
Olá,
Sou usuário de Linux Mint e queria saber se vocês tem alguma previsão para disponibilizar a versão Linux da extensão?

**Comment by killerall** [comment]
O desenvolvimento está indo bem, estou finalizando o debug. acredito que abril lance.

**Comment by jerfweb** [comment]
Muito bom... Agradeço o retorno e fico a disposição para qualquer ajuda nos testes!

**Comment by killerall** [comment]
Bom dia,
Esta bem perto de lançar.

**Comment by killerall** [comment]
Versão mac e linux liberada na versao 0.9.0.

**Comment by jerfweb** [comment]
\o/ valeu!

**Comment by silfar** [comment]
Bom dia, existe alguma mudança na configuração em relação ao windows ? Tem algum exemplo de config para linux ?

**Comment by killerall** [comment]
Bom dia. 
Tem que ver só a versao do seu linux se tem a lib 32 bits instalada.
https://github.com/killerall/advpl-vscode/wiki/Instala%C3%A7%C3%A3o-em-Linux-Mac-OS

**Comment by silfar** [comment]
Sim já estão, mas como ficam as configurações ?

**Comment by killerall** [comment]
a configuraçao é igual. so os paths que devem ser colocados no modelo linux.

**Comment by silfar** [comment]
quando tento debugar :+1: 
spawn /home/silfar/.var/app/com.visualstudio.code/data/vscode/extensions/killerall.advpl-vscode-0.10.4/bin/alpha/linux/AdvplDebugBridgeC ENOENT
E se tento compilar:
![captura de tela de 2018-07-09 16-29-28](https://user-images.githubusercontent.com/68900/42471784-60757854-8395-11e8-8c31-295219a5f9a9.png)

**Comment by silfar** [comment]
Minha config:
"environment": "DESENV",
			  "smartClientPath": "/home/silfar/TOTVS/smartclientLinux/",
			  //"smartClientPath": "D:\\Google_Drive\\TOTVS\\smartclient12\\",
			  "includeList": "/home/silfar/TOTVS/workspace/includes/",
			  //"includeList": "D:\\Google_Drive\\TOTVS\\workspace\\includes\\",
			  "server": "192.168.1.11",
			  "port": "1111",
			  "user": "usuario",
			  "passwordCipher": "VUdEZWlVdnh5SU5HYUpLaGZzVm1GN056Qk0zM0tBUnUrcVpYK0t3R1dTVUhxdlgxZXdtU0Z3TitNeXk4cTdtUUhydHNsSExINkRGemhUNys5L1JETE5PbjRZV256c3QvVUxSVTJ0bXVuRzdFYmR2N1pJTG95RVhwVkVVcjZtL28="

**Comment by killerall** [comment]
Você conseguiu compilar no linux?
gerou uma cipher nova?

**Comment by silfar** [comment]
Na verdade não tinha gerado não, mas tentei gerar agora, e nada acontece , não gera.

**Comment by killerall** [comment]
Veja qual versão da extensão foi instalada.
Parece que nào esta atualizada pela 0.10.4
(O seu vscode tem que estar atualizado tmb)

**Comment by silfar** [comment]
![image](https://user-images.githubusercontent.com/68900/42475128-1f7e9b2c-83a0-11e8-8294-91ac84b25b7a.png)
![image](https://user-images.githubusercontent.com/68900/42475202-546277d2-83a0-11e8-8c1d-4573d47bc859.png)

**Comment by killerall** [comment]
Acesse a pasta da extensao do seu usuario, algo como:
/home/rodrigo/.vscode/extensions/killerall.advpl-vscode-0.10.4/bin/alpha/linux
e rode:
./AdvplDebugBridgeC --getID

Deve retornar o ID de compilacao.

**Comment by silfar** [comment]
Vixe não tem essa pasta.

**Comment by silfar** [comment]
Bom, acabei desistalando e instalando do site do vscode, acho que o pacote que o mint instala está ruim. Pelo consegui gerar o cipher, mas ainda não funcionou, se compilo recebo o seguinte erro :+1: Erro no IAFIN003.prw equest ignored -- RMS_DBGCOMPILE -- Build not started.
Compilação finalizada em Mon Jul 09 2018 18:45:24 GMT-0300 (-03) tempo consumido (10.295 segs.)
e no debugue até parece que vai mas ai não abre o client.

**Comment by killerall** [comment]
Veja no tmp do seu usuario se ele criou um arquivo AdvplDebugBridge.log, se sim posta ele aqui.

**Comment by silfar** [comment]
Onde fica esse tmp ? Tõ com o linuxmint.

**Comment by killerall** [comment]
Não conheço muito o mint,
se nao for no /tmp, talvez seja no /home/usuario/tmp

**Comment by silfar** [comment]
Não existe esta pasta.

**Comment by silfar** [comment]
Bom o arquivo de log eu não encontrei. A advpl.logger = "true" tem que ficar na configuração de usuario ? Tem como setar a pasta para ele criar o log ? 
Acabou funcionando aqui, sem eu fazer nada, na verdade eu só reiniciei o serviço.
