### ISSUE TITLE
Tag com "apelido" para ambientes

### ISSUE THREAD

**Issue by VctrAndrade** [killerall/advpl-vscode#174]
Pessoal.
    Existe alguma forma de apelidar um ambiente?
    
Hoje tenho um probleminha que é atender diferentes clientes que possuem o mesmo nome de ambiente, como por exemplo: TESTE, se existir alguma forma de apelidar o ambiente, ajudaria muito nesses casos.

Obrigado.

**Comment by afucher** [comment]
Utilize a propriedade `name` da configuração.
