### ISSUE TITLE
Debug F5

### ISSUE THREAD

**Issue by higorluizrz** [killerall/advpl-vscode#176]
Boa tarde!

Meu debug(F5) não encontra a rotina que acabei de compilar, digito 'u_vscode' e não da opção de executar.

{
    "editor.fontSize": 13,
    "files.encoding": "windows1252",
    "advpl.environments":[  
   {  
      "smartClientPath":"C:\\smartclient_LMTESTE12\\",
      "environment":"LMTESTE",
      "includeList":"C:\\Totvs\\include\\",
      "server":"10.1.0.120",
      "port":"8030",
      "user":"admin",
      "passwordCipher":"VkJzQyttd1loRXQrV3hZUDhlQlF0YlA2bzBRQzdCSHJzUGdrOHp2Q1N6YzZLYzgrNHYwbHgvV2xUc2FPTzF1b1h5Uk9VRmFKcWJFMXJDMCtsY1gyN2NKNEEvRjF5eXRVZzRleDU0MElyRUp2K0pCbDZoZEVucElTRjJnVkZ0SUM="
   }
],
"advpl.selectedEnvironment": "LMTESTE",
"advpl.startProgram": "SIGAMDI",
"advpl.debug_multiThread": true,
"advpl.workspaceFolders": "C:\\Totvs\\Workspace\\",
"advpl.debug_ignoreSourceNotFound": true
}

**Comment by killerall** [comment]
Boa tarde,
Ao compilar,
Você verificou no server se mostrou o nome do fonte e as linhas do arquivo?

**Comment by higorluizrz** [comment]
No vscode aparece:
Iniciando compilação do fonte c:\Totvs\Workspace\VsCode.prw

Compile Start at Thu Feb 15 2018 15:05:22 GMT-0200 (Horário brasileiro de verão)

Source VsCode.prw Skipped!
Compilação OK
Compile Finish at Thu Feb 15 2018 15:05:26 GMT-0200 (Horário brasileiro de verão) Elapsed  (3.336 segs.)

No console do servidor protheus:

[INFO ][SERVER] [Thread 572] [15/02/2018 15:05:24] Starting Debugger (POLITRIZ\higor.roza, LM01TICNB02)
[INFO ][SERVER] [Thread 572] [15/02/2018 15:05:26] Debugger finished (POLITRIZ\higor.roza, LM01TICNB02)

**Comment by killerall** [comment]
Agora ele fez skip do fonte.
SE você rodar via smartclient diretamente, ele chama a sua função?

**Comment by higorluizrz** [comment]
Sim, chama normalmente.

**Comment by higorluizrz** [comment]
![2018-02-15_15h12_31](https://user-images.githubusercontent.com/36513099/36270385-b1491532-1262-11e8-874d-e13f2166f165.png)

**Comment by killerall** [comment]
Poste aqui o seu launch.json

**Comment by higorluizrz** [comment]
Desculpa Rodrigo. Era mancada minha. Funcionou agora.

Outra dúvida, já usou SVN no VsCode?

**Comment by killerall** [comment]
Sem problema.
Nunca usei com SVN, apenas com o GIT.
Porem existe diversas extensões para SVN no MarketPlace do Vscode.

**Comment by tiagowelter** [comment]
Olá, tudo bem ? estou com esse mesmo problema do Skipped, como conseguiram resolver? Obrigado
