### ISSUE TITLE
Localization in user snippets

### ISSUE THREAD

**Issue by eternauta123** [killerall/advpl-vscode#177]
Desculpem abrir como Issue...
Veriifiquei que para usar uma variavel de string de lovalizacao deve ser referenciada como
		"description": "%extension.advpl.if.statement%"
mas nao estou achando documentacao de onde colocar essa variavel (deveria ser no package.nls.en.json por exemplo, da seguinte forma:
{
	"extension.advpl.if.statement": "Teste de localizacao"
}
Mas onde deve ficar o arquivo package? Fazem ideia?

**Comment by killerall** [comment]
Não tenho certeza se entendi o que você quer fazer, mais veja essa extensão.
https://github.com/Microsoft/vscode-extension-samples/tree/master/i18n-sample
Ela mostra como fazer a localização. E é como o proprio VSCODE faz.

**Comment by killerall** [comment]
Só mais 1 coisa, tem varias messagens que não estão na camada do TypeScript da extensão, e sim do Bridge, que não aberto, mais estou pensando numa maneira de possibilitar a traducao do mesmo.

**Comment by eternauta123** [comment]
Rodrigo, nao eh isso... Neste caso o string eh usado em um TS (que tem um metodo invocado para carregar os STR).
No meu caso, eh nos snippets, eh um arquivo advpl.JSON que tem que carregar a variavel com a traducao dentro de um campo dela. 
O seguinte strings fica, por exemplo, dentro do arquivo advpl.json
 "description": "%extension.advpl.if.statement%"

**Comment by eternauta123** [comment]
Mas quando abre o snippet faz isto:
![image](https://user-images.githubusercontent.com/34449118/36293194-8fe729c0-12e8-11e8-8645-6b8a2fe41403.png)

**Comment by killerall** [comment]
Não implementei nenhum Snippet, talvez o @izacsc  saiba como fazer isso.

**Comment by izacsc** [comment]
Não sei... Mas abri uma issue no repositório do vscode para perguntar Microsoft/vscode#43829

**Comment by izacsc** [comment]
Segundo o Erich Gamma(!) atualmente não é possível e virou um feature request.
