### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by eternauta123** [killerall/advpl-vscode#178]
Meu time criou snippets para um set de funcoes do ADVPL. Somos novo no hithub e nao soubemos como criar um PULL request e tb nao sei como fazer com o plugin as leia (localmente colocamos todos os snippets juntos no advpl.json de usuario, mas acreditamos serem mais faceis de adnministrar em arquivos separados por grupo de funcao).
Os aqruvos anexados represemtam pastas do TDN.

[Snippets_ok.zip](https://github.com/killerall/advpl-vscode/files/1738324/Snippets_ok.zip)

**Comment by izacsc** [comment]
Se não me engano a extensão só aceita um advpl.json. Você pode passar o arquivo completo? Eu faço o pull request

**Comment by eternauta123** [comment]
Izac posso mandar, mas a ideia é mesmo manter separado para facilitar a colaboração.
Acredito que a extensão tem que ser modificada para ler os outros (tem outra extensão de Sniper a que tem 3 arquivo a na pasta).
Mas como disse somos nem leigos.... também criamos para algumas classes, mas da erro porque o nome da classe se repete, então os deixei de fora... embora eu acho que ficaram utilizáveis... vou lhe enviar, quem sabe não acha uma forma de refazer o snippet para poder utilizar (Moira acredito que so vai rolar para o Language server).

**Comment by eternauta123** [comment]
O nome do método quis disser

**Comment by killerall** [comment]
@izacsc e @eternauta123 
Acredito que não se deve colocar a documentação de funções, como Snippet.
O ideal é colaborar com o projeto do language server:
https://github.com/advpl/advpl-language-server-cxx
Aonde toda a parte de autocomplete e documentação será feita por essa extensão.

**Comment by eternauta123** [comment]
@killerall de acordo... criamos uma extensão para meu time usar por enquanto e quando sair o language server o incorporamos la e apagamos... advpl codex 
Abraço!
