### ISSUE TITLE
Problemas com Watch + Variaveis de classe

### ISSUE THREAD

**Issue by fernandosalvatori** [killerall/advpl-vscode#180]
Amigos, boa tarde.

Não estou conseguindo abrir uma variavel de classe no Watch e nem no DEBUG CONSOLE.

OBS: Quando a variavel nao é classe, funciona tranquilo. 

Estou fazendo um workaround onde jogo a variavel classe pra dentro de uma variavel normal pra poder debugar.

Alguem sabe o que pode estar ocorrendo?
Grato
Fernando

**Comment by killerall** [comment]
Boa tarde,
Consegue postar uma user function exemplificando ?
