### ISSUE TITLE
Invalid Compile Key

### ISSUE THREAD

**Issue by DudsM** [killerall/advpl-vscode#181]
Estava usando o Vs Code normalmente, porém quando fui compilar novamente os fontes ocorreu o erro Invalid Compile Key - Cannot overwrite TOTVS programs

**Comment by killerall** [comment]
A sua chave de compilação está expirada, basta gerar outra e atualizar.

**Comment by aretw0** [comment]
Então, a chave que esta sendo gerada é sempre a mesma e continua dizendo que ela é inválida. :(

**Comment by aretw0** [comment]
Bem, sou novo nesse mundo do AdvPl mas pelo que eu entendi essa chave fica la no Totvs Dev Studio. E é realmente a mesma chave que aparece ao utilizar o comando da extensão.

No entanto fica dando *invalid key* na compilação de qualquer fonte pelo VsCode :(

Inclusive ao abrir a parte do Totvs Dev Studio que mostra essas informações: 
![image](https://user-images.githubusercontent.com/14055273/45047235-dd355e00-b04e-11e8-83bc-d909547fb236.png)
![image](https://user-images.githubusercontent.com/14055273/45047313-153ca100-b04f-11e8-8555-20ce9c3390bd.png)

Estou sem idéias do que fazer.

**Comment by izacsc** [comment]
@DudsM confira a data de validade de sua chave. Se estiver tudo OK, confira se não existe configuração de workspace para a pasta que você está que esteja sobrescrevendo a de usuário.

**Comment by killerall** [comment]
@aretw0 
Você precisa que te gerem uma chave dessas, não o TDS nem o vscode que geram ela, apenas validam.

**Comment by aretw0** [comment]
A minha pergunta é: por que o TDS compila de boas com a mesma chave que o vscode diz que é inválida???

**Comment by killerall** [comment]
O mais provavel é formato do data.
"advpl.authorization_generation": "20180822",
    "advpl.authorization_validation": "20181120",
    "advpl.authorization_permission": "1",
    "advpl.authorization_code": "01FSPL036RFRR74A1E7671210",

**Comment by killerall** [comment]
Vc tambem pode importar a chave.
https://github.com/killerall/advpl-vscode/wiki/Chave-de-compila%C3%A7%C3%A3o

**Comment by aretw0** [comment]
Na verdade ta tudo certo. (??)

Apesar do vscode avisar que a chave é inválida a compilação funciona! (??)

Apertei **F5**  de teimoso e vi que o código rodava! Alterei o código várias vezes usando alguns _connout_ alterando as mensagens e outras operações e
.... **FUNCIONA**......

![imagem](https://refnews.files.wordpress.com/2015/01/referee_mark_geiger_advantage1.jpg)
_Lance normal segue o jogo_
