### ISSUE TITLE
can't connect to server with this user

### ISSUE THREAD

**Issue by W1ll14nC4rl0s** [killerall/advpl-vscode#184]
estou com problemas ao tentar compilar pelo vscode já pesquisei sobre o problema mas não encontro soluçao
Este é meu AdvplDebug
[AdvplDebugBridge.log](https://github.com/killerall/advpl-vscode/files/1752793/AdvplDebugBridge.log)

**Comment by killerall** [comment]
No console do appserver não da nenhuma massagem?
O usuario willian é admin no protheus?

**Comment by W1ll14nC4rl0s** [comment]
Isso esse é o login que uso ja testei pelo TDS e por lá eu compilo

![image](https://user-images.githubusercontent.com/35581737/36611893-b8906938-18b3-11e8-9f21-419e0c863f7d.png)

**Comment by killerall** [comment]
Não vejo qual pode ser o problema, se é uma ambiente de teste, use o admin padrão para tentar conectar.

**Comment by W1ll14nC4rl0s** [comment]
o admin padrao nao utilizo senha e quando deixo o passwordCipher da erro

**Comment by W1ll14nC4rl0s** [comment]
Deu certo porem quando eu aperto f5 e tento executar o codigo não acontece nada :/

![image](https://user-images.githubusercontent.com/35581737/36612772-4b84c854-18b6-11e8-85aa-9c86b7083fc7.png)

**Comment by killerall** [comment]
Você criou o launch.json?
Ao dar f5 a primeira vez, vc precisa selelecionar ADVPL. Isso vai criar o launch.json.
Salve e feche esse arquivo, ai sim pode dar F5 e colocar a função.

**Comment by W1ll14nC4rl0s** [comment]
como eu crio esse launch.json?
