### ISSUE TITLE
smartclient\ is missing, empty or invalid.

### ISSUE THREAD

**Issue by MaicomRigo** [killerall/advpl-vscode#185]
Olá, 
Estou tentando efetuar a configuração no workspace, a principio parece estar tudo ok. Mas quando tento compilar da o seguinte erro:
D:\Protheus\ProtheusTrans\bin\smartclient\ is missing, empty or invalid
Alguem pode ajudar?

![image](https://user-images.githubusercontent.com/23719819/36678020-735c124e-1aee-11e8-824c-25bd2d6f0134.png)

**Comment by edusfc15** [comment]
@MaicomRigo começa pelo óbvio. O smartclient está mesmo nessa pasta?

**Comment by MaicomRigo** [comment]
Sim, segue abaixo:
![image](https://user-images.githubusercontent.com/23719819/36679033-03a217de-1af1-11e8-9f5b-fdc879528702.png)

**Comment by MaicomRigo** [comment]
@edusfc15 O Smartclient não precisa estar local na máquina para funcionar, correto?
Estou usando o VS Code na minha maquina e o smartclient fica em um servidor.

**Comment by edusfc15** [comment]
Tenho quase certeza que precisa estar no diretório local. Aqui no meu eu sempre usei com o smartclient na minha própria máquina.

**Comment by MaicomRigo** [comment]
@edusfc15 Se eu copiar a pasta smarclient, será que vai funcionar?

Outra questão, podes enviar o teu arquivo launch.json para eu poder comparar? Estou tentando configurar o debug tmb.

Obrigado.

**Comment by edusfc15** [comment]
> @edusfc15 Se eu copiar a pasta smarclient, será que vai funcionar?
Provavelmente.

O launch.json é criado quando você executa o debug.

`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Advpl Debug",
            "type": "advpl",
            "request": "launch",
            "args": [],
            "cwd": "${workspaceRoot}",
            "programRun": "${command:AskForProgramName}",
            "stopOnEntry": false,
            "enviromentInfo": "${command:GetEnvInfos}",
            "workspace": "${workspaceRoot}/"
        }
    ]
}`

**Comment by MaicomRigo** [comment]
Feito! Funcionou!
Iniciando compilação do fonte c:\Users\mrigo\Documents\FontesSVN\1_Grupo A\Branches\Interno\Branch_11_2017\ARTATESTE.PRW

Compile Start at Mon Feb 26 2018 12:50:06 GMT-0300 (Hora oficial do Brasil)

Compile Finish at Mon Feb 26 2018 12:50:16 GMT-0300 (Hora oficial do Brasil) Elapsed  (10.407 segs.)

Maaaaaaaaaaaaaaass...

Fui lá no repositório pra ver se alterou, mas sem sucesso. Se tem alguem conectado ele retorna que não conseguiu compilar ou ele só informa a msg "Compile Finish"?

**Comment by edusfc15** [comment]
@MaicomRigo não funcionou a compilação.

Tem que aparecer a mensagem: "Compilação OK"

**Comment by MaicomRigo** [comment]
@edusfc15 Ah, certo!

A principio está funcionando tudo certinho....
Muito obrigado pela ajuda, Eduardo!

**Comment by MaicomRigo** [comment]
@edusfc15 
Eduardo, 
Apenas para te sinalizar, consegui abrir o smartclient pelo servidor!!! 👍 
Segue o caminho que utilizei como teste, caso queira como fazer tmb!

\\\\Servidor\\d$\\Protheus\\ProtheusTrans\\bin\\smartclient\\

**Comment by edusfc15** [comment]
Boa @MaicomRigo! 

Por nada!
