### ISSUE TITLE
Debug com problema na Tecla F10

### ISSUE THREAD

**Issue by VictorF19** [killerall/advpl-vscode#192]
Quando o debug está com a chave "advpl.debug_multiThread": true, ao utilizar a tecla F10 o vscode não respeita as linhas e avança direto para o ponto de parada seguinte. Realizei um teste e constatei que desabilitando a chave de debug multithread aparentemente o problema não ocorre mais. Estou abrindo a issue pois não sei ao certo se é um bug ou o comportamento esperado quando essa chave estiver habilitada.

**Comment by killerall** [comment]
O Problema está na forma que o binario faz o debug.
O que deve estar ocorrendo é que tem outra thread rodando.
Faça o seguinte teste;
No primeira vez que parar, no console rode um ThreadId(), vai te retornar a thread atual.
de f10, e quando ele parar rode novamente, você tera outra thread provavelmente.

**Comment by VictorF19** [comment]
Bom dia, realmente, o problema é que  eu estava debugando sem estar em multi-thread e com essa chave habilitada. Agora o comportamento está normal! :) Muito obrigado.

**Comment by viniciusgati** [comment]
> E como desabilita esta multi-thread?

la embaixo no code ele mostra Multi Thread: Yes/No
