### ISSUE TITLE
Problemas com Debug

### ISSUE THREAD

**Issue by VictorBassoon** [killerall/advpl-vscode#193]
Olá Killerall,

Estou com problemas para debugar e executar as funções. Quando  eu uso CTRL+F5 , ele não executa.

Obs.: Esta compilando normalmente.

**Comment by afucher** [comment]
@VictorBassoon ele apresenta alguma mensagem no console do appserver? Ou alguma mensagem no output da extensão dentro vscode?

**Comment by VictorBassoon** [comment]
@afucher  não apresenta nada , nem no appserver, nem no vscode

**Comment by afucher** [comment]
coloque a configuração `advpl.logger` como verdadeiro e veja o arquivo de log gerado

**Comment by VictorBassoon** [comment]
Não consegui achar esse arquivo de log, ele gera em algum diretorio especifico

**Comment by killerall** [comment]
@VictorBassoon Ele fica no temp do seu usuario.
no windows explorer digite %TEMP% que vai abrir a pasta.
O arquivo cha AdvplDebugBridge.log

Veja se o seu caminho do smartclient esta configurado para o diretorio correto, ele sempre termina com \.
Por exemplo:

C:\\totvs12\\smartclient\\

**Comment by VictorBassoon** [comment]
Thread[1] - 20/04/2018 21:05:02: Start.
Thread[1] - 20/04/2018 21:05:02: {"selectedEnvironment":"environment","workspaceFolders":"","environments":[{"smartClientPath":"H:\\Totvs\\Ambientes\\P12\\Padrao\\Protheus\\bin\\smartclient\\","environment":"environment","serverVersion":"131227A","includeList":"H:\\Totvs\\Ambientes\\P12\\Padrao\\Protheus\\include\\","server":"localhost","port":"1234","user":"admin","passwordCipher":"cGhJc3pqUGIwZEpmQlRpbkdSd3diU1YyR0ZPeU1wMFd3TkFENG5ZNEM1T1kzeGR3ODY0QjJ5S2dzVCtMcnV5NFBaVHNFK2tMUHRxVmxVMmNTRXJheDBSYVMycDdSY29XRnpxU0pmeVZvS3luLzU2alhRS094MTZHbFhmNkh5ZzU"}],"startProgram":"SIGAMDI","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|prg|apw|aph|tres|png|bmp|res|apl)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":false,"debug_showTables":true,"debug_showPrivates":true,"debug_showPublic":true,"debug_showStatics":true,"compile_force_recompile":false,"logger":true,"compile_threads":4}.
Thread[1] - 20/04/2018 21:05:02: Starting MultiThread Compiler with 4 threads..
Thread[1] - 20/04/2018 21:05:08: {"msgs":[{"Key":"NOSOURCE","Value":[{"Line":1,"Column":0,"Type":0,"Message":"Can't connect to server with this user:admin"}]}]}.
Thread[1] - 20/04/2018 21:05:08: End.
Thread[1] - 20/04/2018 21:07:01: Start.
Thread[1] - 20/04/2018 21:07:01: {"selectedEnvironment":"environment","workspaceFolders":"","environments":[{"smartClientPath":"H:\\Totvs\\Ambientes\\P12\\Padrao\\Protheus\\bin\\smartclient\\","environment":"environment","serverVersion":"131227A","includeList":"H:\\Totvs\\Ambientes\\P12\\Padrao\\Protheus\\include\\","server":"localhost","port":"1234","user":"admin","passwordCipher":"UzViaGE0WFBrMkcrTUVnNFUrWUV0WDZuMzZkaXJmVmdET1JNcUlIL0FyOWdCRHJUSkgrRGFiUWNWU1p5MWJIdnRneFY3MkpKVkZLRFk2QnY1T3NMVUV5azdqejhFa1I5Ynh2MWtGcUJUeGFlWkZ0R1RQSnB6bXpWdXFhNlliUDY"}],"startProgram":"SIGAMDI","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|prg|apw|aph|tres|png|bmp|res|apl)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":false,"debug_showTables":true,"debug_showPrivates":true,"debug_showPublic":true,"debug_showStatics":true,"compile_force_recompile":false,"logger":true,"compile_threads":4}.
Thread[1] - 20/04/2018 21:07:01: Starting MultiThread Compiler with 4 threads..
Thread[1] - 20/04/2018 21:07:17: {"msgs":[]}.
Thread[1] - 20/04/2018 21:07:17: End.
