### ISSUE TITLE
[localization] Localização para Espanhol

### ISSUE THREAD

**Issue by AleksSyntek** [killerall/advpl-vscode#197]
Boa noite @killerall, gostaría de començar com a traducão para o _espanhol_, mais vc conhece si álguem tambén esta fazendo isso? Gostaria do unir esforços mais si no houver pessoal fazendo a tradução, eu posso iniciar a tradução dos arquivos *.json* é apos fazer um PR para sua revisão.

Atencionsamente.

**Comment by afucher** [comment]
@AleksSyntek ninguém está fazendo, pode fazer :)

**Comment by AleksSyntek** [comment]
Bom día @afucher é @killerall já fiz a tradução do arquivos, adjunto é o arquivo .zip e tambén un exemplo do tela com localização:
[pacote-espanhol.zip](https://github.com/killerall/advpl-vscode/files/2042762/pacote-espanhol.zip)

Sin localização
![imagen](https://user-images.githubusercontent.com/30332762/40587775-36e5631c-61aa-11e8-84d6-27036a3a00c3.png)

Com localização espanhol
![imagen](https://user-images.githubusercontent.com/30332762/40587735-7cda21ec-61a9-11e8-8a4d-21f1f66848d8.png)

Podem fazer a revisão é mudanzas necesárias no arquivos de ser necessário o para compartilhar com outros desenvolvedores que quieran fazer correções. Slds.

**Comment by afucher** [comment]
@alekssyntek o ideal era se pudesse fazer um pulo request com as alterações.. Consegue fazer isso? Assim analisamos é se estiver tudo ok, já incorporamos as alterações.

**Comment by AleksSyntek** [comment]
Sim @afucher !, vou a generar um PR então para isso. Hoje na noite tento criar o pulo mais si tenho algum erro le aviso.
