### ISSUE TITLE
Avaliação de Array no Debug não retorna valor algum.

### ISSUE THREAD

**Issue by killerall** [killerall/advpl-vscode#20]
Ao se olhar arrays, tanto no variable quanto no watch, o Debug não é capaz de mostrar os valores.

**Comment by cmgalves** [comment]
bom dia

estou tendo este problema...

muito estranho, não estou conseguindo contornar.

**Comment by saldanha85** [comment]
Estou com esse mesmo problema. No Watch não exibe os valores do array, nem no debug console. 
![debug](https://user-images.githubusercontent.com/48651289/96722651-fd861b00-1383-11eb-8bdd-3368d83ceb73.JPG)

**Comment by alexandrelima61** [comment]
Fala pessoal!

Eu estava com o mesmo problema, então voltei uma versão da extensão (TOTVS Developer Studio for VSCode (AdvPL, TLPP e 4GL))
Estou utilizando por enquanto a versão 1.1.0
Espero que tenha ajudado.
Abraço.

**Comment by saldanha85** [comment]
> Fala pessoal!
> 
> Eu estava com o mesmo problema, então voltei uma versão da extensão (TOTVS Developer Studio for VSCode (AdvPL, TLPP e 4GL))
> Estou utilizando por enquanto a versão 1.1.0
> Espero que tenha ajudado.
> Abraço.

Na verdade a versão mais atual é a 1.1.0, retornei para 1.0.6 e aí sim funcionou.... mas valeu a dica de voltar a versão.

**Comment by alexandrelima61** [comment]
> > Fala pessoal!
> > Eu estava com o mesmo problema, então voltei uma versão da extensão (TOTVS Developer Studio for VSCode (AdvPL, TLPP e 4GL))
> > Estou utilizando por enquanto a versão 1.1.0
> > Espero que tenha ajudado.
> > Abraço.
> 
> Na verdade a versão mais atual é a 1.1.0, retornei para 1.0.6 e aí sim funcionou.... mas valeu a dica de voltar a versão.

Desculpe a confusão, esta versão 1.1.0 e a versão que esta com o problema.
Eu voltei para a versão 1.0.6

Abraço.

**Comment by cmgalves** [comment]
Oi boa noite.

Voltei a versão e funcionou.

Em qua, 21 de out de 2020 15:49, alexandrelima61 <notifications@github.com>
escreveu:
