### ISSUE TITLE
Criando arquivos erx_prw e ppx_prw na compilação, mas não apaga.

### ISSUE THREAD

**Issue by jcstorino** [killerall/advpl-vscode#203]
Bom dia..
Os arquivos de controle de compilação erx e ppx não estão sendo apagados após a compilação com sucesso, existe alguma configuração que precisa ser feita para isso ?
Grato.

**Comment by killerall** [comment]
Bom dia,
Qual o sistema operacional?

**Comment by jcstorino** [comment]
Bom dia.. desculpe... MAC OSX... High Sierra..

**Comment by killerall** [comment]
Realmente esta deixando, vlw por avisar.
