### ISSUE TITLE
Erro no debug

### ISSUE THREAD

**Issue by webrsilva** [killerall/advpl-vscode#205]
Olá, 
Primeiramente agradecer ao desenvolvedor que customizou a ferramenta para ADVPL, está de parabéns e muito obrigado pelo a iniciativa.
Quanto ao meu problema. Mudaram meu perfil de usuário do Windows em minha máquina aqui na empresa e depois disso meu VS passou a dar o erro abaixo na hora de debugar, alguém tem ideia do que pode ser?
![image](https://user-images.githubusercontent.com/18246778/40329700-c565a72a-5d20-11e8-94eb-5233428a5869.png)
O erro só acontece no momento que clico em debugar. Para execução normal ele funciona perfeitamente e também está compilando os fontes sem problemas. Somente na hora de debugar é que acontece.... Já deletei meu arquivo launch.json, o VS recriou o arquivo mas não solucionou o meu problema. Desde já muito obrigado.

**Comment by killerall** [comment]
Ola,
no setting coloca advpl.logger ,'true'.
No temp da sua maquina vai gerar um arquivo de log, AdvplDebugBridge.log, veja se gera esse arquivo.

**Comment by webrsilva** [comment]
Realizei a configuração e executei. O log ficou em branco quando executei o debug, logo depois para teste, compilei um fonte qualquer aqui no meu projeto e ai sim escreveu o log abaixo:

Thread[1] - 22/05/2018 09:50:41: Start.
Thread[1] - 22/05/2018 09:50:41: {"selectedEnvironment":"con_hmg_weberson","workspaceFolders":"c:\\sistemas\\Microsiga;c:\\TDS113\\Workspace\\jameftransportes\\web_testes;p:\\Patch;c:\\TDS113\\Workspace\\jameftransportes\\imagens;","environments":[{"smartClientPath":"C:\\win_hmg","name":"con_hmg_weberson","environment":"weberson","includeList":"\\\\Totp05.adm.jamef\\totvs\\protheus\\includes\\","server":"hmg-totmaster.srv.jamef","port":"1237","user":"bh35185","passwordCipher":"eXdsRDJMVjhrWjhzUWRWMG85ZVZHMVAyWXZOUnFQeGllU0RhMUpGVEdoUHREamcwNGJVM3JLWitySVYyTlR6bEd1bHdYYTc4MVExaURmbnlpc2I3SEY0YWZTQkJ6WVNtT0I1NkU4ZGRJRFE0SzV1OW0zejNhd281VGlVQW5PZng="},{"smartClientPath":"C:\\win_hmg","name":"cfg_hmg_weberson","environment":"weberson","includeList":"\\\\Totp05.adm.jamef\\totvs\\protheus\\includes\\","server":"hmg-totmaster.srv.jamef","port":"2237","user":"bh35185","passwordCipher":"eXdsRDJMVjhrWjhzUWRWMG85ZVZHMVAyWXZOUnFQeGllU0RhMUpGVEdoUHREamcwNGJVM3JLWitySVYyTlR6bEd1bHdYYTc4MVExaURmbnlpc2I3SEY0YWZTQkJ6WVNtT0I1NkU4ZGRJRFE0SzV1OW0zejNhd281VGlVQW5PZng="},{"smartClientPath":"C:\\win_hmg","name":"con_hmg_ferreti","environment":"ferreti","includeList":"\\\\Totp05.adm.jamef\\totvs\\protheus\\includes\\","server":"hmg-totmaster.srv.jamef","port":"1237","user":"bh35185","passwordCipher":"eXdsRDJMVjhrWjhzUWRWMG85ZVZHMVAyWXZOUnFQeGllU0RhMUpGVEdoUHREamcwNGJVM3JLWitySVYyTlR6bEd1bHdYYTc4MVExaURmbnlpc2I3SEY0YWZTQkJ6WVNtT0I1NkU4ZGRJRFE0SzV1OW0zejNhd281VGlVQW5PZng="},{"smartClientPath":"C:\\win_hmg","name":"rest_hmg","environment":"rest","includeList":"\\\\Totp05.adm.jamef\\totvs\\protheus\\includes\\","server":"hmg-totmaster.srv.jamef","port":"1060","user":"bh35185","passwordCipher":"eXdsRDJMVjhrWjhzUWRWMG85ZVZHMVAyWXZOUnFQeGllU0RhMUpGVEdoUHREamcwNGJVM3JLWitySVYyTlR6bEd1bHdYYTc4MVExaURmbnlpc2I3SEY0YWZTQkJ6WVNtT0I1NkU4ZGRJRFE0SzV1OW0zejNhd281VGlVQW5PZng="},{"smartClientPath":"C:\\win_hmg","name":"ws_hmg","environment":"hmg","includeList":"\\\\Totp05.adm.jamef\\totvs\\protheus\\includes\\","server":"hmg-totmaster.srv.jamef","port":"1239","user":"bh35185","passwordCipher":"eXdsRDJMVjhrWjhzUWRWMG85ZVZHMVAyWXZOUnFQeGllU0RhMUpGVEdoUHREamcwNGJVM3JLWitySVYyTlR6bEd1bHdYYTc4MVExaURmbnlpc2I3SEY0YWZTQkJ6WVNtT0I1NkU4ZGRJRFE0SzV1OW0zejNhd281VGlVQW5PZng="},{"smartClientPath":"C:\\win_sig","name":"sig_vld","environment":"vld","includeList":"\\\\Totp05.adm.jamef\\totvs\\protheus\\includes\\","server":"totmaster.dtc.jamef","port":"1237","user":"bh35185","passwordCipher":"eXdsRDJMVjhrWjhzUWRWMG85ZVZHMVAyWXZOUnFQeGllU0RhMUpGVEdoUHREamcwNGJVM3JLWitySVYyTlR6bEd1bHdYYTc4MVExaURmbnlpc2I3SEY0YWZTQkJ6WVNtT0I1NkU4ZGRJRFE0SzV1OW0zejNhd281VGlVQW5PZng="},{"smartClientPath":"C:\\win_sig","name":"sig_vld1","environment":"vld1","includeList":"\\\\Totp05.adm.jamef\\totvs\\protheus\\includes\\","server":"totmaster.dtc.jamef","port":"1237","user":"bh35185","passwordCipher":"eXdsRDJMVjhrWjhzUWRWMG85ZVZHMVAyWXZOUnFQeGllU0RhMUpGVEdoUHREamcwNGJVM3JLWitySVYyTlR6bEd1bHdYYTc4MVExaURmbnlpc2I3SEY0YWZTQkJ6WVNtT0I1NkU4ZGRJRFE0SzV1OW0zejNhd281VGlVQW5PZng="},{"smartClientPath":"C:\\win_d-1","name":"D-1_S01","environment":"vld1","includeList":"\\\\Totp05.adm.jamef\\totvs\\protheus\\includes\\","server":"s01-totmaster.srv.jamef","port":"1237","user":"bh35185","passwordCipher":"eXdsRDJMVjhrWjhzUWRWMG85ZVZHMVAyWXZOUnFQeGllU0RhMUpGVEdoUHREamcwNGJVM3JLWitySVYyTlR6bEd1bHdYYTc4MVExaURmbnlpc2I3SEY0YWZTQkJ6WVNtT0I1NkU4ZGRJRFE0SzV1OW0zejNhd281VGlVQW5PZng="},{"smartClientPath":"C:\\win_sig","name":"sig_weberson","environment":"weberson","includeList":"\\\\Totp05.adm.jamef\\totvs\\protheus\\includes\\","server":"totmaster.dtc.jamef","port":"1237","user":"bh35185","passwordCipher":"eXdsRDJMVjhrWjhzUWRWMG85ZVZHMVAyWXZOUnFQeGllU0RhMUpGVEdoUHREamcwNGJVM3JLWitySVYyTlR6bEd1bHdYYTc4MVExaURmbnlpc2I3SEY0YWZTQkJ6WVNtT0I1NkU4ZGRJRFE0SzV1OW0zejNhd281VGlVQW5PZng="},{"smartClientPath":"C:\\win_sig","name":"sig_compila","environment":"compila","includeList":"\\\\Totp05.adm.jamef\\totvs\\protheus\\includes\\","server":"totmaster.dtc.jamef","port":"1231","user":"bh35185","passwordCipher":"eXdsRDJMVjhrWjhzUWRWMG85ZVZHMVAyWXZOUnFQeGllU0RhMUpGVEdoUHREamcwNGJVM3JLWitySVYyTlR6bEd1bHdYYTc4MVExaURmbnlpc2I3SEY0YWZTQkJ6WVNtT0I1NkU4ZGRJRFE0SzV1OW0zejNhd281VGlVQW5PZng="}],"startProgram":"SIGATMS","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|prg|apw|aph|tres|png|bmp|res)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":false,"logger":true,"compile_threads":4,"alpha_compile":false}.
Thread[1] - 22/05/2018 09:50:41: Starting MultiThread Compiler with 4 threads..
Thread[1] - 22/05/2018 09:50:46: {"msgs":[{"Key":"c:/TDS113/Workspace/jameftransportes/web_testes/WTESTE.prw","Value":[{"Line":398,"Column":0,"Type":1,"Message":"WTESTE.PRW(398) warning W0004 For variable is not Local"},{"Line":152,"Column":0,"Type":1,"Message":"WTESTE.PRW(152) warning W0010 Static Function FCERTIFICADO never called"},{"Line":496,"Column":0,"Type":1,"Message":"WTESTE.PRW(496) warning W0010 Static Function FREQUEST never called"},{"Line":564,"Column":0,"Type":1,"Message":"WTESTE.PRW(564) warning W0010 Static Function FSQLVIAG never called"},{"Line":541,"Column":0,"Type":1,"Message":"WTESTE.PRW(541) warning W0010 Static Function LOADWSDL never called"},{"Line":604,"Column":0,"Type":1,"Message":"WTESTE.PRW(604) warning W0010 Static Function FMJAMEF never called"},{"Line":359,"Column":0,"Type":1,"Message":"WTESTE.PRW(359) warning W0003 Local variable CFILANT never used"},{"Line":466,"Column":0,"Type":1,"Message":"WTESTE.PRW(466) warning W0003 Local variable ESPECIE never used"},{"Line":614,"Column":0,"Type":1,"Message":"WTESTE.PRW(614) warning W0003 Local variable NTIMEOUT never used"}]}]}.
Thread[1] - 22/05/2018 09:50:46: End.

Outro usuário aqui da empresa que também está utilizando a ferramenta está com o mesmo problema, mesmo erro.

**Comment by killerall** [comment]
Pelo o que você relata, parece que o window esta fechando o executavel do debug apos alguns segundos(por isso vc consegue compilar).
Veja com o Admin da Rede se não pode colocar o AdvplDebugBridge.exe como exceção da regra dele.

**Comment by killerall** [comment]
@webrsilva 
Qual o sistema operacional?

**Comment by webrsilva** [comment]
Boa tarde. Sistema operacional é windows 7. Estou em contato com o pessoal do suporte para ver se tem algum bloqueio...

**Comment by webrsilva** [comment]
Me colocaram como administrador da rede e não consegui debugar... Vou desinstalar e testar pra ver se volta...

**Comment by killerall** [comment]
Quando vc coloca para debugar, no appserver da alguma mensagem?

**Comment by webrsilva** [comment]
No console.log do server é escrito a mesma mensagem da imagem. A única diferença é que escreve um caminho de um arquivo no server:

> [FATAL][SERVER] [Thread 26823] [THROW] Invalid ReadMSChar at file /home/bamboo/xml-data/build-dir/TP11-BUILD13V2RCAPPSRV-TEC11LIN32RPO32/advtec9_tt11/lib_base/memstream.hpp line 841

**Comment by izacsc** [comment]
Por acaso vc está em uma WorkSpace em vez de uma pasta? Eu já tive esse problema quando estava em um workspace. Tente colocar diretamente numa pasta.

**Comment by killerall** [comment]
@izacsc Por favor, depois se consegui reproduzir me mostra como faz para corrigir isso, ou dar uma msg mais amigável.
