### ISSUE TITLE
Erro Debug/Compile-MacOS

### ISSUE THREAD

**Issue by Carraro-BH** [killerall/advpl-vscode#206]
Bom dia!
Após a ultima atualização (Alpha Linux/Mac 0.10.2) não foi mais possível executar, debugar ou compilar no ambiente MacOS (10.13.4).
Ao tentar executar/debugar o VS apresenta a seguinte mensagem: **"Debug adapter process has terminated unexpectedly"**
Ao tentar compilar a mensagem apresentada é: **Erro no NOME_PROGRAMA.PRW equest ignored -- RMS_DBGCOMPILE -- Build not started.**
Já refiz a Workspace, reinstalei o VS e a extensão, excluí o launch.json mas o problema persiste.
Alguma luz dos colegas?
Obrigado!

**Comment by Carraro-BH** [comment]
Killer, obrigado pela resposta!
Sim, consigo gerar o cipher normalmente e após diversas tentativas já consigo compilar após excluir absolutamente tudo do user settings e recria-lo), porém nem o erro do debug/execução continua:
"Debug adapter process has terminated unexpectedly"
A barra de status do VSCODE pisca como se fosse executar e em seguida o erro é apresentado.
Verifiquei a questão de privilégios do novo app bridge e nele aparentemente está tudo normal.
A propósito, de fato no MacOs os arquivos de pre-processamento estão sendo criados e permanecem no projeto, conforme indicou um outro colega em outro tópico.
Se tiver mais alguma luz nos informe, vou tentando por aqui também e se tiver novidades eu aviso.

**Comment by killerall** [comment]
@Carraro-BH 
Coloca no seu setting a linha
"advpl.logger" : true
Deve gera o tmp do seu usario um log0.

**Comment by Carraro-BH** [comment]
Killer, o advpl.logger já está habilitado, porém como trata-se de MacOs não sei onde você definiu o salvamento do arquivo de log, pode me informar?
Sobre a mensagem no appserver, apenas:

**[INFO ][SERVER] [Thread 7580] [22/05/2018 14:13:44] Starting Debugger (carraro, MacBook-Pro-de-Carraro.local)**

**Comment by killerall** [comment]
No tmp do usuário mesmo. O nome do arquivo deve ser :
log_0.log

**Comment by killerall** [comment]
Na verdade a pasta sem o executável.
/Applications/smartclient.app/Contents/MacOS/

**Comment by Carraro-BH** [comment]
Killer, show de bola!
Era isso, pois o app não estava na pasta padrão de aplicativos e sim em uma pasta Totvs dentro desta.
Apenas para referencia aos usuarios MacOs, o smartclient.app deve ficar na pasta padrão /Applications/ (assim fica mais fácil para entenderem).
Muitíssimo obrigado pelo suporte!
Está entregando um belíssimo trabalho, parabéns! Se precisarem de um beta em ambiente MacOs podem contar comigo!

**Comment by killerall** [comment]
Obrigado você pelo apoio.
Vou ajustar para ele ler a propriedade certinha do smartClientPath.
Assim que resolver, fecho essa issue.

**Comment by joaov1tor** [comment]
Outra ponto que pode gerar o erro RMS_DBGCOMPILE e tentar compilar com RPO em uso, ele nao respeita a tag BuildKillUsers=1.

**Comment by rogeriojacome** [comment]
Alguém já pegou esse erro?

Bridge Return:
execve failed: Bad CPU type in executable {"msgs":[{"Key":"/Users/rogeriofreitas/OneDrive/GW/GWMS-BAM/Relatorios/F110FIL.PRW","Value":[{"Line":-1,"Column":-1,"Type":0,"Message":"Can't read appre return."}]}]}
SyntaxError: Unexpected token e in JSON at position 0
Compilation finished at Thu Apr 08 2021 01:41:54 GMT-0300 (Brasilia Standard Time) Elapsed (5.746 secs.)
