### ISSUE TITLE
[MacOS] Problema na Execução (sem depuração)

### ISSUE THREAD

**Issue by Carraro-BH** [killerall/advpl-vscode#214]
Srs, boa tarde!
Encontrei um pequeno problema e gostaria de saber se ocorre com os demais (em especial os que usam o MacOs). A extensão está funcionando a contento para praticamente tudo (compilação, debug...), porém a opção de "Executar sem Depuração" a mensagem "Debug Adapter process has terminated unexpectedly" é exibida e o Smartclient não é executado.
Estou com a versão 0.10.3 da extensão instalada e com o ajuste manual da localização do executável para a pasta BIN correta.
Algum relato/informação acerca deste problema?

**Comment by killerall** [comment]
Boa tarde,

Vou tentar reproduzir essa situacao a noite.

**Comment by FelipeMelo1** [comment]
Fala Fernando, tranquilo?!

Cara, eu estava usando só o debug e estava funcionando perfeitamente, quando precisei usar o lançamento do smartclient sem debug, deu esse mesmo problema aqui no Mac.

Conseguiu alguma novidade para correção deste problema?

Att

**Comment by killerall** [comment]
@FelipeMelo1  e @Carraro-BH 
Acabei de lancar a versao 0.10.4
Consegue ver se resolveu?

valeu

**Comment by Carraro-BH** [comment]
Fala Rodrigo, bom dia e otima semana!
Resolvido o problema, a chamada está funcional!
Muito obrigado pelo apoio!
Carraro

**Comment by rcarloslima** [comment]
Também estou com esse mesmo erro.

Conseguiu resolver?

**Comment by Evandroafv** [comment]
No meu caso, quando executo F5, o smartclient fica travado no dock do mac. Se eu uso Ctrl + F5, o smartclient abre normalmente. Tem alguma configuração a mais que preciso informar?  
Configuração atual:
"advpl.debug_multiThread": true,
"advpl.debug_ignoreSourceNotFound": true,
"advpl.debug_showTables": true,
 "advpl.debug_showPrivates": true,
 "advpl.debug_showPublic": true,
 "advpl.debug_showStatics": true,

**Comment by Carraro-BH** [comment]
Evandro, boa tarde!
Como está a chave smartClientPath da sua configuração? Atentou-se para o fato de ter que ser configurada para o app dentro do pacote?
Ex: "smartClientPath": "/Applications/Totvs/SmartClient/smartclient.app/Contents/MacOS/"

**Comment by killerall** [comment]
@Carraro-BH 
Boa tarde,
Não consegui reproduzir na VM mac que tenho aqui a msg que está dando.
@Evandroafv , verifique tmb se a extensao esta atualizada, a versao anterior tinha um problema parecido  com o que vocÊ esta relatando.

**Comment by Evandroafv** [comment]
@Carraro-BH , veja que está conforme vc mencionou.
<img width="661" alt="captura de tela 2018-06-18 as 17 08 04" src="https://user-images.githubusercontent.com/33877185/41569726-1026c350-733a-11e8-8e78-c957e02d7ed2.png">


@killerall , estou a última atualização.
<img width="622" alt="captura de tela 2018-06-18 as 17 07 53" src="https://user-images.githubusercontent.com/33877185/41569717-079f9de2-733a-11e8-9fb0-3909d20b30d1.png">

**Comment by killerall** [comment]
@Evandroafv 
Desabilite o multithread.
Habilite o advpl.logger : true
No temp do seu usuario deve ter criado um arquivo chamado log_0.log
Veja se deu alguma msg la.

**Comment by Evandroafv** [comment]
Desabilitei o multithread.
O advpl.logger já estava habilitado.
Não funcionou e não foi gerado o arquivo de log na minha pasta temp.

**Comment by killerall** [comment]
Você consegue compilar?

**Comment by Evandroafv** [comment]
Consigo compilar e executar com o control + F5. Só não consigo usando o F5 direto para debug.
Vi que está perdendo a comunicação no console do appserver, por isso fica travado o smart. Mas isso só acontece debugando no mac.

<img width="973" alt="captura de tela 2018-06-19 as 14 08 31" src="https://user-images.githubusercontent.com/33877185/41615861-6b695850-73ca-11e8-87f2-e1e5c3c99725.png">

**Comment by killerall** [comment]
@Evandroafv 
Você olhou que pasta de tmp, para procurar o log?
se você executar num terminal?
echo $TMPDIR
Ele vai mostrar o diretorio do tmp do seu usuario, o arquivo de log é criado la.

**Comment by Evandroafv** [comment]
[28-06-2018 11:13:30] - Start
[28-06-2018 11:13:35] - Debug Thread Start
[28-06-2018 11:13:35] - Starting Mono Thread Debug...
[28-06-2018 11:13:35] - Debug ID
[28-06-2018 11:13:35] - 1176
[28-06-2018 11:13:35] - Iniciando o SmartClient
[28-06-2018 11:13:35] - io_service SC run

**Comment by killerall** [comment]
só tem isso no arquivo?

**Comment by Evandroafv** [comment]
Somente essa mensagem está no arquivo. Nas configurações do debug, teria algo para ser inserido? Se tiver, me envie um exemplo.
