### ISSUE TITLE
Não informa corretamente linha com erro de sintaxe

### ISSUE THREAD

**Issue by jcstorino** [killerall/advpl-vscode#219]
Não sei se é só na plataforma MAC OS, mas tenho percebido que o compilador não informa corretamente a linha dos problemas detectáveis a nível de pré-compilação.
exemplo, o fonte abaixo tem um parênteses a menos propositalmente..

#INCLUDE "PROTHEUS.CH"

User Function Teste1
Local aIndice       := {}
aAdd( aIndice , {1,2,3,4,5} )
aSort( aIndice ,,, {|x,y| x<y})
For nI := 1 To 10
    MsgStop("Atenção, msg de erro",cValToChar(aIndice[nI])
Next nI
Return( Nil )

Ao compilar recebo a msg
![captura de tela 2018-05-30 as 13 48 54](https://user-images.githubusercontent.com/19559870/40734932-3cdbd3b0-6410-11e8-9982-16f42cea0a74.png)

que me informa que o problema é na linha 2, coluna 1, porém o problema é na linha 8 coluna 58 conforme mostra o compilador do TDS
![captura de tela 2018-05-30 as 14 01 31](https://user-images.githubusercontent.com/19559870/40735631-0935490e-6412-11e8-9c24-352d12499994.png)

Alguém mais observa este comportamento ?

**Comment by AleksSyntek** [comment]
Bom día @jcstorino , com a versão 0.10.3 (VSCode x32) no Win7 x64 não tenho divergéncia na linhas informadas como erro é o fonte do exemplo:

![imagen](https://user-images.githubusercontent.com/30332762/40793513-fbd0637c-64d2-11e8-843f-9f38e733815a.png)

Espero ajude para detectar possível raiz do problema.

Slds.

**Comment by killerall** [comment]
O Appre nao sao as mesmas versoes,
Vou ver se aonde esta o problema, mais se for no appre, não muito o que fazer no mac.
