### ISSUE TITLE
[MacOS] Erro Compilação 0.10.3

### ISSUE THREAD

**Issue by Carraro-BH** [killerall/advpl-vscode#223]
Bom dia senhores!
Estranhamente após a reinstalação da extensão voltei a ter problemas com a compilação dos fontes.
No Output do VS as mensagens são:

```
Compilação iniciada em Wed Jun 06 2018 08:45:26 GMT-0300 (-03)
SyntaxError: Unexpected token e in JSON at position 0
Compilação finalizada em Wed Jun 06 2018 08:45:36 GMT-0300 (-03) tempo consumido (10.299 segs.)
```
No Console do server a mensagem é:

```
[WARN  ] [SERVER] Request Ignored -- RMS_DBGENDBUILD -- Build not started.
```

Permaneço conseguindo depurar normalmente o ambiente, já tendo refeito o cipher e o launch.json.
Também já refiz a workspace e já copiei o AdvplDebugBridgeC para a pasta correta (bin/alpha/mac).

Há algo relacionado a este problema já catalogado e que possa auxiliar na resolução?

Muito agradecido!

**Comment by FelipeMelo1** [comment]
Bom dia Carraro, 

Você está conseguindo depurar normalmente? Aonde você baixou o AdvplDebugBridgeC? Pois depois que reinstalei a extensão, não consigo mais depurar.

E a compilação eu também não estou conseguindo devido ao mesmo problema que você.

Obrigado!

**Comment by Carraro-BH** [comment]
Bom dia Felipe!
Na verdade o AdvplDebugBridgeC já vem instalado na extensão, porém está colocado na pasta incorreta.
Você deve copia-lo da pasta 

> /Users/seu_usuario/.vscode/extensions/KillerAll.advpl-vscode-0.10.3/bin/alpha/mac/bin

para a pasta 
> /Users/seu_usuario/.vscode/extensions/KillerAll.advpl-vscode-0.10.3/bin/alpha/mac/

Com isso você deverá conseguir realizar a depuração sem maiores problemas.

Se eu puder ajudar em algo mais é só falar.

**Comment by FelipeMelo1** [comment]
Opa.

Eu estava lendo outros tópicos lá e fiz conforme você disse ai e funcionou.

Obrigado hein..

Att

**Comment by FelipeMelo1** [comment]
Deixa eu te perguntar uma coisa.

Quando da erro de compilação, ele não fala qual é a linha que está com problema mesmo?

Att

**Comment by Carraro-BH** [comment]
Bom dia!
Até o momento onde eu estava conseguindo compilar me parece que as linhas de erro indicadas estavam corretas (não tenho certeza absoluta disso). Tão logo consiga realizar novamente a compilação reportarei neste tópico e no tópico 219 indicado pelo @jcstorino como se comporta na minha instalação.
Att.

**Comment by FelipeMelo1** [comment]
Pessoal,

No meu caso aqui, na aba Output não aparece a linha, mas na aba Problems aparece. Isso já atende a minha necessidade aqui. Caso tenha alguma configuração para aparecer a linha no Output também, como acontece no TDS, por gentileza postem aqui ou então no tópico 219.

Att

**Comment by Carraro-BH** [comment]
Felipe, após os ajustes você conseguiu também compilar? Se sim, pode nos informar quais ajustes procedeu?

Obrigado!

**Comment by Carraro-BH** [comment]
Srs, interessante!
Fiz a reinstalação de tudo, absolutamente tudo, inclusive do VS, tendo recriado novamente a workspace, o launch.json e o settings.json e o problema da compilação foi resolvido.
Farei alguns novos testes tentando isolar o problema e se encontrar algo postarei aqui.
Abcs!

**Comment by FelipeMelo1** [comment]
Olá Carraro!

Eu fiz exatamente o que me indicou:

"Bom dia Felipe!
Na verdade o AdvplDebugBridgeC já vem instalado na extensão, porém está colocado na pasta incorreta.
Você deve copia-lo da pasta

/Users/seu_usuario/.vscode/extensions/KillerAll.advpl-vscode-0.10.3/bin/alpha/mac/bin
para a pasta

/Users/seu_usuario/.vscode/extensions/KillerAll.advpl-vscode-0.10.3/bin/alpha/mac/
Com isso você deverá conseguir realizar a depuração sem maiores problemas.

Se eu puder ajudar em algo mais é só falar."

Após colocar o arquivo AdvplDebugBridgeC no local correto, a compilação já foi realizada corretamente.

Alguém ai alterou os snippets do ADVPL.JSON? Se sim, podem compartilhar por gentileza? No padrão vem com apenas alguns snippets.

Att

**Comment by FelipeMelo1** [comment]
Fui tentar depurar agora e está dando a mensagem "Processo do adaptador de depuração foi finalizado inesperadamente".

Alguém sabe o que pode ser?

Att

**Comment by Carraro-BH** [comment]
Fala Felipe!
Veja se a tag smartclientpath está completa, pois deve ser informada até o conteúdo interno do pacote do smartclient.app, da seguinte forma:

> "smartClientPath": "/Applications/smartclient.app/Contents/MacOS/"

Perceba que a path aí em cima pode variar de acordo com onde você tem o smartclient.app.

Att.

**Comment by FelipeMelo1** [comment]
Boa!

Na outra versão acho que era diferente e não precisava colocar até o content e sim até onde está o Smartclient só.

Obrigado mais uma vez Eduardo!

Att

**Comment by Carraro-BH** [comment]
Fala Felipe! Que bom que deu certo!
Sobre a questão das linhas com erro de compilação indicadas pelo Julio, de fato no Output há a mensagem indicando o erro mas não a linha, e na Problems é apresentada a linha, porém parece estar sempre indicando a linha  "2".
A questão acima se resume apenas a erros de compilação, já que em warnings as linhas são apresentadas corretamente na aba Problems.
Pelo menos aqui pra mim está assim.
Att.

**Comment by FelipeMelo1** [comment]
Então Eduardo, aqui pra mim na aba Problems, está aparecendo corretamente a linha do erro. Tentei simular aqui alguns erros, mas nunca apontou o erro para a linha 2 conforme citado por vocês.

É algum erro especifico que aponta pra linha 2 ou todos?

Att

**Comment by jcstorino** [comment]
O meu continua apontando sempre a linha 2, independente do erro... estou tendo que compilar no TDS para conseguir encontrar alguns problemas...

**Comment by Carraro-BH** [comment]
Boa Julio! É Exatamente isso! Aparentemente o erro ocorre apenas com o fechamento indevido de estruturas, para os erros de sintaxe o problema não ocorre.

**Comment by killerall** [comment]
Eu acredito ja ter comentado em outra issue, o appre utilizado no Mac.
Estou tentando resolver isso, mais nao posso prometer que vou conseguir.

**Comment by killerall** [comment]
Corrigido no 0.10.4
