### ISSUE TITLE
Nome de arquivos com pontuação não entra em breakpoints em debug

### ISSUE THREAD

**Issue by IsraelPossoli** [killerall/advpl-vscode#224]
Se o nome do arquivo possui pontuação, ao entrar em modo Debug acaba não entrando nos breakpoints.

Para contornar o problema:
- Remover o fonte do repositório 
- Renomear o fonte tirando a pontuação
- Debugar
- Reverter o processo para manter o nome correto.

Nome de fonte exemplo: RTMS002_DACTE_3.0.PRW, renomeando para RTMS002_DACTE_3_0.PRW funciona normalmente.

**Comment by killerall** [comment]
Qual o sistema operacional?
Testei aqui no windows com o nome que passou, e parou normalmente.

**Comment by IsraelPossoli** [comment]
Windows 10, mas minha build é bem antiga: TOTVS - Build 7.00.131227A - Sep  8 2015 - 11:54:57

**Comment by killerall** [comment]
Algums binarios antigos tinham mesmo esse problema.
