### ISSUE TITLE
Erro no Fonte.prw equest ignored -- RMS_DBGCOMPILE -- Build not started. No MAC

### ISSUE THREAD

**Issue by iurysa** [killerall/advpl-vscode#232]
Olá venho trabalhando desde ontem com o MAC sem problemas na compilação derrepente começou aparecer esse erro RMS_DBGCOMPILE em toda compilação que eu tento, verifiquei ele em outra pergunta refiz o processo para gerar a senha e coloquei mas não funcionou segue meu arquivo de configuração já desinstalei e instalei de novo o plugin e nada.

{
    "editor.fontSize": 14,
    "files.encoding": "windows1252",
    "advpl.environments":[
    {
        "name": "pneumax",
        "smartClientPath":"/Applications/smartclient.app/Contents/MacOS/",
        "environment":"COMP",
        "includeList":"/Applications/smartclient.app/Contents/include/",
        "server":"192.168.0.220",
        "port":"1202",
        "user":"administrador",      "passwordCipher":"WOHqcQG4VGHkiOYsrR+sOkRrdnMtF5VVvwg2fgBf0TwM9MG903aD5cgt2565mJnzAAiNb6+FZblPguupc6rgqdQK="
    }
],
"advpl.selectedEnvironment": "pneumax",
"advpl.logger" : true,
"advpl.startProgram": "SIGAMDI",
"advpl.debug_ignoreSourceNotFound": true,
"advpl.debug_showPrivates": true,
"advpl.debug_showPublic": true,
"advpl.debug_showStatics": true,
"advpl.debug_showTables": true,
"files.trimTrailingWhitespace": true,
"workbench.iconTheme": "material-icon-theme"
}

**Comment by iurysa** [comment]
No servidor aparece 
[WARN ][SERVER] Request ignored -- RMS_DBGENDBUILD -- Build not started.

[WARN ][SERVER] Request ignored -- RMS_DBGCOMPILE -- Build not started.

[WARN ][SERVER] Request ignored -- RMS_DBGENDBUILD -- Build not started.

**Comment by iurysa** [comment]
Rapaz já tentei sim, mas verifiquei aqui o que era uma coisa que eu realmente não esperava, o HD do servidor ficou cheio então ele não conseguia compilar.

**Comment by joaov1tor** [comment]
Outro motivo que pode gerar este erro RMS_DBGCOMPILE e tentar compilar com o RPO em uso.
