### ISSUE TITLE
MAC OS Avisos aparecendo como erros

### ISSUE THREAD

**Issue by iurysa** [killerall/advpl-vscode#233]
Em alguns fontes quando a variável não é local tem apresentado mensagem de erro ao compilar em vez de aviso, o problema é que em alguns casos ele não mostra a linha de forma correta como segue no print, observa que tem varias linhas comentadas e a cada comentário ele da o erro na linha superior e não consigo compilar, fiz o teste e compilei normalmente pelo windows.
<img width="802" alt="captura de tela 2018-06-27 as 14 41 46" src="https://user-images.githubusercontent.com/40610660/41990487-ea74e6ce-7a18-11e8-8c91-e78e3cbdee7e.png">

**Comment by iurysa** [comment]
Verifiquei que o FOR realmente estava com uma variável sem ser local, porem a mensagem de erro fica na linha errada e gera um pouco de confusão.

**Comment by killerall** [comment]
O APpre do windows e do MAC são diferentes.
No seu erro acima acredito que seja o else o problema.
Em relação as linhas, o appsrv/appre é que mandam o erro e a linha, e de fato as vezes vem errado.

Você consegue postar um codigo para testar aqui.
