### ISSUE TITLE
[MAC OS] Defrag RPO apresenta mensagem de erro e não finaliza.

### ISSUE THREAD

**Issue by jcstorino** [killerall/advpl-vscode#238]
Bom dia.
Quando faço a chamada da função de Desfragmentação do RPO, as vezes recebo a mensagem abaixo, porém parece que o RPO é desfragmentado corretamente, pois seu tamanho reduz e a data é atualizada.
![image](https://user-images.githubusercontent.com/19559870/42225239-7204dfca-7eb2-11e8-8bd1-1e3086b49ab5.png)

Mas nem sempre acontece isso.. por vezes apenas mostra que a desfragmentação iniciou, mas só mostra uma mensagem de erro depois de algum tempo.. e o RPO não é desfragmentado nem sua data alterada. E depois não consigo mais rodar o Defrag.
![image](https://user-images.githubusercontent.com/19559870/42225685-8313e990-7eb3-11e8-9462-054ddce2d770.png)

Somente após insistir é que consigo a saída com a msg de erro que aparentemente faz a desfragmentação corretamente...
![image](https://user-images.githubusercontent.com/19559870/42225780-b6f80d0e-7eb3-11e8-8403-5ee8ca76c2d2.png)

Alguma suspeita ?

**Comment by killerall** [comment]
Boa noite.

Tava com erro mesmo.

Já corrigi, devo lancar uma versao essa semana, ja vai com essa correção.

Valeu.,
