### ISSUE TITLE
Lobo-Guara - Can't apply patch

### ISSUE THREAD

**Issue by vlopes11** [killerall/advpl-vscode#240]
We have some inconsistencies while generating and applying patches to lobo-guara.

If we:

1) Generate patch via VsCode
1.1) Try to apply via VsCode - Error
`{"Line":1,"Column":0,"Type":0,"Message":"Can't apply patch:Request ignored -- RMS_DBGAPPLYPATCH -- Build not started."}`
1.2) Try to apply via TDS - Ok

2) Generate patch via TDS
2.1) Try to apply via VsCode - Error
`{"Line":1,"Column":0,"Type":0,"Message":"Can't apply patch:Request ignored -- RMS_DBGAPPLYPATCH -- Build not started."}`
2.2) Try to apply via TDS - Ok

3) Generate patch via AtuSX Spool of compilation
3.1) Try to apply via VsCode - Ok
3.2) Try to apply via TDS - Ok

Binary version
```
* TOTVS - Build 7.00.170117A - Jun 28 2018 - 16:13:26
* Build: 64 bits
* SVN Revision: 19627
* Build Version: 17.3.0.3_RC20
```

Attached follows some files to support the analysis for the Bridge.

hexdiff.png - Hex diff between the two generated patches. There are differences, except for the main header beyond first block (FB/FC)

![hexdiff](https://user-images.githubusercontent.com/8730839/42707452-efbd78d6-86e2-11e8-9979-b59f3362f9a7.png)
```
0000 0000: FB 00 00 00 74 74 74 65  31 32 30 00 00 00 00 00  v...ttte 120.....
0000 0010: 00 00 00 00 00 00 00 00  00 41 50 4E 53 52 4D 30  ........ .APNSRM0
0000 0020: 34 31 38 00 00 00 00 00  00 00 00 00 00 00 00 00  418..... ........
0000 0030: 00 00 00 00 F9 4E 42 9E  0D 7A D8 C8 52 58 D6 64  ....
```

Source code for this file
```
#include 'protheus.ch'

User Function TEST()
Conout("==>TEST-1")
Return Nil
```

**Comment by killerall** [comment]
What's the latest version of the extension?
Try to update your binary as I could not reproduce.
The last version I tested was:
Build_17.3.0.3_RC31

**Comment by vlopes11** [comment]
The test was performed with the latest version of the extension (0.10.6).

I'll update the binaries to the target release candidate and I'll post the results here

**Comment by killerall** [comment]
Which OS?
