### ISSUE TITLE
Erro ao compilar com ServerVersion 170117A

### ISSUE THREAD

**Issue by DudsM** [killerall/advpl-vscode#241]
Quando tento compilar um fonte com o ServerVersion 170117A ocorre o erro 
"SyntaxError: Unexpected end of JSON input"

Segue advpl.logger:
Thread[1] - 17/07/2018 11:45:58: Starting MultiThread Compiler with 4 threads..
Thread[1] - 17/07/2018 11:45:58: System.Net.Sockets.SocketException (0x80004005): Uma conexão estabelecida foi anulada pelo software no computador host
   em System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   em advtec.lib_comm.AdvtecConnectionManager.Send(TMessage msg)
   em advtec.lib_comm.AdvtecConnectionManager.SendMessage(TSendMessage msg).

**Comment by killerall** [comment]
Qual versão do seu binario?
Acabei de testar aqui com o : 
17.3.0.3_RC23

E funcionou ok.

**Comment by DudsM** [comment]
Estou usando o 17.3.0.3_RC30 também..

**Comment by killerall** [comment]
Acabei de atualizar para a:
Build Version: 17.3.0.3_RC32
E compilou normal tambem.
Você gerou um novo cipher para esse server?
Tente atualizar o binario, gerar um novo cipher. E apague o arquivo.
state.bin
da sua pasta temp.
(Para ir para ela, basta abrir o endereço %TEMP%)

**Comment by DudsM** [comment]
Atualizei para a Build Version: 17.3.0.3_RC32 gerei nova Cipher pra esse server e apaguei o arquivo state.bin da Temp..

Porém ocorre o erro Thread[1] - 17/07/2018 16:30:01: {"msgs":[{"Key":"NOSOURCE","Value":[{"Line":1,"Column":0,"Type":0,"Message":"Can't connect to server with this user:Admin"}]}]}.

**Comment by killerall** [comment]
Bem ai o erro esta claro, não esta conseguindo validar a senha com o usuario Admin.
Antes de compilar você entrou nesse ambiente normalmente?
