### ISSUE TITLE
Procurar por fonte duplicado no workspace ao debugar

### ISSUE THREAD

**Issue by sandro-costa** [killerall/advpl-vscode#244]
Ao inserir um breakpoint em um fonte, o qual já possui também em outra pasta ou projeto, no mesmo workspace, o debug está abrindo o primeiro fonte que encontra, só que às vezes não é o fonte que está sendo trabalhado no momento.

No TDS, na pasta Source, em Configurações do Debug, tem um CheckBox chamado "Search for duplicate source files in the path",  e neste caso quando ocorre o evento citado, o TDS abre a relação do mesmo nome de fonte em várias pastas para poder escolher qual será utilizado para debugar.

Poderiam implementar essa melhoria no VS Code, seria muito bacana.

Eu utilizo o VS Code há alguns meses e estou muito satisfeito com a performance.

Valeu e obrigado à todos.

Sandro Costa

**Comment by killerall** [comment]
@sandro-costa 
Já existe uma issue com esse pedido.
https://github.com/killerall/advpl-vscode/issues/97

Esta na lista de coisas pra fazer.

Valeu.
