### ISSUE TITLE
Erro ao gerar Patch

### ISSUE THREAD

**Issue by samaronybarros** [killerall/advpl-vscode#245]
Olá, 

Estou recebendo o erro abaixo ao gerar patch. 

![7d717da7-2048-4858-80c1-97396d8d2b0c](https://user-images.githubusercontent.com/10220629/42972578-53b3127c-8b86-11e8-890a-1338b91bd2f3.jpg)

A questão é que o ttts120.ptm informa que estou gerando em espanhol. Não entendo já que meu RPO está em Português e o VS Code está em Inglês. Entrentanto, se eu procuro por tttp120.ptm no diretório temporário informado, o arquivo lá se encontra.

![5e36ce21-9970-41b1-9978-2b9a75a5b448](https://user-images.githubusercontent.com/10220629/42972577-53968774-8b86-11e8-8beb-351588ec4b05.jpg)

Utilizei no processo a [configuração do ambiente](https://github.com/killerall/advpl-vscode/wiki/Configura%C3%A7%C3%A3o) e a [configuração para trabalhar com patch](https://github.com/killerall/advpl-vscode/wiki/Trabalhando-com-Patchs).

**Comment by killerall** [comment]
Como esta configurado o seu RpoLanguage, no appsrv.ini?
Deve ser:
RpoLanguage=Portuguese

**Comment by samaronybarros** [comment]
Estava da seguinte forma:
RpoLanguage=por

Alterei como orientado
RpoLanguage=Portuguese

Entretanto a saída agora está como _undefined_

**Comment by samaronybarros** [comment]
Obrigado, 

Era somente isso mesmo

Estava como 
RpoLanguage=por

Resolveu apenas com a troca para
RpoLanguage=portuguese
