### ISSUE TITLE
Inconsistência no arquivo settings.json

### ISSUE THREAD

**Issue by dinochip** [killerall/advpl-vscode#249]
Após a atualização 1.24.1 e 1.25 do VSCode o arquivo de configuração exibe estrutura de propriedades advpl grifada com texto "Essa configuração não pode ser aplicada agora. Sera aplicada quando você abrir essa pasta diretamente." e não exibe ambientes para seleção, e não respeita o ambiente da propriedade advpl.selectedEnvironment existe algum ajuste necessário para que volte a funcionar?

**Comment by dinochip** [comment]
Faltou complementar que estou usando a configuração por Workspace por usuário esta funcionando normalmente

**Comment by killerall** [comment]
Nunca utilizei o vscode assim, vou testar por aqui.

**Comment by killerall** [comment]
Consegue fazer um passo a passo pra reproduzir?

Eu criei uma workspace nova, salvei, e adicionei dois diretórios. 
Funcionou normalmente.
