### ISSUE TITLE
Implement Language Server Support

### ISSUE THREAD

**Issue by afucher** [killerall/advpl-vscode#25]
As seguintes coisas deverão ser feitas para adicionar o suporte:  
- [x] Refatorar estrutura do projeto para separar pasta da extensão e server, exemplos: [jshint](https://github.com/Microsoft/vscode-jshint) e [eslint](https://github.com/Microsoft/vscode-eslint) - [commit](https://github.com/killerall/advpl-vscode/commit/7d9c3bd6590412a0ae35f079516e9e8079496363);
- [x] Implementação de gramática ADVPL (Antlr);
- [x] Implementação básica do Advpl Language Server;
- [x] Implementação do parser em C# - Em Javascript estava extremamente lento [advpl-parser](https://github.com/killerall/advpl-parser);
- [x] Implementação de parser de fonte para exibição de erros de gramática em tempo real;
- [x] Implementação de Symbols por arquivo no Advpl Language Server para:  
  - [ ] Funções
  - [ ] Classes
  - [ ] Métodos

Links:
[Language Server Protocol](https://github.com/Microsoft/language-server-protocol)
[Criando um Language Server](https://code.visualstudio.com/docs/extensions/example-language-server)

**Comment by izacsc** [comment]
E como podemos ajudar? :)

**Comment by afucher** [comment]
@izacsc por enquanto ainda não tem como, em breve devemos subir uma versão básica com a implementação da gramática e do server.
Acredito que em uma nova branch até estar 100%, aí acredito que será possível ajudar com a construção das lógicas para os Symbols.
Vou atualizar os links da descrição, o que pode já ajudar é ir lendo e vendo os exemplos para estar mais familiarizado quando liberarmos aqui :smile:

**Comment by izacsc** [comment]
Não sei se conhecem mas...

**Comment by killerall** [comment]
Esse porte é novo para TypeScript, o arthur chegou a usar o de javascript mais o parser do fonte fwbrowse leva 5 min em JS. 
Optamos por fazer em C#.
https://github.com/killerall/advpl-language-server
Que faz isso em segundos.
A estrutura está quase pronta para ser liberada LS. Porem ainda não consegui implementar nada "util" por falta de tempo no LS por isso não o liberei  ainda.

**Comment by killerall** [comment]
@afucher 
Eu andei estudando as outras implementações e não vi muito sentido em deixar o LS no mesmo repositorio, Por isso vou criar um repo novo, para o LS.
@izacsc Só para alinhar, nesse 1 ano, a performace do do antlrts melhorou muito, entao vamos fazer a implementacao em TypeScript, por ficar mais facil para o pessoal contribuir, e para distribuir.

**Comment by afucher** [comment]
@killerall ok! na época a implementação que tinha visto tinha organizado dessa maneira.
Mas do mesmo jeito serão duas extensões, e essa dependerá da outra.. correto?

**Comment by afucher** [comment]
@killerall se você olhar o primeiro item da lista do primeiro comentário dessa issue, vai ver de onde eu peguei as referências...

**Comment by izacsc** [comment]
Não sei se vocês já viram, mas tem uma extensão de Harbour que acredito que já tenha um LS. Eu vi pelo menos que já tinha uma parte de identificação de símbolos. Talvez seja útil https://marketplace.visualstudio.com/items?itemName=aperricone.harbour

**Comment by killerall** [comment]
@afucher 
Na verdade continua sendo 1 só extensão, o client vai ficar na extensao do advpl, e o Server não é uma extensão propriamente dita, é apenas um projeto nodejs.
Ai nao precisa quebrar toda a estrutura de diretorio atual.
Eu já tenho uma branch local que estou fazendo issso.

@izacsc 
Dei uma olha na extensão dele,
Ele faz o parser de maneira bem manual. Para os fontes de ADVPL ficaria bem lento. Mais valeu pela dica.

**Comment by afucher** [comment]
@killerall eu estava relembrando o que fiz, e continuava sendo uma só... Tem um script que instala o server na extensão do client. Mas ok, vou esperar subir sua branch local então..
Vou fechar essa issue já que temos um repo só para isso.

**Comment by killerall** [comment]
@afucher 
Blz,
Subi o que fiz, e criei um projeto no outro rpo:
https://github.com/advpl/advpl-language-server/projects/
A branch dele aqui no advpl-vscode é 
ts-language-server
