### ISSUE TITLE
Após atualizar o VS Code ontem, não consigo mais debugar.

### ISSUE THREAD

**Issue by joaoleao01** [killerall/advpl-vscode#250]
Boa tarde!

Aparece o erro ao pressionar F5 e digitar SIGAADV:
HandleRequestAsync timeout

Mais alguém reportou esse erro?

**Comment by killerall** [comment]
Boa tarde.
Você utiliza workspace ou pastas no vscode?
Eu particulamente nunca vi esse erro.
Na duvida, dentro da sua pasta .vscode, do diretorio que vc usa, apague o launch.json e recrie-o.

**Comment by joaoleao01** [comment]
Boa noite.


Eu uso pasta. Na versão 1.24.1 do vs code funcionava normal. Na versão 1.25.1 parou de funcionar.

Apaguei o arquivo launch.json, recriei e não resolveu.


Então resolvir criar a workspace e adicionar a pasta que tenho meus fontes. Ao tentar debugar agora aparece outro erro: command 'advpl.getDebugPath' not found


João Leão


________________________________
De: Rodrigo Antonio Godinho da Silva <notifications@github.com>
Enviado: quinta-feira, 26 de julho de 2018 20:59
Para: killerall/advpl-vscode
Cc: joaoleao01; Author
Assunto: Re: [killerall/advpl-vscode] Após atualizar o VS Code ontem, não consigo mais debugar. (#250)


Boa tarde.
Você utiliza workspace ou pastas no vscode?
Eu particulamente nunca vi esse erro.
Na duvida, dentro da sua pasta .vscode, do diretorio que vc usa, apague o launch.json e recrie-o.

**Comment by killerall** [comment]
Você usa no windows?
Nào consigo ter nem ideia o do porque isso ocorre.

Eu tentaria remover a extensão e proprio vscode, e reinstalar tudo novamente.

**Comment by joaoleao01** [comment]
Vou reinstalar tudo de novo.

Obrigado.


João Leão


________________________________
De: Rodrigo Antonio Godinho da Silva <notifications@github.com>
Enviado: sexta-feira, 27 de julho de 2018 00:04
Para: killerall/advpl-vscode
Cc: joaoleao01; Author
Assunto: Re: [killerall/advpl-vscode] Após atualizar o VS Code ontem, não consigo mais debugar. (#250)


Você usa no windows?
Nào consigo ter nem ideia o do porque isso ocorre.

Eu tentaria remover a extensão e proprio vscode, e reinstalar tudo novamente.

**Comment by mateus-erp** [comment]
Boa noite.

Estou sofrendo com o mesmo problema na versão 1.42, vocês teria em mente alguma solução?

**Comment by killerall** [comment]
Boa noite,

Não tenho nenhum relato disso.

Você esta utilizando qual versão da extensão?

Qual versão de binario do appserver?

**Comment by mateus-erp** [comment]
Bom dia.

Build AppServer: 7.00.170117A-20190628 - 64 bits
Totvs Developer Studio for VSCode - Versão 0.3.23

**Comment by mateus-erp** [comment]
Segue Launch,

{
	"version": "0.2.0",
	"configurations": [
		
		{
			"type": "totvs_language_debug",
			"request": "launch",
			"name": "Totvs Language Debug",
			"program": "${command:AskForProgramName}",
			"cwb": "${workspaceFolder}",
			"smartclientBin": "C:\\TOTVS12\\Protheus\\Protheus\\bin\\smartclient\\smartclient.exe",
			"isMultiSession": true,
			"enableTableSync": true,
			"programArguments": "undefined",
			"enableMultiThread": false,
			"enableProfile": false,
			"isAccessibilityMode": false,
			"doNotShowSplash": false,
			"language": "",
			"ignoreFiles": true
		}
	],
	"lastPrograms": [
		{
			"args": [],
			"label": "SIGAADV",
			"description": ""
		}
	],
	"lastProgramExecuted": "SIGAADV"
}

**Comment by AlencarGabriel** [comment]
> Segue Launch,
> 
> {
> "version": "0.2.0",
> "configurations": [
> 
> ```
> 	{
> 		"type": "totvs_language_debug",
> 		"request": "launch",
> 		"name": "Totvs Language Debug",
> 		"program": "${command:AskForProgramName}",
> 		"cwb": "${workspaceFolder}",
> 		"smartclientBin": "C:\\TOTVS12\\Protheus\\Protheus\\bin\\smartclient\\smartclient.exe",
> 		"isMultiSession": true,
> 		"enableTableSync": true,
> 		"programArguments": "undefined",
> 		"enableMultiThread": false,
> 		"enableProfile": false,
> 		"isAccessibilityMode": false,
> 		"doNotShowSplash": false,
> 		"language": "",
> 		"ignoreFiles": true
> 	}
> ],
> "lastPrograms": [
> 	{
> 		"args": [],
> 		"label": "SIGAADV",
> 		"description": ""
> 	}
> ],
> "lastProgramExecuted": "SIGAADV"
> ```
> 
> }

@mateus-erp , bom dia.

Com base nas suas configurações, você não está utilizando esta extensão, e sim a versão TDS for VsCode. https://github.com/totvs/tds-vscode
