### ISSUE TITLE
DEBUG arquivo incorreto

### ISSUE THREAD

**Issue by paulo-afill** [killerall/advpl-vscode#253]
Utilizo em meu workspace a ramificação de pastas padrão do SVN, sendo ela BRANCH, TAG e TRUNK. Quando vou debugar algum fonte, a ferramenta está utilizando o primeiro encontrado no workspace. No TDS tem uma opção na configuração do DEBUG que permite informar quais pastas farão parte do DEBUG, evitando este problema...

**Comment by killerall** [comment]
https://github.com/killerall/advpl-vscode/issues/97
