### ISSUE TITLE
Erro ao compilar folder no MacOS

### ISSUE THREAD

**Issue by FelipeMelo1** [killerall/advpl-vscode#254]
Bom dia pessoal!

Alguém já teve problema em compilar pastas? O erro acusado é o seguinte:

`SyntaxError: Unexpected token w in JSON at position 0`

Agradeço desde já!

Atenciosamente.

**Comment by killerall** [comment]
@FelipeMelo1 
Bom dia.
No temp do do seu mac, deve ter gerado um arquivo AdvplDebugBridgeC_0 ou 1.log
Veja se consegue achar esse arquivo e mande ele aqui.

[]s

**Comment by FelipeMelo1** [comment]
Procurei o arquivo e não encontrei no TEMP.

nas configurações está habilitado o Advil.logger.. ("advpl.logger": true,)

Att.

**Comment by killerall** [comment]
O path utilizando é o do temp do usuario, para ver esse dir, rode um
echo $TMPDIR.
no terminal
Em tese ele cria sempre o arquivo.

**Comment by FelipeMelo1** [comment]
Segue o arquivo gerado após a compilação da pasta e o erro que logou na aba Saída:

`SyntaxError: Unexpected token 
 in JSON at position 77
Compilação finalizada em Mon Aug 13 2018 11:10:08 GMT-0300 (-03) tempo consumido (12.529 segs.)`

[AdvplDebugBridgeC_0.log](https://github.com/killerall/advpl-vscode/files/2283243/AdvplDebugBridgeC_0.log)

**Comment by killerall** [comment]
O log veio meio que vazio.
Vou testar em casa, pois só tenho acesso a vm MAC la e vejo se consigo reproduzir.

**Comment by FelipeMelo1** [comment]
Maravilha, vou tentar obter mais alguma informação para te ajudar tbm.

Att

**Comment by killerall** [comment]
@FelipeMelo1 
na sua configuração, coloque a linha
"advpl.alpha_compile": true

Deve funcionar.

**Comment by FelipeMelo1** [comment]
Bom dia!

Adicionando a configuração, o problema foi resolvido ao compilar a pasta.

Obrigado!

**Comment by killerall** [comment]
De nada, vou deixar aberto, pois deveria funcionar sem isso.
Na proxima versao eu libero uma correção.

**Comment by killerall** [comment]
Tente colocar
"advpl.compile_force_recompile": true

**Comment by jcstorino** [comment]
Tenho o mesmo comportamento aqui… diz que compilou no console, mas não atualiza o repositório.

Tenho as duas tags informadas como true..

**Comment by rogeriojacome** [comment]
Alguém já pegou esse erro?

Bridge Return:
execve failed: Bad CPU type in executable {"msgs":[{"Key":"/Users/rogeriofreitas/OneDrive/GW/GWMS-BAM/Relatorios/F110FIL.PRW","Value":[{"Line":-1,"Column":-1,"Type":0,"Message":"Can't read appre return."}]}]}
SyntaxError: Unexpected token e in JSON at position 0
Compilation finished at Thu Apr 08 2021 01:41:54 GMT-0300 (Brasilia Standard Time) Elapsed (5.746 secs.)
