### ISSUE TITLE
APLICAR PATCH - Somente fontes mais atuais

### ISSUE THREAD

**Issue by EdnerGrechi** [killerall/advpl-vscode#255]
Olá KillerAll, parabéns a você e toda galera que está contribuindo para o uso da linguagem advpl PROTHEUS no VsCode. Foi uma ótima contribuição para os desenvolvedores.

Uso a pouco tempo mas já defini como minha plataforma padrão.

De todos os recursos que explorei senti falta da opção SOMENTE FONTES ATUALIZADOS quando vamos aplicar um patch. 

Essa opção existe? Caso não, seria de grande contribuição, assim não dependeríamos mais do TDS, Dev.

Abraço e bom trabalho.

**Comment by killerall** [comment]
@EdnerGrechi 
Obrigado.
Essa issue esta sendo tratada aqui.
https://github.com/killerall/advpl-vscode/issues/138
