### ISSUE TITLE
Exibir Tabelas

### ISSUE THREAD

**Issue by cmregazzo** [killerall/advpl-vscode#257]
Bom dia,

Primeiramente parabéns pelo projeto. Excelente ferramenta para programar em AdvPL.

Fiz a configuração para exibição de tabelas ("advpl.debug_showTables": true) no Debug, porém no meu VsCode não esta aparecendo a "Visão" com as Tabelas.

Além da configuração acima, preciso setar mais alguma coisa no meu ambiente, para exibir as tabelas?

Muito obrigado.
![tabelas vscode advpl](https://user-images.githubusercontent.com/6932442/44096450-a8d0f1fe-9fb1-11e8-83ff-d80753685152.png)

**Comment by killerall** [comment]
@cmregazzo  Obrigado.
A configuração que você colocou deve ser posta fora do ambiente, antes dos "advpl.enviroments"

**Comment by jcstorino** [comment]
Perdoe minha intromissão… mas as tabelas que vc quer ver não estariam como sub-pastas da pasta variáveis…

Pelo menos pra min aparece assim…

**Comment by cmregazzo** [comment]
Bom dia @jcstorino ,

Matou a charada... 

Eu não havia aberto as variaveis, para mim, iria aparecer uma outra opção chamado "variáveis".

Muito obrigado @jcstorino  e @killerall 

Abs,

Obrigado.

**Comment by cmregazzo** [comment]
Bom dia,

Alias seria mais interessante que a as Tabelas estivessem fora das variáveis, não seria?

Muito obrigado.

**Comment by killerall** [comment]
@cmregazzo 
Isso é uma definição do vscode, ate onde eu vi, não é possível adicionar algo no nivel anterior no debug.
