### ISSUE TITLE
Configuração de Include Mac OS

### ISSUE THREAD

**Issue by fabiocerris** [killerall/advpl-vscode#261]
Não estou conseguindo compilar no VS CODE - ADVPL, exibindo a mensagem abaixo.
"Erro no MVEMP046.PRW Error C2090  File not found PRTOPDEF.CH".
não está reconhecendo as INCLUDES, mas acredito que está configurado corretamente:

{
    "editor.fontSize": 13,
    "files.encoding": "windows1252",
    "advpl.environments":[  
    {
    "name": "COMP",  
    "smartClientPath":"/Applications/smartclient.app/Contents/MacOS/",
    "environment":"COMP",
    "serverVersion": "131227A",
    "includeList":"/Users/fabiocerri/Documents/Totvs/INCLUDES/",
    "server":"200.216.110.250",
    "port":"9473",
    "user":"fabioc",
    "passwordCipher":"qwLkC4EzJ+ijpb6/QiPDv2HJwW1tefgXvmXNVQuykVA/P0RQ5dsOqElhetPLz3ibAARC7MHdfFtz52Rf5WxQJnfl=",
    "language": "PORTUGUESE",
    "rpoType": "TOP",
}
],
"advpl.selectedEnvironment": "COMP",
"advpl.startProgram": "SIGAMDI",
"git.ignoreMissingGitWarning": true,
"advpl.compileFolderRegex": ".*\\.(prw|prx|prg|apw|aph|tres|png|bmp|res|apl|tlpp)",

"advpl.debug_multiThread": false,
"advpl.debug_ignoreSourceNotFound": true,
"advpl.debug_showTables": true,
"advpl.debug_showPrivates": true,
"advpl.debug_showPublic": true,
"advpl.debug_showStatics": true,
"window.zoomLevel": 0,
"workbench.iconTheme": "material-icon-theme",
"explorer.confirmDelete": false,
"extensions.ignoreRecommendations": true,
"material-icon-theme.hidesExplorerArrows": false,
"material-icon-theme.folders.color": "#fdd216",
"explorer.confirmDragAndDrop": false,
}

Segue abaixo conteúdo arquivo LOG
[AdvplDebugBridgeC_0.log](https://github.com/killerall/advpl-vscode/files/2333734/AdvplDebugBridgeC_0.log)

**Comment by killerall** [comment]
Tenta tirar os espacos em branco no caminho do seu fonte.

**Comment by fabiocerris** [comment]
Fiz essa tentativa, mas tbm não resolveu.

**Comment by killerall** [comment]
@fabiocerris 
De uma olhada aqui:
https://apple.stackexchange.com/questions/22297/is-bash-in-osx-case-insensitive
Pode ser que o HD do seu mac, esta  configurado para ser case sensitive.

**Comment by fabiocerris** [comment]
Verifiquei, não está como case sensitiva, inclusive nas configurações copiei e colei diretorio.

Configuração do Disco:
Partition Type:           41504653-0000-11AA-AA11-00306543ECAC
File System Personality:  APFS
Type (Bundle):            apfs
Name (User Visible):      APFS
Owners:                   Enabled

**Comment by fabiocerris** [comment]
Completando, o erro que aparece ao compilar:

Compilação iniciada em Thu Aug 30 2018 08:26:35 GMT-0300 (-03)

Erro no MVEMP045.prw Error C2090  File not found PRTOPDEF.CH
Compilação finalizada com erros, verifique a aba problemas!
Compilação finalizada em Thu Aug 30 2018 08:26:39 GMT-0300 (-03) tempo consumido (3.456 segs.)

**Comment by killerall** [comment]
O seu diretorio de inlcude, esse ch está com case ?

**Comment by jcstorino** [comment]
@killerall @fabiocerris 
Olha só.. eu consegui reproduzir o problema aqui no meu mac, colocando o caminho dos includes de forma errada, mesmo não estando utilizando o include PRTOPDEF.CH a mensagem do erro só se refere a este  include. Confirme letra por letra o caminho informado, pois esse sim considera o case.

**Comment by fabiocerris** [comment]
Tentei tirar essa barra, verifiquei os caracteres, tá muito estranho... 
Tenho VM do windows e conseguir funcionar normalmente.
Segue os prints do diretorio e da configuração do includeList. 
<img width="705" alt="diretorio" src="https://user-images.githubusercontent.com/42818528/44913399-afc17b00-ad03-11e8-9d4a-4a7c0c875ca3.png">
<img width="1043" alt="includelist" src="https://user-images.githubusercontent.com/42818528/44913400-afc17b00-ad03-11e8-841b-6cf273cf319d.png">

**Comment by fabiocerris** [comment]
@killerall , o arquivo PRTOPDEF.CH, esta minúsculo, eu também renomeei e mesmo assim nada!

**Comment by killerall** [comment]
Que bom que resolveu. Obrigado
