### ISSUE TITLE
Problema com CTRL + F11

### ISSUE THREAD

**Issue by cmregazzo** [killerall/advpl-vscode#262]
Boa Tarde,

Estou tentando executar o SmartClient com o CTRL + F11, conforme a documentação, porém tal comando não está funcionado. 

Pressiono o comando de teclas CTRL + F11, e nada acontece.

Deve-se fazer alguma configuração "específica".

Obrigado.

**Comment by killerall** [comment]
Boa tarde,
Não precisa, qual SO você usa?

**Comment by cmregazzo** [comment]
Boa Tarde,

Estou usando no Windows 10 Pro.

Att.

**Comment by killerall** [comment]
Já viu o problema, você esta usando a tag name, para diferenciar os ambientes.
Na proxima versão já ajustei para ver o nome do ambiente e tag name.
Valeu.

**Comment by cmregazzo** [comment]
Boa Tarde.

Show!!! Muito obrigado.

Outra dúvida, quando é lançada uma nova versão da Extensão AdvPL do VsCode, a mesma é atualizada, utilizando o procedimento de atualização do VsCode?

Att,

**Comment by killerall** [comment]
Na verdade o vscode atualiza a extensão de forma automatica.
