### ISSUE TITLE
Aba Tabela de Dados

### ISSUE THREAD

**Issue by VictorF19** [killerall/advpl-vscode#263]
Boa tarde, é possível criar uma visualização semelhante à tabela de dados do TDS? Facilitaria muito a vida para debugar certas rotinas.

**Comment by killerall** [comment]
Não tenho certeza de qual visualização você esta se referindo no tds, mais você pode mostrar as tabelas no debug, adicionando a configuração abaixo:

"advpl.debug_showTables": true

**Comment by VictorF19** [comment]
Tenho essa chave habilitada, porém como faço pra visualizar as tabelas?

**Comment by killerall** [comment]
Vai estar no debug, na parte de Variables.
![image](https://user-images.githubusercontent.com/4764609/45097719-db74a480-b0f9-11e8-9464-54e45a445237.png)
