### ISSUE TITLE
Debug em REST

### ISSUE THREAD

**Issue by claudiodevops** [killerall/advpl-vscode#264]
Boa noite,

Não estou conseguindo debugar um WS REST pelo VSCODE, somente consigo debugar WS SOAP.
Habilitei a opção de debug multithread ("advpl.debug_multiThread": true), iniciei um debug e derrubei todas as threads para que as novas instâncias entrassem no meu debug, mas após invocar um método GET, o VSCODE não para no breakpoint.
Pelo TDS funciona normalmente após os procedimentos acima.

Consegue me ajudar?

Obrigado

**Comment by killerall** [comment]
Bom dia,
Não tem por que ser diferente. Você não está derrubando a thread de debug?
Desabilitar o onstart do rest, entrar debugando e iniciar um outro smartclient com a funcao:
HTTP_START

**Comment by claudiodevops** [comment]
Bom dia,

Na verdade o procedimento que eu havia passado esta invertido. Eu subia o serviço do WS, derrubava todas as threads, iniciava o debug e aguardava o onstart subir as threads novamente para garantir que as novas instâncias entrassem no debug. Fiz um teste agora com os procedimentos que você passou e mesmo assim não para no breakpoint.

**Comment by claudiodevops** [comment]
Identifiquei aqui que o problema estava ocorrendo porque estava usando um binário muito antigo de 2015, atualizei para um binário de 2018 e consegui debugar normalmente o REST no VSCODE!
