### ISSUE TITLE
[MAC OS] Parou de compilar...

### ISSUE THREAD

**Issue by jcstorino** [killerall/advpl-vscode#268]
Boa noite.. houve alguma atualização no debugger.c ou algum outra coisa, pois meu VSC simplesmente parou de compilar...

Se mando compilar pelo menu de contexto não compila e não dá erro...
Se uso minha tecla de atalho [command+F9] recebo...
![image](https://user-images.githubusercontent.com/19559870/45329868-ecc61280-b538-11e8-8f54-2314dbc6ef41.png)

E depois todas as tentativas mostram...
![image](https://user-images.githubusercontent.com/19559870/45329887-fe0f1f00-b538-11e8-8088-f7bda6a5ad19.png)

Tentei gerar novo cipher e tb não mostra a saída...

O que eu perdi... 😩

**Comment by killerall** [comment]
Boa noite,
Ontem soltei uma atualização, que não deveria ter feito nada disso.

No seu $DIRTMP deve ter gerado um arquivo AdvplDebugBridgeC.log, tem alguma informacao nele?

**Comment by killerall** [comment]
Acho que peguei o problema aqui.
O executavel novo não foi com a propriedade de execucao.
entre na pasta.
/Users/seu_usuario/.vscode/extensions/KillerAll.advpl-vscode-0.10.9/bin/alpha/mac
e faça:
$chmod +x internall
e depois
#chmod +x AdvplDebugBridgeC

**Comment by jcstorino** [comment]
@killerall Quem dera a Totvs respondesse nossos chamados do protheus com a mesma velocidade e dedicação do Rodrigo... funcionou perfeitamente.... obrigado 😀👍🏻

**Comment by charlesreitz** [comment]
Show! Aqui tbm resolveu!

**Comment by ihorran** [comment]
Estou com o mesmo problema porem não consegui fazer o procedimento, diz que o comando não existe

**Comment by killerall** [comment]
@ihorran 
Boa noite, Acabei de atualizar o vscode, em tese apenas atualizando deve voltar a compilar normalmente.

**Comment by killerall** [comment]
Corrigido na versão 0.10.12.
