### ISSUE TITLE
Gerar paths a partir de fontes do RPO

### ISSUE THREAD

**Issue by paulogabrielfs** [killerall/advpl-vscode#275]
Implementar a geração de Patch`s a partir dos fontes do RPO.

**Comment by killerall** [comment]
Boa tarde,

Você pode ser um pouco mais especifico?

**Comment by wiliam-bertoncini** [comment]
Boa noite Rodrigo.
No Developer Studio antigo existia a opção Ferramentas / Geração de Atualizações, onde era listada todos os fontes existentes no RPO e eu conseguia gerar uma patch com os arquivos selecionados do RPO.

**Comment by killerall** [comment]
@wiliam-bertoncini 
O Vscode já faz isso:
https://github.com/killerall/advpl-vscode/wiki/Trabalhando-com-Patchs

**Comment by wiliam-bertoncini** [comment]
Obrigado Rodrigo

Enviado do meu iPhone

Em 20 de set de 2018, à(s) 09:12, Rodrigo Antonio Godinho da Silva <notifications@github.com<mailto:notifications@github.com>> escreveu:


@wiliam-bertoncini<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwiliam-bertoncini&data=02%7C01%7C%7Ce69b808f52a34b6d56ab08d61ef25ee7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636730423648004009&sdata=oh8SPfDDmgFVwHOpMSxU7Vk2b9dpc5vdnRJDHtkBAgA%3D&reserved=0>
O Vscode já faz isso:
https://github.com/killerall/advpl-vscode/wiki/Trabalhando-com-Patchs<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkillerall%2Fadvpl-vscode%2Fwiki%2FTrabalhando-com-Patchs&data=02%7C01%7C%7Ce69b808f52a34b6d56ab08d61ef25ee7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636730423648004009&sdata=bvH71JxnkDe5qEBtbnZCTpi0Mfs4K5SpgFUU0d1RDpE%3D&reserved=0>
