### ISSUE TITLE
Can't launch debug invalid user or password

### ISSUE THREAD

**Issue by samaronybarros** [killerall/advpl-vscode#277]
Não sei por qual motivo, mas hoje ao usar o Debug no VS Code ele parou de funcionar apresentando o seguinte erro

![image](https://user-images.githubusercontent.com/10220629/45840832-86868000-bcee-11e8-902f-91ec7623d025.png)

O interessante é que quando aperto F5 e escrevo `SIGAADV` a mensagem aparece, porém ao digitar CTRL+F5 ele funciona normalmente

Deletei o arquivo launch.json e recriei e o problema persiste.

Por ser possível problema de *password* criei uma nova criptografia de senha com o `cipher`, mas o problema persiste.

O que poderia ser isso?

**Comment by killerall** [comment]
Não consigo ver algum motivo para isso.
Não foi alterado nada do ambiente?
É no windows?

**Comment by robsonrosilva** [comment]
Isso acontece quando conecto em appserver master, nesses casos tem que conectar com slave.

**Comment by samaronybarros** [comment]
@killerall , Não foi alterado nada no ambiente. É no windows

@robsonrosilva  Não estou usando balanceamento de carga.

**Comment by killerall** [comment]
@samaronybarros 
Ative o log
No setting coloca advpl.logger ,'true'.
No %TEMP% da sua maquina vai gerar um arquivo de log, AdvplDebugBridge.log, veja se gera esse arquivo.
Veja se ele da mais algum detalhe nele.

**Comment by samaronybarros** [comment]
@killerall 
Primeiramente, obrigado por me ajudar nesse problema

Coloquei o `advpl.logger` no *User Settings*

![image](https://user-images.githubusercontent.com/10220629/45899102-51436600-bdb2-11e8-877f-906e1476b35d.png)

Rodei o Debug pelo F5 e novamente apareceu a mensagem de erro

![image](https://user-images.githubusercontent.com/10220629/45899163-7932c980-bdb2-11e8-8c29-2ad6ed4bc213.png)

Ao buscar o arquivo `AdvplDebugBridge.log` o mesmo não se encontra no log da %TEMP%

![image](https://user-images.githubusercontent.com/10220629/45899270-b9924780-bdb2-11e8-9b8b-686effedd9fe.png)

**Comment by samaronybarros** [comment]
@killerall , Não foi alterado nada no ambiente. É no windows

@robsonrosilva  Não estou usando balanceamento de carga.

**Comment by samaronybarros** [comment]
Tinha um erro que eu não havia atentado
![image](https://user-images.githubusercontent.com/10220629/45955221-b501a500-bfe5-11e8-894b-2f34a5870275.png)

Entretanto, tive o mesmo resultado. Ainda não consigo debugar

**Comment by killerall** [comment]
@samaronybarros 
Mais foi gerado o arquivo de log? na pasta temp?

**Comment by samaronybarros** [comment]
Sim, acabei de ver que foi gerado e identifiquei o problema.

A senha havia sido alterada. Corrigi, gerei o `>cipher` e ficou OK.

Obrigado pela disponibilidade
