### ISSUE TITLE
[MAC OS] Falha ao compilar folder

### ISSUE THREAD

**Issue by jcstorino** [killerall/advpl-vscode#279]
Bom dia...
Não consigo ainda compilar uma pasta no mac os, agora apresenta várias mensagens (para cada fonte) no console de saída.
![image](https://user-images.githubusercontent.com/19559870/46079211-dc36ae80-c16c-11e8-85a8-1c1ef359b992.png)
a chave advpl.logger esta ativa, segue o log gerado...
[AdvplDebugBridgeC_0.log](https://github.com/killerall/advpl-vscode/files/2419614/AdvplDebugBridgeC_0.log)

Grato..

**Comment by killerall** [comment]
Boa noite,
Eu já corrigi esse problema, na proxima versão já vai estar corrigido.
Obrigado.

**Comment by killerall** [comment]
Corrigido na versão 0.10.12.
