### ISSUE TITLE
Compilação - SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by charlesreitz** [killerall/advpl-vscode#283]
Ao tentar compilar apresenta a msg de syntax erro, seria minha configuração de usuário, pois revi e aparente está certo. 

Bridge Return:

SyntaxError: Unexpected end of JSON input
Compilação finalizada em Fri Oct 05 2018 09:22:06 GMT-0300 (-03) tempo consumido (0.109 segs.)

**Comment by killerall** [comment]
Ele da algo no console do server?

**Comment by haskellcamargo** [comment]
Começou isso aqui também na última versão. Ele dá a mensagem de erro, mas compila mesmo assim. No entanto, não é mais possível fazer debug e nem executar via F5. Estou executando o SmartClient na mão.

**Comment by killerall** [comment]
Por favor,
Ativa o advpl.logger : true , na configuração. 
Na pasta TEMP do usuario deve gera um arquivo chamdo AdvplDebugBridge.log
Cola ele aqui.

**Comment by jcstorino** [comment]
Olá @killerall , aqui no MAC OS tb não lançando mais do debug.. chega a aparecer o ícone do SmartClient, mas não mostra nenhuma tela...

![image](https://user-images.githubusercontent.com/19559870/46624176-646e6980-cb06-11e8-9b9c-50e13b77326b.png)


Segue o AdvplDebugBrideC_0.log
[AdvplDebugBridgeC_0.log](https://github.com/killerall/advpl-vscode/files/2456983/AdvplDebugBridgeC_0.log)

**Comment by killerall** [comment]
@jcstorino 
Não tem erro nenhum no seu log.
A noite vou atualizar o VSCODE na VM Mac que tenho e testar. Mais não consegui reproduzir isso no Windows.

@haskellcamargo Você usa que SO?

**Comment by killerall** [comment]
@jcstorino 
Fiz o teste do MAC, antes de atualizar, na 1.27.2 funcionava normal, ai atualizei para 1.28.0 e para aqui.
Estou investigando o que a microsoft fez.

**Comment by denispolastri** [comment]
Bom dia Rodrigo, tudo bem?
Parabéns pelo trabalho com o VSCode, está ficando muito bom!
Estou com o mesmo problema reportado pelo @jcstorino, porém estou utilizando o Windows 10.
![image](https://user-images.githubusercontent.com/25599597/46663140-b14c5180-cb93-11e8-9486-7804c6e50c9c.png)
Quando pressiono F5 para o debug, não executa nada.
Abraço.

**Comment by killerall** [comment]
@denispolastri 
Bom dia.
No Windows eu so consigo reproduzir isso com "advpl.alpha_compile": true,
Se esse for seu caso, volte para false. Estou tentando identificar o que mudou no protocolo de debug do vscode.

**Comment by silfar** [comment]
E no linux? 
tô tendo o seguinte erro:
SyntaxError: Unexpected number in JSON at position 1
Compilação finalizada em Tue Oct 09 2018 10:49:18 GMT-0300 (-03) tempo consumido (1.836 segs.)

**Comment by killerall** [comment]
@silfar 
Quando você tenta compilar ou debugar?

**Comment by silfar** [comment]
Quanto tento compilar:
Bridge Return:
------------------------------------------------------------------{"msgs":[{"Key":"NOSOURCE","Value":[{"Line":-1,"Column":0,"Type":1,"Message":"Source IA04RT01.PRW Skipped!"}]}]}
SyntaxError: Unexpected number in JSON at position 1
Compilação finalizada em Tue Oct 09 2018 11:16:35 GMT-0300 (-03) tempo consumido (1.833 segs.)

e o debug não dispara o smartclient

**Comment by killerall** [comment]
O Debug não iniciar eu já identifiquei e resolvi, a noite vou lancar uma nova versão.
Na compilacao esta dando que o fonte foi Skipado pois não teve alteração.
Não era para dar erro nesse json. Vou verificar.

**Comment by silfar** [comment]
pois é o erro do json que é estranho.
Silfar Goulart


Em ter, 9 de out de 2018 às 11:31, Rodrigo Antonio Godinho da Silva <
notifications@github.com> escreveu:

**Comment by silfar** [comment]
kde neon, que base ubuntu 64

**Comment by silfar** [comment]
[image: image.png]

Estranho que o erro ṕarece ser aqui no arquivo de config. Tá vendo ali as
marcas vermelhas ?
Silfar Goulart


Em ter, 9 de out de 2018 às 14:26, Rodrigo Antonio Godinho da Silva <
notifications@github.com> escreveu:

**Comment by killerall** [comment]
@silfar Não veio a imagem.

**Comment by silfar** [comment]
![image](https://user-images.githubusercontent.com/68900/46690206-19bd2200-cbd8-11e8-8d9e-2d4c90d39123.png)

**Comment by killerall** [comment]
Acredito que seu problema pode ter a ver em ter diversas pastas abertas (no seu json tem o "folders" do vscode).
Tente abrir apenas 1 pasta, ao inves da workspace.
Não consigo testar agora o caso no linux.

**Comment by killerall** [comment]
@silfar @denispolastri @jcstorino 
Pessoal boa noite
Corrigido na versão 0.10.12.

Obrigado.

**Comment by silfar** [comment]
A atualização corrigiu tudo, a té amensagem de Json.

Muito obrigado pelos eu trabalho.

**Comment by jcstorino** [comment]
Tudo funcionado no MAC @killerall !! Perfect !!

**Comment by denispolastri** [comment]
Tudo ok, ótimo trabalho, obrigado @killerall , Abraço.

**Comment by charlesreitz** [comment]
o meu ainda apresenta a msg :( 


Bridge Return:

SyntaxError: Unexpected end of JSON input
Compilação finalizada em Wed Oct 10 2018 09:55:22 GMT-0300 (-03) tempo consumido (0.653 segs.)


set

Será que pode ser meu settings? 

[setting.txt](https://github.com/killerall/advpl-vscode/files/2464711/setting.txt)

**Comment by killerall** [comment]
@charlesreitz 
Você esta numa maquina MAC é isso?
"smartClientPath": "//Applications//smartclient.app//Contents//MacOS//",
Acredito que o caminho do smart client  quanto o do include não tem essas // duplas.

**Comment by charlesreitz** [comment]
Ajustei, mas mantém o erro

**Comment by killerall** [comment]
O includeList termina com "/"??
"includeList": "/Users/charlesreitz/git/websales2/advpl/includes/",

**Comment by charlesreitz** [comment]
Tinha ajustado esse caminho, tbm não foi..

Att.

*Charles Reitz*
*Gtalk/Email: *charles.reitz@gmail.com
*Twitter:* @charlesreitz
*Skype:* charles.reitz
*Contato:* (47) 8804-6686



Em qua, 10 de out de 2018 às 11:30, Rodrigo Antonio Godinho da Silva <
notifications@github.com> escreveu:

**Comment by killerall** [comment]
Abra o temp do seu MAC
$echo $TMPDIR

va nesse diretorio e mande o AdvplDebugLogC.log, que é criado nele, pf.

**Comment by charlesreitz** [comment]
Segue

![t_ _-bash_ _80x24_e_compilacao_-_syntaxerror__unexpected_end_of_json_input_ _issue__283_ _killerall_advpl-vscode](https://user-images.githubusercontent.com/1248135/46876558-021ead00-ce15-11e8-84e3-482fa71997e5.jpg)

**Comment by killerall** [comment]
O log não ajudou muito. Estou sem ideia do que pode estar acontencendo.
Vc esta usando uma VM para rodar o Server?
Se sim. ja tentou fazer a compilacao com vscode dentro dessa vm?

**Comment by charlesreitz** [comment]
Tentei conectar em um servidor cloud, mesmo erro. 

Alguém pode enviar o usersettings do vscode para eu conferir com o meu?

**Comment by killerall** [comment]
@charlesreitz 
Da uma olhada na seguinte extensão
https://marketplace.visualstudio.com/items?itemName=totvs.protheus-dev-sandbox
Ela configura automaticamente o vscode para usar em advpl, e o pessoal que fez usa MAC.

Ela ainda funciona com o Docker para subir o ambiente.

**Comment by FRReinert** [comment]
> o meu ainda apresenta a msg :(
> 
> Bridge Return:
> 
> SyntaxError: Unexpected end of JSON input
> Compilação finalizada em Wed Oct 10 2018 09:55:22 GMT-0300 (-03) tempo consumido (0.653 segs.)
> 
> set
> 
> Será que pode ser meu settings?
> 
> [setting.txt](https://github.com/killerall/advpl-vscode/files/2464711/setting.txt)

Converte o appserver.ini em ANSI, dê uma boa olhada no arquivo, pode ter símbolos estranhos, principalmente nas quebras de linha. Se tiver, deleta os simbolos e salva arquivo.

Eu uso o Notepad++ no Windows para estes manuseios, mas da pra fazer no VS também. 

Espero ter ajudado
