### ISSUE TITLE
Erro ao tentar compilar lista de arquivos TXT

### ISSUE THREAD

**Issue by Wexlei** [killerall/advpl-vscode#285]
Ao tentar utilizar o comando _AdvPl - Compile TXT list of files_, ocorre o seguinte erro:

#### **Running the contributed command:'advpl.menucompiletextfile' failed.**

O arquivo é um documento _log_ com o nome de 38 fontes com extensão _prw_ e _prx_ nesse formato:
file01.prx
file02.prx
file03.prx
file04.prw
file05.prw
file06.prx
[...]

O comando para compilar lista de TXT também não aparece mais no menu de contexto da árvore.

**Dados do VS Code:**
Version: 1.28.0 (system setup)
Commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
Date: 2018-10-04T16:47:36.731Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: ia32

**Comment by killerall** [comment]
@Wexlei Qual o Sistema Operacional?

**Comment by killerall** [comment]
Foi feita uma alteração, apenas arquivos .txt o menu aparece de contexto.
Se você chamar esse comando via F1, vai dar erro mesmo.
Renomeei o arquivo para .txt.

**Comment by Wexlei** [comment]
Com o formato txt funcionou tudo certinho. Era só porque o formato do documento era .log mesmo. Obrigado!
