### ISSUE TITLE
Erro ao gerar patch

### ISSUE THREAD

**Issue by samaronybarros** [killerall/advpl-vscode#286]
Após atualizar o VS Code as opções de aplicar patch, gerar patch... não estão mais no menu do botão direito

![image](https://user-images.githubusercontent.com/10220629/46667842-3be77d80-cba1-11e8-927c-a8c7831156b8.png)

Ao utilizar o CTRL + SHIFT + P e selecionar a aplicação de patch 

![image](https://user-images.githubusercontent.com/10220629/46667941-76511a80-cba1-11e8-8c4e-b919c98663bd.png)

O VS Code apresenta a seguinte mensagem 

![image](https://user-images.githubusercontent.com/10220629/46667985-95e84300-cba1-11e8-8641-16343333a0b2.png)

**Comment by izacsc** [comment]
De ser um arquivo.txt

Em ter, 9 de out de 2018 08:59, Sam Barros <notifications@github.com>
escreveu:

**Comment by samaronybarros** [comment]
Perfeito Izac,

Era isso mesmo, eu usava o arquivo sem extensão e funcionava, então não imaginei que fosse isso.

Muito obrigado

**Comment by izacsc** [comment]
Foi uma alteração recente para filtrar as opções do menu de contexto (botão
direito). A opção de gerar patch ficou somente para arquivos txt

Em ter, 9 de out de 2018 09:51, Sam Barros <notifications@github.com>
escreveu:

**Comment by samaronybarros** [comment]
Excelente, resolvi aqui. 

Obrigado mais uma vez
