### ISSUE TITLE
Debug macOS não funciona na nova versão do vscode (1.28)

### ISSUE THREAD

**Issue by paulogabrielfs** [killerall/advpl-vscode#287]
O debug no mac parou de funcionar após a atualização do vscode para a versão 1.28.0.
Iniciar o smartclient com a opção "Sem debugar" funciona normalmente.

**Comment by killerall** [comment]
@paulogabrielfs 
Já estamos vendo o pq isso ocorre. 

https://github.com/killerall/advpl-vscode/issues/283

**Comment by killerall** [comment]
Corrigido na versão 0.10.12.
