### ISSUE TITLE
Opção "Build Patch" não é exibida após atualização do VSCode

### ISSUE THREAD

**Issue by julianeventeu** [killerall/advpl-vscode#288]
Oi!

Atualizei o VSCode ontem para a versão 1.28.0 e o menu de opçoes exibidas para o arquivo mudou, não mostrando mais as opções de interação com patch.

Se eu tento forçar o comando gera erro.

Todavia, se eu volto o plugin do advpl para a versao 0.8.2 volta a funcionar normalmente.

**Comment by julianeventeu** [comment]
Agora:
![agora](https://user-images.githubusercontent.com/11297954/46734874-28214180-cc9d-11e8-968f-40f0b9176cd9.png)

Antes:
![antes](https://user-images.githubusercontent.com/11297954/46734876-28214180-cc9d-11e8-93d8-43f7abd6f1ef.png)

Erro:
![erro](https://user-images.githubusercontent.com/11297954/46734877-28b9d800-cc9d-11e8-9293-6417bc6cb225.png)

Versao VSCode:
![versaovscode](https://user-images.githubusercontent.com/11297954/46734878-28b9d800-cc9d-11e8-8b99-ec3e302b8ed1.png)

**Comment by izacsc** [comment]
@julianeventeu, foram feitas alterações para exibir os comandos de menu conforme a extensão do arquivo. Os comandos de patch só serão exibidos para extensões "ptm".

**Comment by killerall** [comment]
Ju como o Izac falou, foi feito essa alteração.
Para gerar path apenas extensões .txt.

[]s

**Comment by julianeventeu** [comment]
Ok, alterei a extensão e funcionou.

Obrigada!

**Comment by diegpo2** [comment]
Olá.
Verifiquei este post e estava com este problema, mas não entendi direito como corrigir. 
Como assim alterar a extensão?

**Comment by izacsc** [comment]
O arquivo texto com a lista do que deve ser gerado dever um arquivo txt:

Ex: salve a lista de arquivos no arquivo lista.txt
