### ISSUE TITLE
erro ao tentar iniciar o debug (F5)

### ISSUE THREAD

**Issue by andreronaldo** [killerall/advpl-vscode#290]
Debugging with inspector protocol because Node.js version could not be determined (Error: connect ECONNREFUSED 127.0.0.1:9229)

**Comment by killerall** [comment]
Boa noite.
Consegue explicar melhor o que esta acontecendo?

**Comment by andreronaldo** [comment]
Boa tarde quando ia iniciar o debug apresentava essa mensagem, consegui resolver tirando a configuração de launch json de comunicação via port padrão que tinha
