### ISSUE TITLE
Fusão de Projetos

### ISSUE THREAD

**Issue by AlencarGabriel** [killerall/advpl-vscode#291]
Boa tarde @killerall , criei uma extensão para resolver um problema comum que os desenvolvedores ADvPl tem que é o conflito de arquivos com o mesmo nome no debug, em um mesmo workspace, e a troca entre projetos sem precisar reabrir uma nova área de trabalho.

Atualmente está sendo usada e testada por alguns colegas analistas da TOTVS e terceirizados, acredito que possa ser algo interessante para trabalharmos juntos, já que é um problema comum.

Inclusive para o futuro estava querendo fazer algo parecido com a seleção dos Ambientes, pois quando se trabalha em vários clientes a lista de ambientes fica extensa, e minha ideia seria vincular os Ambientes por Projeto.

Caso seja de seu interesse, aguardo contato.

Link do projeto:
> https://github.com/AlencarGabriel/advpl-switch-project

**Comment by killerall** [comment]
Boa noite @AlencarGabriel .
Parabens pela iniciativa.
Acredito que pode ser bem util para o pessoal que tem essa necessidade.
A ideia de ambientes é bem bacana tambem. Fique a vontade em desenvolve-la, tanto fazendo um pull request aqui, ou colocando na sua extensão.

Se precisar de apoio em algo relativo ao Bridge, basta me avisar.

Abraço.

**Comment by AlencarGabriel** [comment]
Bom dia @killerall , gostaria de pedir uma opinião sua para a conversa acima, referente a vinculação dos ambientes por projeto, irei fazer um Pull Request pra você, mas preciso resolver como fazer.

Você acharia melhor:
- [ ] Colocar minha extensão como dependência da sua
- [ ] Verificar se a minha extensão está instalada, e habilitar o funcionamento

Após uma análise, vi que seria melhor se a sua extensão considerasse os ambientes por projeto, se não eu teria que desenvolver uma forma da minha extensão manipular a configuração `advpl.environments`, semelhante o que eu fiz com as pastas do Workspace.

**Comment by AlencarGabriel** [comment]
Boa noite @killerall , ainda no aguardo do seu retorno para dar continuidade no Pull Request. Alguns colegas estão me cobrando esse recurso.

Agradecido pela compreensão.

**Comment by killerall** [comment]
Boa noite @AlencarGabriel 
Acredito que nenhum dos dois.
O ideal seria fazer na extensão principal, um esquema de protocolo/extensao igual ao proprio vscode.
Pois outras extensão poderiam contribuir e você tira o acomplamento entre extensões.

**Comment by AlencarGabriel** [comment]
Para ter certeza se entendi o que quis dizer, eu teria que adicionar todas as funcionalidades da minha extensão, na extensão criada por você, como se fosse mais um recurso? 

Meu questionamento se deu, devido ao fato que que eu teria que alterar na sua extensão para listar somente os ambientes de um determinado projeto, para isso eu criaria mais um atributo no objeto `advpl.environments` e ao clicar em **Selecionar ambientes** a extensão consideraria  somente os ambientes referentes ao projeto.

Penso eu que colocar este recurso direto na extensão principal forçaria um uso "engessado", onde o usuário irá sempre trabalhar com Ambientes x Projetos.

**Comment by killerall** [comment]
Acredito que eu não me fiz entender.
O que pensei é justamente ao contrario.
A ideia seria implementar nesta extensão o conceito extension point. Aonde outras extensões como a sua conseguem interagir com está aqui.

**Comment by AlencarGabriel** [comment]
Entendi, essa a principio era minha ideia, a dificuldade seria manipular os environments. 

Tive uma ideia essa noite, que seria criar mais um atributo definindo se o ambiente é usado ou não, e ai a minha extensão iria manipular este atributo, consequentemente a opção de seleção de ambientes traria apenas os ambientes ativos.

O que acha?

**Comment by AlencarGabriel** [comment]
Bom dia @killerall , ainda no aguardo do seu retorno para dar continuidade no Pull Request. Alguns colegas estão me cobrando esse recurso.

Agradecido pela compreensão.

**Comment by killerall** [comment]
@AlencarGabriel 
A sua ideia de criar um atributo, resolve apenas o que você quer fazer. o Lance de Extenstion Point da a oportunidade de outras extensões conseguirem contribuir.
Até o dia 3/11 não estou com tempo para pensar/propor nada relativo isso. Depois disso volto a ter mais tempo para mexer por aqui.

**Comment by AlencarGabriel** [comment]
@killerall , qual a previsão de lançamento da próxima versão da extensão?

**Comment by AlencarGabriel** [comment]
Ótimo, só aguardando a atualização para eu lançar o update da minha também.
