### ISSUE TITLE
Extrair Patch a partir de um arquivo.

### ISSUE THREAD

**Issue by evandromariano** [killerall/advpl-vscode#293]
Depois das ultimas atualizações do VSCode, começou a apresentar o seguinte erro.

running the contributed command: advpl.patch.build failed

Ocorre quando quero extrair um patch.

Antigamente só precisava clicar com o botão direito do mouse e clicar para extrair o patch através do arquivo, essa opção desapareceu.

Tenti com a opção CTRL + Shift + P tem a opção Advpl - Patch - Build - Cria um Patch(PTM) da lista de arquivo.

E apresentou a mensagem a cima.

Mudou a forma de extrair os Patchs?

Abraços

**Comment by izacsc** [comment]
Foi adicionada uma validação para somente exibir os comandos para arquivos txt.

**Comment by evandromariano** [comment]
Ele apresenta essa mensagem quando aplico na versão 12.

"Message":"Can't validPatch:Path version incorrect, file TTTP110

Teria como "converter" esse patch para a versão 12?

Alguém já passou por isso?

**Comment by killerall** [comment]
@evandromariano 
Não tem como aplicar uma patch da versão 11 na versão 12. São incompativel.
