### ISSUE TITLE
Debug MacOS

### ISSUE THREAD

**Issue by rodrigosanches** [killerall/advpl-vscode#296]
Boa tarde, 

gostaria de uma ajusta, eu conseguindo utilizar o VsCode normal para compilar, executar o smartCliente, mas quando eu tento realizar o Debug, me traz a seguinte mensagem "Program smartclient does not exist", e tem a opção de abrir o arquivo Lauch.json

Mas pelo atalho "Run SmartClient Protheus" o smartCliente abre normalmente.

**Comment by jcstorino** [comment]
Verifique o seguinte…

	Se seu SmartClient.app esta na pasta /Applications que é o mais comum…

	No seu settings.json deve haver uma configuração de ambiente com a chave smartclientpath, conforme abaixo..

		"smartClientPath": "/Applications/smartclient.app/Contents/MacOS/"

	E no seu launch.json uma configuração com a abaixo…

        {
                "name": "SmartClient SIGAADV",
                "type": "advpl",
                "request": "launch",
                "args": [],
                "cwd": "${workspaceRoot}",
                "programRun": "SIGAADV",
                "stopOnEntry": false,
                "enviromentInfo": "${command:GetEnvInfos}",
                "workspace": "${workspaceRoot}"
            },

**Comment by rodrigosanches** [comment]
Bom dia,

Obrigado pela ajuda agora funcionou corretamente o Debug.
