### ISSUE TITLE
Debug depois de atualização do VS.COD

### ISSUE THREAD

**Issue by iurysa** [killerall/advpl-vscode#301]
Verifiquei que depois do ultimo update do vs.code, o degub tem se perdido (como acontecia no devstudio do smartclient) testei tanto no windows como no mac apesar de agora eu estar usando o mac, ele simplesmente aleatoriamente trava não exibe nenhuma mensagem, se eu rodo o codigo sem debugar ele roda até o final.

**Comment by killerall** [comment]
@iurysa 
Boa noite,
Você consegue precisar se foi apos a ultima atualização do vscode em si, ou da extensão?

**Comment by iurysa** [comment]
Acredito que tenha sido a ultima do visual studio, mas tá muito estranho, ele simplesmente para o debug trava o smartclient e não da nenhum erro em linhas aleatorias.

**Comment by phcc2306** [comment]
Bom dia pessoal.
Estou tendo problemas após a atualização do VSCode também.
O meu problema é o mesmo relatado nessa issue,
https://github.com/killerall/advpl-vscode/issues/205
Porem acontece ao utilizar o vscode com pastas e workspaces.
Não sei se é o mesmo caso relatado pelo amigo @iurysa.

**Comment by iurysa** [comment]
No mac não apresentava tela de erro, passei usar no windows dentro da maquina onde o app server está trabalhando, e me foi apresentado o seguinte erro 

[FATAL][SERVER] [Thread 27740] [THROW] Communication error: Failure receiving message at file D:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-BUILDV2APPSRV-TEC11WIN32RPO32\advtec9_tt11\lib_comm\tprotocolrmt.cpp line 9664
THREAD ERROR [ 27740 ]
UserName: totvs.iury
ComputerName: HEFESTO
Severity:  3
Error Code: 56
Description: Communication error: Failure receiving message
Stack: 
THREAD ERROR ([27740], totvs.iury, HEFESTO)   21/11/2018 08:00:47
Communication error: Failure receiving message on FPRSIND(BRA0701.PRW) 21/11/2018 07:50:35 line : 462

[TOTVS build: 7.00.131227A-20180328 NG]
Called from FPRSIND(BRA0701.PRW) 21/11/2018 07:50:35 line : 462
Called from {||fPrSinD()}(BRA0701.PRW) 21/11/2018 07:50:35 line : 462
Called from { || FWSetShowKeys( .F. ), Eval( bAction, @lEnd ),lEnd := .t. , FWSetShowKeys( .T. ), oDlgModal:Deactivate() }(MSPROCES.PRW) 15/05/2015 11:54:38 line : 462
Called from {|Self|(Eval(oSelf:bInit))}(FWDIALOGMODAL.PRW) 27/01/2016 17:48:54 line : 462
Called from ::MSDIALOG:ACTIVATE line : 462
Called from FWDIALOGMODAL:ACTIVATE(FWDIALOGMODAL.PRW) 27/01/2016 17:48:54 line : 458
Called from PROCESSA(MSPROCES.PRW) 15/05/2015 11:54:38 line : 95
Called from FSINDAD(BRA0701.PRW) 21/11/2018 07:50:35 line : 319
Called from FWMBROWSE:EXECUTE(FWFORMBROWSE.PRW) 21/06/2017 17:06:57 line : 1077
Called from { || OSELF:EXECUTE("STATICCALL",              4,             0,"SINCRONIZAR DADOS",              7,"(BRA0701, FSINDAD)","","",               7) }(FWFORMBROWSE.PRW) 21/06/2017 17:06:57 line : 1077
Called from ::MSDIALOG:ACTIVATE line : 1077
Called from FWMBROWSE:ACTIVATE(FWMBROWSE.PRW) 05/05/2017 18:12:47 line : 674
Called from U_BRA0701(BRA0701.PRW) 21/11/2018 07:50:35 line : 36
Called from SIGAIXB(APLIB190.PRW) 20/10/2016 15:18:43 line : 228
Called from __EXECUTE(APLIB090.PRW) 05/06/2017 17:10:02 line : 541
Called from MDIEXECUTE(APLIB260.PRW) 04/04/2017 17:51:27 line : 820
Called from STATICCALL(APLIB260.PRW) 04/04/2017 17:51:27 line : 820
 

[INFO ][SERVER] [Thread 27740] [21/11/2018 08:06:08] Thread finished (totvs.iury, HEFESTO)

**Comment by killerall** [comment]
Não cheguei a utilizar ainda a ultima versão de Outubro, Pode ter ocorrido alguma mudança igual em setembro.
Vou verificar com o pessoal que trabalha comigo aqui se alguem conseguiu simular isso.

Devo lancar hoje a versão com algumas correções para alpha/Mac mais a alteração do @AlencarGabriel .
Vamos ver se o problema persiste.

**Comment by AlencarGabriel** [comment]
Ótimo, você lançando a atualização vamos fazer mais testes e reportamos aqui. 

Vi que você fez algumas alterações no Bridge também, pode ser que resolva. Estava acompanhando também aquela issue sobre o Call Stack.

**Comment by AlencarGabriel** [comment]
> Bom dia pessoal.
> Estou tendo problemas após a atualização do VSCode também.
> O meu problema é o mesmo relatado nessa issue,
> #205
> Porem acontece ao utilizar o vscode com pastas e workspaces.
> Não sei se é o mesmo caso relatado pelo amigo @iurysa.

@killerall , fazendo mais testes identifiquei o mesmo problema do @phcc2306 , e cada vez que "debugo" esse erro é causado em uma linha diferente, seja antes ou depois da anterior. Mas só acontece em debug.

![image](https://user-images.githubusercontent.com/10109480/48860924-68e69d00-eda9-11e8-859e-70c95bebe640.png)

**Comment by WEBGITbruno-ferreira** [comment]
Tenho notado com frequência esse mesmo erro citado pelo @AlencarGabriel , o debug se perde, muitas vezes não volta. 

Notei um detalhe,  as  teclas  de Step Into  e Step Over foram invertidas.  Anteriormente o Step Over era o F10, passou a ser  F11.  Atualmente na barrinha do DEBUG ainda  aparece invertido.  Isso estava causando alguns erros quando passavamos com o F10 (Atual step into) em funções padrões. 

![image](https://user-images.githubusercontent.com/41831408/48862407-71d96d80-edad-11e8-8f59-23f6d8783a4c.png)

**Comment by AlencarGabriel** [comment]
Boa tarde @WEBGITbruno-ferreira , fiquei intrigado quando falou sobre a inversão de teclas, e acabei fazendo alguns testes com F11 ao invés do F10 (Step Over) e tambem usando o botão, o erro continuou acontecendo.

Na verdade acho que não houve inversão, sempre esteve configurado no meu VsCode F10 como Step Over e F11 como Step Into. 

---

@killerall , falando nesse assunto de inversão, será que não é o no *README.md* que está invertido?

Peguei este print na página oficial do VsCode: [https://code.visualstudio.com/docs/getstarted/keybindings](https://code.visualstudio.com/docs/getstarted/keybindings)

![image](https://user-images.githubusercontent.com/10109480/48864439-ac460900-edb3-11e8-8c32-bcecf01c4621.png)

**Comment by killerall** [comment]
A documentação esta errada no README.

**Comment by killerall** [comment]
Já consegui reproduzir o que esta acontecendo. A Microsoft mudou novamente algumas coisas no protocolo de debug.
Eu fiz uma correção que estamos testando. Se der certo, vou liberar uma versão o mais rapido possivel.

**Comment by AlencarGabriel** [comment]
@killerall , bom dia.

Atualizei aqui, e o erro que mandei acima parou de acontecer. Porem o Debug ainda está com uma certa inconsistência. 

Quando estou debugando pressionando F10 de forma "lenta" (esperando a próxima linha ser posicionada), eu consigo debugar normalmente, mas percebi que agora quando aperto F10 de forma consecutiva (sem esperar posicionar na próxima linha), o debug trava, sem retornar nenhum erro nem encerra a sessão do Debug. 

Será que isso agora não é um problema por conta da atualização da versão de outubro?

**Comment by killerall** [comment]
@AlencarGabriel 
Atualizei o AdvplDebugBridge aqui no github, pega essa versao e troca da sua instalação (Deve ficar em algo como C:\Users\rodrigo.antonio\.vscode\extensions\killerall.advpl-vscode-0.10.14\bin).
Com essa versao o Debug rapido deve funcionar.
Consegue fazer esse teste?

**Comment by AlencarGabriel** [comment]
Sim, irei baixar agora e testar.

**Comment by AlencarGabriel** [comment]
> @AlencarGabriel
> Atualizei o AdvplDebugBridge aqui no github, pega essa versao e troca da sua instalação (Deve ficar em algo como C:\Users\rodrigo.antonio.vscode\extensions\killerall.advpl-vscode-0.10.14\bin).
> Com essa versao o Debug rapido deve funcionar.
> Consegue fazer esse teste?

@killerall , agora está funcionando muito bem. Não sei se é impressão minha, mas achei que o debug está mais rápido que antes.

Olhei a pilha de execução, e está certinha tambem, mostrando o histórico de chamadas.

Pretende lançar quando esse update no Bridge?

**Comment by killerall** [comment]
Eu preciso fazer a mesma alteracao em MAC e linux, e só consigo fazer a noite de casa.
Devo lança hj a noite ou amanha.
Obrigado.

**Comment by killerall** [comment]
Liberada a versão com as correcoes dessa issue. Se tiverem algum outro problema. Por favor reabram a issue.

**Comment by iurysa** [comment]
Na versão 0.10.14 o problema havia sido corrigido para o MAC, na versao 0.10.15 o problema voltou a acontecer.

**Comment by killerall** [comment]
@iurysa Na 14 não foi feito nada, não tem como ter resolvido no MAC nessa versão.

Você consegue dizer como fazer para simular a queda?

Não tive relatos na versão Linux( que é a mesma do MAC) do pessoal que usa o mint aqui.

**Comment by killerall** [comment]
@iurysa Eu peguei uma situação de voar se o watch tive-se com algo preenchido, eu já lancei uma atualização. Veja como se comporta.

**Comment by ShinyTotvs** [comment]
Peguei o mesmo erro de ReadMsChar, e estou com a versão 0.10.18. 
Ja existe uma correção para este caso?

**Comment by killerall** [comment]
Esse caso foi resolvido há algum tempo.
Abra uma issue nova, com o detalhe do que esta acontencedo por favor.
