### ISSUE TITLE
Gerar query para AdvPL

### ISSUE THREAD

**Issue by gustavo-krug** [killerall/advpl-vscode#305]
Bom dia

Estávamos conversando em nossa squad sobre a possibilidade de ter algum atalho que gere uma estrutura básica de SQL para advpl, segue exemplo: 

Local cAliasQry  := GetNextAlias()
Local cQuery     := ''

cQuery := " SELECT * "	
cQuery += " FROM " + RetSQLTab('Tabela')
cQuery += " WHERE Tabela.Tabela_FILIAL = '" + xFilial('Tabela') + "'" 
cQuery += " AND Tabela.D_E_L_E_T_ = ' ' "
cQuery := ChangeQuery(cQuery)
DbUseArea(.T.,'TOPCONN',TCGENQRY(,,cQuery),cAliasQry,.T.,.T.)
		
/*Condições*/

(cAliasQry)->(DbCloseArea())

Para exemplo, existe o atalho Ctrl+Alt+D - "Adicionar PDoc" do TDS, que gera um cabeçalho padrão para funções.

É possível configurar o TDS ou o VS Code para que um atalho ou comando gere uma estrutura como essa?   

Pergunto pois não sei se o TDS ou o VS Code já fazem isso e eu não conheço, ou se seria uma configuração a se fazer local ou uma implementação a ser feita.

Desde já agradeço.

**Comment by alvarocneto** [comment]
Bom dia. Isso se encaixa no conceito de snippet. Porém sobre esse caso pq vcs não usam o embedded SQL? É mais rápido, mais limpo e terá muita melhorias no futuro como parser interno, prevenção de SQL injection e memo em query.
http://tdn.totvs.com/display/framework/Embedded+SQL

**Comment by izacsc** [comment]
segue os Snippets que eu uso para Embedded Queries: 

```
"Embedded Query": {
        "prefix": "EmbeddedQuery",
        "body": [
            "${cAlias} := GetNextAlias()",
            "",
            "BeginSQL Alias ${cAlias}",
            "\t SELECT ${TAB}.${TAB}_${CAMPO1}",
            "\t   FROM %Table:${TAB}% ${TAB}",
            "\t  WHERE ${TAB}.${TAB}_FILIAL = %XFilial:${TAB}%",
            "\t\tAND ${TAB}.${TAB}_${CAMPO1} = 'VALOR'",
            "\t\tAND ${TAB}.%NotDel%",
            "EndSQL",
            "",
            "While (${cAlias})->(!EoF())",
            "\t$0",
            "\t(${cAlias})->(DbSkip())",
            "End",
            "",
            "(${cAlias})->(DbCloseArea())"
        ],
        "description": " Armazena a próxima area disponível em uma variável"
    },
    "Embedded Query Join": {
        "prefix": "Embedded Query Join",
        "body": [
            "  ${INNER} JOIN %Table:${TAB}% ${TAB}",
            "\t ON ${TAB}.${TAB}_FILIAL   = %XFilial:${TAB}%",
            "\tAND ${TAB}.${TAB}_${CAMPO} = ${TAB2}.${TAB2}_${CAMPO} ",
            "\tAND ${1} ",
            "\tAND ${TAB}.%NotDel%"
        ],
        "description": "Clausula join para uma query de uma tabela no DbAccess"
    }
```

Você deve colocar no seu arquivo de Snippets de ADVPL.  Mais informações sobre snippets: https://code.visualstudio.com/docs/editor/userdefinedsnippets

**Comment by gustavo-krug** [comment]
Muito obrigado @alvarocneto e @izacsc, me ajudaram muito. Valeu

**Comment by gustavo-krug** [comment]
@izacsc sabe se tem como criar um snippets semelhante no TDS? 
Na nossa equipe, só 3 utilizam o VS Code, o restante utiliza o TDS.

**Comment by izacsc** [comment]
Tem sim @gustavo-krug. Mas a sintaxe é diferente. Na versão que eu tenho instalada aqui ( que já é bem velha ). Fica em Janela > Preferências > Developer Studio > AdvPL > Amostras:

![image](https://user-images.githubusercontent.com/423449/49811902-5aa5f400-fd4b-11e8-8b86-f87b3f5d3cd8.png)

**Comment by gustavo-krug** [comment]
Valeu, ajudou muito.
