### ISSUE TITLE
Erro ao compilar - SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by webrsilva** [killerall/advpl-vscode#306]
Prezados,

Ao atualizar o VS Code para versão 1.30 passei a receber o seguinte erro no console:

![image](https://user-images.githubusercontent.com/18246778/49944104-c1a0e580-fed0-11e8-8ead-d1b38c9cf6d9.png)

Esse erro derruba todas as minhas conexões com servidor precisando ter de reiniciar o serviço.
Antes da compilação:

![image](https://user-images.githubusercontent.com/18246778/49944170-fdd44600-fed0-11e8-8659-37ad820f98d2.png)

Depois da compilação:

![image](https://user-images.githubusercontent.com/18246778/49944250-29efc700-fed1-11e8-97f6-4855901a5852.png)

AdvplDebugBridge.log:

Thread[1] - 13/12/2018 12:04:04: Start.

Thread[1] - 13/12/2018 12:04:04: {"selectedEnvironment":"con_dev","enableCoverage":"true","workspaceFolders":"c:\\sistemas\\Microsiga;","environments":[{"smartClientPath":"C:\\win_dev","name":"con_dev","environment":"weberson","includeList":"\\\\server.adm.jamef\\totvs\\protheus\\includes\\","server":"dev-server.srv.jamef","port":"1237","user":"bh35185","passwordCipher":"Y3hlcm93NlRLd2FRMWhrUXRMWXRBeU56UklMT1I5VWU0RE1aL25UcjlINzVYT0NlUkJJQ3RQemgxM0tQTWkzWkc3QlRBSTd0QlJGeStQREx5RDlSakZYU2RTUzB1cXdUSkFQVXB5Y3Y2ZmxDd2xqNFFkYUV6V2prR0I1OTAxTlc="}],"startProgram":"SIGATMS","authorization_generation":"","authorization_validation":"","authorization_permission":"","authorization_code":"","compileFolderRegex":".*\\.(prw|prx|prg|apw|aph|tres|png|bmp|res)","pathPatchBuild":"c:\\patchs\\","debug_multiThread":false,"debug_ignoreSourceNotFound":true,"debug_showTables":true,"debug_showPrivates":false,"debug_showPublic":false,"debug_showStatics":false,"compile_force_recompile":false,"logger":true,"compile_threads":4,"alpha_compile":false}.

Thread[1] - 13/12/2018 12:04:04: Starting MultiThread Compiler with 4 threads..
Thread[1] - 13/12/2018 12:04:04: Last Message.
Thread[1] - 13/12/2018 12:04:04: Last Message:   em advtec.lib_comm.AdvtecConnectionManager.SendMessage(TSendMessage msg)
   em advtec.lib_comm.AdvtecConnectionManager.startBuild(Int32 buildType, Int32 defragRPO, String environment)
   em AdvplDebugBridge.advteclib.compile.AdvplCompileMultiThread.__compileSingle()
   em AdvplDebugBridge.advteclib.compile.AdvplCompileMultiThread.compile()
   em AdvplDebugBridge.Program.InternalMain(String[] argv)
   em AdvplDebugBridge.Program.Main(String[] argv)
MS_DBGSTARTBUILD.
Thread[1] - 13/12/2018 12:04:07: Last Message.
Thread[1] - 13/12/2018 12:04:07: Last Message:   em advtec.lib_comm.AdvtecConnectionManager.SendMessage(TSendMessage msg)
   em AdvplDebugBridge.advteclib.compile.AdvplCompileMultiThread.needCompile(String sourceName, Int64 checksum)
   em AdvplDebugBridge.advteclib.compile.AdvplCompileMultiThread.compileSource(String realSource, String ppoSource, Encoding wind1252)
   em AdvplDebugBridge.advteclib.compile.AdvplCompileMultiThread.__compileSingle()
   em AdvplDebugBridge.advteclib.compile.AdvplCompileMultiThread.compile()
   em AdvplDebugBridge.Program.InternalMain(String[] argv)
   em AdvplDebugBridge.Program.Main(String[] argv)
MS_DBGVALIDCHECKSUM.
Thread[1] - 13/12/2018 12:04:07: Last Message.
Thread[1] - 13/12/2018 12:04:07: Last Message:   em advtec.lib_comm.AdvtecConnectionManager.SendMessage(TSendMessage msg)
   em AdvplDebugBridge.advteclib.compile.AdvplCompileMultiThread.sendSource(String name, Msdatetime msdatetime, TBinaryBuffer tBinaryBuffer, Double chksum)
   em AdvplDebugBridge.advteclib.compile.AdvplCompileMultiThread.compileSource(String realSource, String ppoSource, Encoding wind1252)
   em AdvplDebugBridge.advteclib.compile.AdvplCompileMultiThread.__compileSingle()
   em AdvplDebugBridge.advteclib.compile.AdvplCompileMultiThread.compile()
   em AdvplDebugBridge.Program.InternalMain(String[] argv)
   em AdvplDebugBridge.Program.Main(String[] argv)
MS_DBGCOMPILE.
Thread[1] - 13/12/2018 12:04:08: System.Net.Sockets.SocketException (0x80004005): Foi forçado o cancelamento de uma conexão existente pelo host remoto
   em System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   em advtec.lib_comm.AdvtecConnectionManager.Receive()
   em advtec.lib_comm.AdvtecConnectionManager.InternalManager()
   em advtec.lib_comm.AdvtecConnectionManager.Send(TMessage msg)
   em advtec.lib_comm.AdvtecConnectionManager.SendMessage(TSendMessage msg).

**Comment by killerall** [comment]
O Vscode esta sendo executado em windows ou linux?
Pelo o log não consegui entender o que ocorre.

**Comment by webrsilva** [comment]
Olá,

Vs code está sendo executado no Windows, nosso servidor Protheus que é Linux

**Comment by killerall** [comment]
Parece estar com problema de rede.
No log do server não aparece nada?

**Comment by webrsilva** [comment]
Descobri o erro.

Foi erro de digitação no fonte, estranho que ao digitar esse carácter de forma incorreta no fonte derruba a conexão no servidor e ao tentar compilar no ide antigo o mesmo trava totalmente.

Erro de digitação: lRet :=- .F. ( sinal de menos depois do := )

**Comment by killerall** [comment]
Pode ser a versao do seu appsrv, não consegui reproduzir isso, com as versões que tenho aqui.
