### ISSUE TITLE
Fonte não compila

### ISSUE THREAD

**Issue by atila-advpl** [killerall/advpl-vscode#36]
Segui configuração do meu ambiante.

`

// AdvplSuport configuration

    // Diretorio aonde esta o smartclient.
    "advpl.smartClientPath": "C:\\TOTVS 12\\Microsiga\\Protheus\\bin\\smartclient\\",

  // Versão do server
    "advpl.serverVersion": "131227A",

    // Server IP
    "advpl.server": "localhost",

    // Server Port
    "advpl.port": "5678",

    // Environment
    "advpl.environment": "environment",

    // Usuario com privilegio de Administração para conectar no servidor.
    "advpl.user": "admin",

    // Senha Criptografada do usuario. Utize o commando Cipher Password para gerar a senha.
    "advpl.passwordCipher": "",

    // Diretorios de include para compilação separar cada diretorio com ;
    "advpl.includeList": "C:\\TOTVS 12\\Microsiga\\Protheus\\include",

    // Repository language, Accepted values:PORTUGUESE,ENGLISH,SPANISH
    "advpl.language": "PORTUGUESE",

    // Type of Repository, Accepted values: TOP,CTREE,DBF
    "advpl.rpoType": "CTREE",

    // Programa inicial para o Debug
    "advpl.startProgram": "SIGAADV",
   
    // Regex dos tipos de arquivos que serão compilados quando selecionar compilação de pasta
    "advpl.compileFolderRegex": ".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)",

    // Patch do cliente que deve existir para geracao de patchs. Caso o arquivo ja exista, ser� sobrescrito.
    "advpl.pathPatchBuild": "c:\\patchs\\",
    
    // Habilita Debug multi Thread.
    "advpl.debug_multiThread" : false,

    // Ignorar os fontes não encotrados no debug.
    "advpl.debug_ignoreSourceNotFound": false
}
`

Ao tentar compilar recebo essa mensagem e depois não acontece nada.

Advpl Iniciando
Iniciando compilação do fonte c:\Users\atila.santos\Documents\TDS\Workspace\Pratico\src\zPedMd2.prw

**Comment by killerall** [comment]
Atila,
Boa tarde.

Você não esta conseguindo nenhum fonte ou esse em especifico?
Você gerou a senha para conectar no ambiente?

Att

**Comment by atila-advpl** [comment]
Não estou conseguindo em nenhum fonte a senha que uso é a default  em branco.

Atte.

**Comment by killerall** [comment]
Então, você precisa usar o comando de Cipth, para gerar algo como :
`"advpl.passwordCipher":"dlVTZStUMUN4dGw3MUNyZW1oYlRTVlh0VG5YcnZhRHd6YjhMbS93ajM5bmRZbGJRVGJiUzJCT09kNVlzNzd4eXR0Zi9pcjlJcXhEcWxaekd5MnA0RkdlQUNGQWliSFZKZ2U4L2RQYU1jWDAwWU1CK3JNeDNQVzExaksvc2t1b2I=",`

**Comment by atila-advpl** [comment]
Onde rodo esse comando ?

**Comment by killerall** [comment]
Ctrl+ Shift +P , começa digitando ADVPL, vai estar na lista

**Comment by atila-advpl** [comment]
![image](https://cloud.githubusercontent.com/assets/22686212/20065275/abdcec5e-a4f4-11e6-85a8-e6e2bacaf91f.png)

Gerei a senha e continua do mesmo jeito, acho que pode ser alguma coisa no meu vs code.

**Comment by killerall** [comment]
Faz um teste,

Copia para outra pasta os seus includes, aonde não tenha espaço em branco nos diretórios.

**Comment by atila-advpl** [comment]
continua do mesmo jeito, o SmartClient abre de boa.

**Comment by killerall** [comment]
Acho que consegui reproduzir o seu problema.

Coloque seu a pasta do smartclient aonde não tenha espaço em branco.

Com espaço no diretório tive o mesmo problema que vc.

**Comment by atila-advpl** [comment]
Show!!!! funcionou!!! :+1:

**Comment by Welintonf** [comment]
Tambem estou com esse problema.
Ele diz que compilou, não da nenhum erro, mas olhando o console do server, mostra  
nomedofonte.prw: 0
Ou seja, como se nao tivesse nenhuma linha no fonte.

**Comment by killerall** [comment]
@Welintonf Boa tarde,
Pelo seu log, você esta usando a extensão do TDS, e não do I Love ADVPL.

Melhor abrir sua duvida la.

Att.

**Comment by Welintonf** [comment]
Instalei a sua mas mesmo assim não deu certo.

 

 

 

Att,

Welinton Fernandes

(62) 9 9168-4060  

Skype: welinton.fernandes

welinton@oxtech.com.br <mailto:welinton@oxtech.com.br> 



 

De: Rodrigo Antonio Godinho da Silva <notifications@github.com> 
Enviada em: quarta-feira, 14 de outubro de 2020 15:44
Para: totvs/advpl-vscode <advpl-vscode@noreply.github.com>
Cc: Welintonf <welinton@oxtech.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [totvs/advpl-vscode] Fonte não compila (#36)

 

@Welintonf <https://github.com/Welintonf>  Boa tarde,
Pelo seu log, você esta usando a extensão do TDS, e não do I Love ADVPL.

Melhor abrir sua duvida la.

Att.
