### ISSUE TITLE
Informação no momento de compilação

### ISSUE THREAD

**Issue by j-deodato** [killerall/advpl-vscode#38]
Olá, seria interessante que no visualizador do VsCode, no momento de compilação, fosse mostrado também se a compilação foi realizada ou não. Hoje é necessário observar o server para verificar se foi compilado.

**Comment by killerall** [comment]
No Vscode, essas informações ficam na view OUTPUT. Para abrir basta usar as teclas Ctrl+Shift+U
Ou ir no menu View, Output.

No combo box da direita, escolha ADVPL.

[]s
