### ISSUE TITLE
Ao compilar diz que só o TDS pode rodar

### ISSUE THREAD

**Issue by atila-advpl** [killerall/advpl-vscode#42]
Ao compilar recebo a seguinte mensagem: Erro: ADVPL preprocessor only runs when called by Developer Studio.

**Comment by killerall** [comment]
Atila,

Qual o caminho inteiro  do seu fonte, o caminho do smartcliente?

**Comment by atila-advpl** [comment]
Estou fazendo uma nova configuração em um novo note com windows 10.

Fonte: C:\Users\atila\TOTVS\Piraque\hello.prw

`
{
    "typescript.check.tscVersion": false,

    // AdvplSuport configuration

    // Diretorio aonde esta o smartclient.
    "advpl.smartClientPath": "C:\\TOTVS 12\\Microsiga\\Protheus\\bin\\smartclient\\",

    // Versão do server
    "advpl.serverVersion": "131227A",

    // Server IP
    "advpl.server": "localhost",

    // Server Port
    "advpl.port": "5678",

    // Environment
    "advpl.environment": "environment",

    // Usuario com privilegio de Administração para conectar no servidor.
    "advpl.user": "Admin",

    // Senha Criptografada do usuario. Utize o commando Cipher Password para gerar a senha.
    "advpl.passwordCipher": "NGttd2FqZ0ozang0WmxVWDYrYVJDaWkycktyeXB0K2E4M05uUjkyNzREa3FGRzBvdEhIUVJReGt3SmZKNzJpNFlOemtvaDVMYXQ4NStJb3hxSldnbnlYWmZHU3hBSWNsWWRpemxOMTl0cjhOZGF0RDh2SW9GTzhFWlhUWGJqQ1U=",

    // Diretorios de include para compilação separar cada diretorio com ;
    "advpl.includeList": "C:\\TOTVS 12\\Microsiga\\Protheus\\include\\",

    // Repository language, Accepted values:PORTUGUESE,ENGLISH,SPANISH
    "advpl.language": "PORTUGUESE",

    // Type of Repository, Accepted values: TOP,CTREE,DBF
    "advpl.rpoType": "CTREE",

    // Programa inicial para o Debug
    "advpl.startProgram": "SIGAADV",

    // Regex dos tipos de arquivos que serão compilados quando selecionar compilação de pasta
    "advpl.compileFolderRegex": ".*\\.(prw|prx|apw|aph|tres|png|bmp|tres)",

    // Patch do cliente que deve existir para geracao de patchs. Caso o arquivo ja exista, ser� sobrescrito.
    "advpl.pathPatchBuild": "c:\\patchs\\",

    // Habilita Debug multi Thread.
    "advpl.debug_multiThread": false
}

`

**Comment by atila-advpl** [comment]
Vou testar quando chegar em casa, mas acho que tem algum arquivo faltando no meu diretório smartclient, pois o tds reclamou tbm.

**Comment by killerall** [comment]
Teste com a ultima versão que liberei a pouco.

**Comment by atila-advpl** [comment]
Funcionou!!!
