### ISSUE TITLE
Warnings estão sendo exibidos como erro no output

### ISSUE THREAD

**Issue by j-deodato** [killerall/advpl-vscode#43]
Olá, os Warnings gerados na compilação estão sendo exibidos como erro:
Erro: 
MPSYSOPENTABLES.PRW(498) warning W0010 Static Function GETMENUSTRUCT never called
MPSYSOPENTABLES.PRW(38) warning W0003 Local variable LCONTINUE never used
Compilação OK

**Comment by rhcalheiros79** [comment]
Boa tarde j-deodato.
Estou tendo este problema também, por acaso você encontrou solução? Caso sim, poderia compartilhar?

**Comment by killerall** [comment]
Boa tarde.
Esse problema foi corrigdo em Nov de 2016.

Você consegue anexar um print do seu erro?

**Comment by rhcalheiros79** [comment]
Boa tarde Rodrigo.
Segue aqui o erro, vale dizer que trabalho com o Protheus 11 em produção e
tenho o Protheus 12 na base TESTE, e é justamente na Protheus 12 que dá
esse erro...
[image: Imagem inline 1]

Desde já agradeço sua atenção e colaboração.

Ricardo Calheiros
(43)99110-7822
(43) 3348-5510

2017-07-28 14:53 GMT-03:00 Rodrigo Antonio Godinho da Silva <
notifications@github.com>:

**Comment by killerall** [comment]
Não esta aparecendo a imagem.

**Comment by rhcalheiros79** [comment]
Olá Rodrigo.
Segue o erro, agora como anexo...

Ricardo Calheiros
(41)3538-7763
(41)9717-4238

2017-07-28 16:09 GMT-03:00 Rodrigo Antonio Godinho da Silva <
notifications@github.com>:

**Comment by killerall** [comment]
Ainda não aparece aqui.

**Comment by rhcalheiros79** [comment]
Me perdoe, eu estava mandando por e-mail acreditando que você receberia por e-mail e não aqui, vamos ver se foi agora.
Ps: Sou novato por aqui....
![image](https://user-images.githubusercontent.com/26253929/28733809-2e4fc452-73b4-11e7-8a0d-0abe1eee9311.png)

**Comment by killerall** [comment]
Opa sem problema, veio a imagem do DevStudio antigo, não do vscode.

**Comment by rhcalheiros79** [comment]
No Protheus 12 devo utilizar outro Ambiente Studio?

**Comment by killerall** [comment]
Esse repositório é de uma IDE diferente, o VsCode(https://code.visualstudio.com/), onde foi feito o suporte para a linguagem Advpl.
De qualquer maneira, este ide que você utilizando já é descontinuado também pela Totvs.
Caso queira utilizar a ferramenta da Totvs, use o TDS(http://ds.totvs.com/).
Abs
