### ISSUE TITLE
Não é possível passar parâmetros ao lançar o smartclient, seja no debug ou seja na opção launch normal.

### ISSUE THREAD

**Issue by izacsc** [killerall/advpl-vscode#50]
![image](https://cloud.githubusercontent.com/assets/423449/21052817/f867cf58-be0d-11e6-86e1-b52c6f00ff60.png)

![image](https://cloud.githubusercontent.com/assets/423449/21052834/04c18fa0-be0e-11e6-9a26-713c90538baa.png)

**Comment by eternauta123** [comment]
@killerall pode passar link para documentacao de como passar parametros (-a)?

**Comment by killerall** [comment]
@eternauta123 
Você pode usar como o IZac mesmo.
Funcao("Param1","param2)
Eles entram como se fosse -a do smartclient.

**Comment by eternauta123** [comment]
sigabpm(5,"DEMO100") ou sigabpm("5","DEMO100") nao funcionam (estes dois parametros sao passados com -A

**Comment by dougtelles** [comment]
@eternauta123, você conseguiu executar o SmartClient passando parâmetros "-a", "-p"?
Estou ajustando alguns desenvolvimentos feitos no TOTVS PDV e não consigo incluir o parâmetro da estação ("-a").

**Comment by eternauta123** [comment]
Sim @dougtelles como indicado sigabpm(5,”u_xxx”), só não lembro se os parâmetros tem aspas ou não

**Comment by dougtelles** [comment]
Boa noite, consegui executar. A diferença é que não sei se é uma falha mas no atalho do TOTVS PDV é preciso colocar duas vezes o parâmetro "-a", testando da mesma forma funcionou.

Usei da seguinte forma: sigafrt(-a= -a=002)

Antes de conseguir executar dessa forma, eu consegui contornar usando o debug de múltiplas threads.

De qualquer forma, obrigado!
