### ISSUE TITLE
Patchs

### ISSUE THREAD

**Issue by killerall** [killerall/advpl-vscode#52]
A aplicação e geração de patchs estão apresentando problemas, e quando não aplica não da retorno.

**Comment by JoseCamilo** [comment]
Boa tarde Godinho, Precisa de alguma configuração para aplicar patchs?
Segue print do erro:
![image](https://user-images.githubusercontent.com/19961076/27050561-5a5adc7a-4f89-11e7-9ba2-dbce1c0eec64.png)

**Comment by killerall** [comment]
Para aplicar estar conseguindo conectar. No server. E ser admin.

**Comment by JoseCamilo** [comment]
o meu ambiente chama "CRM", na print mostra que está conectado no momento do erro e sou admin.
Eu apliquei o mesmo patch pelo TDS.
