### ISSUE TITLE
Comentários em linhas quebradas com ; geram erro de sintaxe e não compila

### ISSUE THREAD

**Issue by josimar-jr** [killerall/advpl-vscode#53]
Colocar os comandos para comentário /**/ e // em sequência numa linha quebrada com ; gera o erro de sintaxe.

> Iniciando compilação do fonte c:\TFS\Protheus_Padrao\Fontes_Doc\Inovação\V12\Serviços GS - R15\Fontes\users\new2.prw
Erro: appre1(8) Error C2002  Statement unterminated at end of line/unbalanced parentesis/brackets

> user function new2()
Local a := 0
func1( a,;
        a,;
        a,; /**/ // << linha gera o erro de compilação
        a;
        )
return

[new2.zip](https://github.com/killerall/advpl-vscode/files/658296/new2.zip)

**Comment by killerall** [comment]
Josimar,

O fonte realmente está errado.

O TDS tambem da o mesmo erro.

niciando processo de compilação às 10:04:10.
Estabelecendo conexão com o servidor [localhost] e ambiente [P12]...

Compilando arquivo teste4.prw...

 Error C2002  Statement unterminated at end of line/unbalanced parentesis/brackets
ADVPL Preprocessor.Precompilation of file C:\Users\Rodrigo\Documents\TDS\Workspace\Novo_Projeto\src\teste4.prw with error. Exitecode equal to 1

Compilação finalizada.

Abs
