### ISSUE TITLE
advpl.includelist não é identificado como uma configuração válida.

### ISSUE THREAD

**Issue by izacsc** [killerall/advpl-vscode#55]
Atualizei hoje e o seguinte warning passou a aparecer:

![image](https://cloud.githubusercontent.com/assets/423449/21328396/deed4f5c-c61a-11e6-96f2-c25d96ff1d83.png)

**Comment by killerall** [comment]
A partir da versão 0.4.0, com a introdução de multi ambientes, essa configuração é feita por ambiente, e não mais global.

Da olha olhada na wiki:

https://github.com/killerall/advpl-vscode/wiki/Configura%C3%A7%C3%A3o

Att
