### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by ribeiry** [killerall/advpl-vscode#59]
Ao dar errro o smartClient cai , porem o Modo Debug no VsCode continua aberto

**Comment by killerall** [comment]
@ribeiry  Você consegue detalhar mais um pouco o que você fez, e o que aconteceu?

Obrigado

**Comment by ribeiry** [comment]
@killerall  quando esta debugando , e por acontece um erro que finaliza o smartClient , no tds ele sai do modo debug e gera o log, no VSCode ele continua como se "Houvesse" em debug ainda...

**Comment by killerall** [comment]
Na verdade isso foi feito para ser assim.
O Debug se comporta da mesma maneira de qualquer outra linguagem. O stack fica parado aonde ocorreu a exception. (Note do lado esquerdo, aonde tem o callstack fica em vermelho).
Quando você finaliza o Debug, o stack é impresso no output ADVPL, igual ao TDS.

Na verdade o TDS que não deveria sair do modo debug. Faça um teste debugando com o eclipse com java, e ele fica parado na exception até o programador parar o debug.

Abs
