### ISSUE TITLE
Histórico de procuras (Ctrl + F) [sugestão]

### ISSUE THREAD

**Issue by sousa96** [killerall/advpl-vscode#60]
Formalizar uma listbox ao dar Ctrl+F para procurar uma string no fonte, onde essa combo traga o histórico das 10 últimas strings buscadas pelo usuário. As strings buscadas pelo usuário no fonte podem ser armazenadas num arquivo temporário e quando o fonte é fechado (removido da aba Open Editors) o temporário pode ser deletado.

[]s

**Comment by killerall** [comment]
Sousas,

Boa tarde.

A parte que faz a pesquisa é inerente ao próprio vscode. Não da extensão de advpl.

Abra uma melhora no projeto do vscode, quem sabe eles não fazem para gente.
:D
