### ISSUE TITLE
Adicionar campos das tabelas no Debug [sugestão]

### ISSUE THREAD

**Issue by sousa96** [killerall/advpl-vscode#61]
Boa tarde,

Pensei na possibilidade de mostrar os campos e os índices das tabelas em aberto no momento do debug junto com o seu conteúdo.
Exemplo:
SA1>

SA1(aberta)
A1_COD: "001"
A1_LOJA: "01"

Bastaria clicar duas vezes na tabela para abrir os índices, os campos e o seu conteúdo atualizado.

[]s

**Comment by killerall** [comment]
Boa tarde Sousa.

Isso já possível, basta habilitar na configuração 

// Mostra as tabelas abertas.
  "advpl.debug_showTables": true,

Obrigado.

**Comment by sousa96** [comment]
Certo, dessa forma as tabelas aparecem no debug, mas ainda não encontrei uma forma prática de ver os índices da tabela, os campos e o conteúdo atual do campo... isso já é possível?

**Comment by killerall** [comment]
Hoje ele mostra as tabelas, e mostra o indice selecionado. Para mostrar cada conteudo precisa ser feito. Vou reabrir a sua issue.

**Comment by sousa96** [comment]
Obrigado!

[]s
