### ISSUE TITLE
Geração de Patch

### ISSUE THREAD

**Issue by ribeiry** [killerall/advpl-vscode#68]
Ao gerar a patch ele esta criando em branco

**Comment by killerall** [comment]
Você consegue detalhar melhor como você está fazendo?

Você seguiu o passos daqui:

https://github.com/killerall/advpl-vscode/wiki/Trabalhando-com-Patchs

**Comment by izacsc** [comment]
Opa, tudo bom? Eu consegui aplicar normalmente o patch, mas pra mim apareceu um erro no Patch Info.


[FATAL][SERVER] [Thread 9300] [THROW] Incompatible RPO file (_APOERROR_100_). Please check binary version. at file C:\bamboo-agent-5.7.2\xml-data\build-dir\TP11-BUILDV2APPSRV-TEC11WIN32RPO32\advtec9_tt11\advpl\ivstream.cpp line 2007

**Comment by ribeiry** [comment]
Criei o arquivo  de fontes para serem gerados as Patch, dei um Set no Arquivo e pedi para Gerar a Patch , e ele cria na pasta do config em branco

**Comment by killerall** [comment]
Copia o json das configurações aqui.
Eu gerei com sucesso aqui.
Lembrando que o fonte tem que estar com a extensão no arquivo txt.

**Comment by ribeiry** [comment]
[.vscode.zip](https://github.com/killerall/advpl-vscode/files/764797/default.vscode.zip)

**Comment by ribeiry** [comment]
atualizei os binarios e agora gerou a patch correto, conversei com o @alvarocneto  para ver os procedimentos e estavam corretos.
