### ISSUE TITLE
Setar file.encoding somente para arquivo advpl

### ISSUE THREAD

**Issue by vicenthy** [killerall/advpl-vscode#69]
tem como configurar o file.encoding somente para as extensão do advpl? não encontrei nada no github do vscode.

**Comment by killerall** [comment]
O que você pode fazer é colocar na WorkSpace, ai apenas na workspace que você trabalha com advpl vai setar.

Agora se você trabalhar na mesma pasta com outras linguagens, ai não sei como fazer.

**Comment by alvarocneto** [comment]
Se você clicar no lado inferior direito você pode trocar o enconding de um arquivo individualmente

![image](https://cloud.githubusercontent.com/assets/17092119/22910371/a109b28c-f240-11e6-856a-81bd37919651.png)

![image](https://cloud.githubusercontent.com/assets/17092119/22910373/aa0b04f8-f240-11e6-87dc-84b14b2b08a7.png)

**Comment by izacsc** [comment]
No arquivo de settings vc pode colocar a configuração default encoding de abertura de arquivos:

 `"files.encoding": "windows1252"`   

Existem sim algumas configurações por linguagem, mas o encoding não está nelas.

Abraço

**Comment by vicenthy** [comment]
Obrigado, vou utilizar a troca individual mesmo. É que uso o vs pra abrir meus fontes e sempre que vou copiar pro TDS da problema. 
Acredito que esse projeto é muito promissor não sei como ainda não tem insentivo de forma oficial dá TOTVS.
