### ISSUE TITLE
VsCode congela ao compilar um determinado fonte

### ISSUE THREAD

**Issue by josimar-jr** [killerall/advpl-vscode#70]
Ao compilar um fonte específico do padrão o vscode congela e uma janela é exibida (conforme primeira imagem), ao selecionar a opção para aguardar continua congelado e não volta a ficar disponível para edição.

O fonte é compilado (conforme segunda imagem). Como o fonte é do padrão não vou publicá-lo aqui, mas estou disponível para enviá-lo via email para análise.

primeira imagem
![image](https://cloud.githubusercontent.com/assets/21246337/23141471/b8903a0c-f795-11e6-93bf-aeb947cdf7e1.png)

segunda imagem
![image](https://cloud.githubusercontent.com/assets/21246337/23141773/31031cf6-f797-11e6-9807-ffb4cc9c7dd8.png)

**Comment by killerall** [comment]
Opa, me passa so o nome do fonte.

**Comment by killerall** [comment]
Corrigido na versao 0.5.1
