### ISSUE TITLE
Erro na execução do Smartclient 

### ISSUE THREAD

**Issue by fbhanimal** [killerall/advpl-vscode#72]
Esta dando a seguinte mensagem de erro na execução do smartclient depois da atualização para a 10.1.

![image](https://cloud.githubusercontent.com/assets/26173016/23567005/1162a4b2-0033-11e7-826e-6501d3b7b113.png)

Grato,
Erich Buttner

**Comment by killerall** [comment]
Erich,
Boa tarde

Apague o arquivo launch dentro do vscode. e mande rodar novamente para criar novamente.

Certifique-se que o vscode foi para 1.10.1 e o advpl para -0.5.4

**Comment by fbhanimal** [comment]
apaguei o arquivo launch.json e funcionou perfeitamente.
Muito obrigado,

**Comment by killerall** [comment]
De nada
