### ISSUE TITLE
Debug 

### ISSUE THREAD

**Issue by fbhanimal** [killerall/advpl-vscode#73]
Bom dia,

Tem alguns ambientes que tento debugar porem apresenta a mensagem abaixo:

![image](https://cloud.githubusercontent.com/assets/26173016/23657057/136b8810-031b-11e7-940f-9555d259be1f.png)

o usuário e senha esta correto.
Existe alguma configuração a ser efetuada no appserver ou no VSCode?

Grato,
Erich buttner

**Comment by killerall** [comment]
Bom dia,

Tentar gerar novamente a senha no  CipherPassword

**Comment by fbhanimal** [comment]
Gerei novamente, porem a mesma mensagem. Como é feita a comunicação com o servidor? pode ser algum firewall bloqueando a comunicação ?

Grato,
Erich Buttner

**Comment by killerall** [comment]
É feita via TCP.

Se você consegue acessar via SmartClient deveria acessar via vscode.

Verifique se o ambiente não tem Trava de acesso ao TDS no ini.

**Comment by fbhanimal** [comment]
Te passei um e-mail com o servidor que estou tentando conexão. Esta mensagem apresentava no TDS 11.3 tambem, mas depois de uma atualização não apresentou mais esta mensagem.

**Comment by izacsc** [comment]
Eu me deparei com esse problema e pra mim era o seguinte.

Eu alterei um ambiente para um novo nome, mas o WorkSpace Settings ficou guardado o nome do ambiente antigo que não existia mais. Toda vez que ia debugar parava de funcionar. Corrigi apagando o workspace setting e tudo voltou a funcionar.

Espero que ajude.

Abraço
