### ISSUE TITLE
Recompilação de fontes [melhoria]

### ISSUE THREAD

**Issue by sousa96** [killerall/advpl-vscode#77]
Boa tarde,

Sugestão de Implementação: Opção de recompilar os fontes de uma pasta no VS Code.

Às vezes surge a necessidade de atualizar a data de modificação do fonte e hoje isso só é possível alterando alguma linha do fonte para que ele seja compilado de fato, porém se houver muitos fontes que por exemplo farão parte de uma patch, isso se torna trabalhoso.

[]s

**Comment by killerall** [comment]
Boa tarde,

Na verdade no VSCODE ele sempre compila como Recompilação.

O que estávamos fazendo é dar as duas opções igual no TDS. Compilar (que compila apenas se o fonte sofreu modificação) ou recompilar, que força.

Abs

**Comment by sousa96** [comment]
Entendido. 
Bom, a ideia é exatamente essa... Então, essa opção estará no próximo release?

Obrigado
