### ISSUE TITLE
Mac(osx) >cipher 

### ISSUE THREAD

**Issue by rodrigomagalha** [killerall/advpl-vscode#78]
Estou digitando o comando, abre o input mas o VsCode nao apresenta a senha criptografada.

OS Sierra 10.12.3
Visual Code 1.10.2
advpl-vscode 0.5.4

Obrigado

**Comment by killerall** [comment]
Rodrigo,

Boa tarde.

Eu refiz a geração em MAC, na versão 0.5.7 vou liberar ela.

Nos testes usei a mesma versao do OS.

**Comment by rodrigomagalha** [comment]
Opa, Obrigado, fico no aguardo...

**Comment by rodrigomagalha** [comment]
Quando vai liberar a versao 0.5.7?
Obrigado

**Comment by killerall** [comment]
Não tenho ideia ainda.

Estou fazendo uma ultima tentativa com o MACOS e com o Linux usando o Mono. Pois o Bridge eu construí em C#.

Caso não consiga ter a performance bacana, terei que partir para desenvolver todo o Bridge novamente em C++, que o multi plataforma fica muito mais fácil.

Mais aviso quando decidir.

**Comment by rodrigomagalha** [comment]
Opa, obrigado pela resposta rapida... Fico no aguardo. (sem pressão) ehhehe...

**Comment by gbpucci** [comment]
Vou testar no meu Mac em casa e depois posto o resultado !! Parabéns pelo trabalho !!

**Comment by afucher** [comment]
Escrever em .Net core não seria uma opção?

**Comment by killerall** [comment]
Já tentei fazer o Port para .net core, porem a biblioteca de rede muda muita coisa.
So for reescrever acho que devo ir para C++ mesmo.

**Comment by rodrigopg** [comment]
Tudo bem amigos?

Parabéns pelo trabalho, realmente muito bom.
Quero deixar minha consideração e incentivo sobre o desenvolvimento do Port para o MacOS

Imagino que esteja cheio de trabalho, mas peço que não se esqueça de nós. MacManiacos ! 

Grato! 👍

**Comment by killerall** [comment]
Versão mac e linux liberada na versao 0.9.0.
