### ISSUE TITLE
Problema ao compilar após atualização 0.5.5

### ISSUE THREAD

**Issue by guiebitt** [killerall/advpl-vscode#79]
Bom dia,

Após atualizar o plugin para 0.5.5, não consigo mais realizar a compilação de nenhum fonte ou diretório.
Existe algum detalhe que foi incluído e eu preciso ajustar nas configurações?

Simplesmente aparece da seguinte forma no OUTPUT:

**Advpl Iniciando
Iniciando compilação do fonte <NOME DO PROGRAMA>.PRW

Compile Start at Mon Mar 27 2017 09:29:04 GMT-0300 (Hora oficial do Brasil)**

E no Console:

**[INFO ][SERVER] [Thread 10108] [27/03/2017 09:29:05] Starting Debugger (<USUÁRIO, MÁQUINA>)

[INFO ][SERVER] [Thread 10108] [27/03/2017 09:29:05] Debugger finished (<USUÁRIO, MÁQUINA>)**

Obrigado.

**Comment by killerall** [comment]
Bom dia,

Não teria que alterar nada.

Tenta gerar o Cipher novamente para o ambiente.
E faça um teste.

Tente tambem remover o arquivo state.bin da pasta da instalação da extensão:
C:\Users\Nomedo usuario \.vscode\extensions\KillerAll.advpl-vscode-0.5.5\bin

**Comment by guiebitt** [comment]
Oi, obrigado pela rápida resposta,

Removendo o arquivo state.bin, ao tentar realizar a compilação, funcionou perfeitamente. Porém, após o arquivo estar criado e eu tentar compilar novamente, não compila mais e preciso novamente remover o arquivo state.bin.

Estou utilizando o plugin a alguns meses e somente agora começou a apresentar esta situação.

Att,

**Comment by killerall** [comment]
Em algumas maquinas está dando isso, já estou verificando uma solução.
Obrigado.

**Comment by killerall** [comment]
Ja atualizei o VSCODE, por favor atualize a sua versão, apague o .state a ultima vez e deve estar ok.

Obrigado.

**Comment by guiebitt** [comment]
Obrigado! Está funcionando normalmente!

Att,
