### ISSUE TITLE
Cipher - Senha de usuário

### ISSUE THREAD

**Issue by robsonolivesa** [killerall/advpl-vscode#83]
Pode explicar melhor sobre o processo de encriptar a senha? Não entendi onde eu rodo o comando. É no próprio Visual Studio ou é uma ferramenta externa?

**Comment by afucher** [comment]
@robsonolivesa o comando é dentro do próprio VSCode, basta pressionar F1 e achar o comando `CipherPassword`

**Comment by robsonolivesa** [comment]
ótimo, consegui! Obrigado.
