### ISSUE TITLE
Patch em rpo TTTS

### ISSUE THREAD

**Issue by igor-sousa** [killerall/advpl-vscode#84]
Boa tarde,

Ao gerar uma patch com Rpo em espanhol, o VS Code não encontra o arquivo .ptm na pasta \\Temp para mover para a pasta escolhida para geração de patchs (pathPatchBuild), retornando um erro na output:
"N�o foi poss�vel localizar uma parte do caminho 'C:\\Users\\igor.nascimento\\AppData\\Local\\Temp\\'.\r\n"

No server é possível verificar que os fontes escolhidos para geração do patch foram compilados, e na pasta \\Temp o arquivo .ptm foi gerado normalmente. 

Qualquer dúvida me procure.

Abs,

**Comment by kleestadt** [comment]
Boa tarde @igornascimentodvl estou com esse problema, você conseguiu resolver?

**Comment by killerall** [comment]
Ser for em espanhol já vi qual é o problema, ainda não consegui gerar uma versão com a correção mais em breve devo faze-lo.

**Comment by kleestadt** [comment]
@killerall obrigado pelo retorno, é isso mesmo, v11 espanhol, o . ptm fica na pasta Temp, ficamos no aguardo então, muito obrigado novamente, abç.

**Comment by jacksjm** [comment]
Boa tarde.

Ocorreu o mesmo problema para mim só que o meu ambiente é em Português.

**Comment by killerall** [comment]
A atualização lançada semana passada resolveu esta questão.
Consegue detalhar melhor o que ocorre?

**Comment by jacksjm** [comment]
Verifiquei e a versão da extensão em minha máquina é a 0.5.10, vi que na 0.5.9 estava a correção associada a esta Issue, contudo apresenta a seguinte mensagem na geração do pacote:
{"Line":1,"Column":0,"Type":0,"Message":"Error ao gerar o patch.System.IO.FileNotFoundException: N�o foi poss�vel localizar o arquivo 'C:\\Users\\jackson.machado\\AppData\\Local\\Temp\\ttdp110.ptm'.\r\nNome do arquivo: 'C:\\Users\\jackson.machado\\AppData\\Local\\Temp\\ttdp110.ptm'\r\n   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   em System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)\r\n   em System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)\r\n   em advtec.patch.PatchManager.Build(String[] sources)"}

**Comment by killerall** [comment]
Seu ambiente é DBF.
Verifica se na setting do vscode, você definiu o rpoType para DBF.

**Comment by jacksjm** [comment]
na verdade meu RPO é TOP.

Forcei o rpoType como TOP e DBF e mesmo assim ocorre o problema.

**Comment by killerall** [comment]
Pelo arquivo que ele procura, ttdp110
O ambiente deve ser Versao 11, DBF e Portugues.
Caso não bata a cfg com o que esta no ini do prothues vai dar problema.

**Comment by jacksjm** [comment]
Então, meu ambiente é sim TOP e as configurações do .ini estão corretas para o ambiente, tanto que o pacote que ele gera no Temp é o tttp110, porém para jogar na pasta definida no pathPatchBuild ele está procurando pelo ttdp110.
O mesmo problema ocorre nos ambientes da 12.1.7, 12.1.14, 12.1.16 e na 12.1.17.

**Comment by kleestadt** [comment]
Bom dia a todos, 

Como devo proceder para instalar a versão mais recente da extensão? No aguardo.

**Comment by killerall** [comment]
O visual code instala os udpates automaticamente, bastando reiniciar o mesmo.

**Comment by jacksjm** [comment]
boa tarde!

verifiquei que o problema está ocorrendo em várias máquinas e começou aparentemente após alguma atualização pois todos mencionam que estava funcionando normalmente.

**Comment by killerall** [comment]
Boa tarde
Por favor, anexe o ini do seu server , e o settings do vscode. 
Pois não estou consegui reproduzir.

**Comment by brluni** [comment]
Boa tarde,

Estou tendo o mesmo problema, como a atualização é automática, não consigo informar com precisão se foi alguma atualização que gerou o problema.
o que apresente no erro é que não encontra o arquivo ttdp120.ptm, o que está correto, pois o arquivo gerado é tttp120.ptm, e é justamente o que eu preciso que gere afinal meu ambiente é TOP.
Não alterei nenhuma configuração e até semana passada conseguia gerar o pacote normalmente.

Vale ainda ressaltar que a patch é gerada e fica em uma pasta temporária, consigo aplicar e verificar o conteúdo da patch normalmente, porém me parece que o problema está em mover a patch da pasta temporária para a paste definida nas configurações do vscode, acredito que justamente por buscar por ttdp e o arquivo ser tttp.

Grato.

**Comment by jacksjm** [comment]
Segue meu .ini.

[appserver_bkp.zip](https://github.com/killerall/advpl-vscode/files/1131814/appserver_bkp.zip)

**Comment by jacksjm** [comment]
Desculpe, o settings acabou não indo junto. Segue anexo
[settings.zip](https://github.com/killerall/advpl-vscode/files/1131880/settings.zip)
.

**Comment by jacksjm** [comment]
boa tarde! com o envio do .ini e do settings foi efetivo?

**Comment by jacksjm** [comment]
boa tarde! verifiquei no .ini a tag RpoDB e estava com SQL, troquei para TOP e funcionou corretamente! Obrigado!
