### ISSUE TITLE
Problemas de compilação e debug após versão 0.5.8

### ISSUE THREAD

**Issue by brluni** [killerall/advpl-vscode#87]
Boa tarde,

Estou utilizando o VSCode a pouco mais de uma semana, a extensão advpl é muito boa, porém hoje, após a atualização para a versão 0.5.8 ocorreu um erro ao efetuar o debug e parou de funcionar, não consigo compilar, debugar ou executar alguns comando como ">cipher". 
Desinstalei e reinstalei varias vezes, não sei onde ficam salvas as configurações, mas sempre que abro o VSCode após ter instalado novamente minas configurações já estão lá, efetuei a desinstalação inclusive usando Revo Uninstaller, porém não tive sucesso em nenhuma de minhas investidas. 
Ao tentar compilar em uma das vezes apresentou o seguinte erro: "settings.json C:\Users\bruno.souza\AppData\Roaming\Code\User
Value expected (32,9)"

desde já agradeço.

Att;
Bruno Lobo de Souza

**Comment by brluni** [comment]
O erro que mencionei foi por conta de ter comentado o "passwordCipher", porém continua sem compilar ou debugar.

**Comment by killerall** [comment]
Boa tarde,

Por favor anexe seu settigns.json.
Valeu

**Comment by brluni** [comment]
Boa tarde,

Consegui desinstalar e instalar novamente, compilou, porém ao executar o debug trava e não compila mais.
Tentei então desinstalar e instalar na partição "C:" porém não consigo adicionar a extensão, preciso fechar o VSCode e adicionar a extensão novamente, aparentemente instala, porém nada funciona, nem mesmo os comandos como ">cipher" por exemplo.

Segue o settings:
// Place your settings in this file to overwrite the default settings
{
    "editor.minimap.enabled": true,
    "files.encoding": "windows1252",
    "mssql.connections": [
        {
            "server": "NG013-PC\\SQLEXPRESS",
            "database": "",
            "authenticationType": "SqlLogin",
            "user": "sa",
            "password": "",
            "savePassword": true
        }
    ],
    // Patch do cliente que deve existir para geracao de patchs. Caso o arquivo ja exista, será sobrescrito.
    "advpl.pathPatchBuild": "D:\\Totvs\\Patch\\",
    // Habilita Debug multi Thread.
    "advpl.debug_multiThread": true,
    // Mostra as variaveis Privates.
    "advpl.debug_showPrivates": true,
    // Ignorar os fontes não encotrados no debug.
    "advpl.debug_ignoreSourceNotFound": true,
    "advpl.environments":[
        {
        "smartClientPath": "D:\\Totvs\\Protheus\\bin\\smartclient\\",
        "environment": "P12116",
        "includeList": "D:\\Totvs\\Protheus\\include\\",
        "server": "localhost",
        "port": "12380",
        "user": "admin",
        "passwordCipher": "dUt3M0dCeGptMVFHZlBUOUgySUUrYzJ0a2xrYjRSZ2dQbjJTQ0VjaE9vM0NPbEpxNU1Rd1dtTisxREkwRzF0WWdmcG4ySjJrUm1ONlJjQ0xiSEdCaGoyVWpsd0ZtdlRXWWNrbEIzdU82blJ6RUJXOFNuZTAwR2FZMjhpamRwdU4="
        },
        {
        "smartClientPath": "D:\\Totvs\\Protheus\\bin\\smartclient\\",
        "environment": "P12114",
        "includeList": "D:\\Totvs\\Protheus\\include\\",
        "server": "localhost",
        "port": "12380",
        "user": "Admin",
        "passwordCipher": "dUt3M0dCeGptMVFHZlBUOUgySUUrYzJ0a2xrYjRSZ2dQbjJTQ0VjaE9vM0NPbEpxNU1Rd1dtTisxREkwRzF0WWdmcG4ySjJrUm1ONlJjQ0xiSEdCaGoyVWpsd0ZtdlRXWWNrbEIzdU82blJ6RUJXOFNuZTAwR2FZMjhpamRwdU4="
        },
        {
        "smartClientPath": "D:\\Totvs\\Protheus\\bin\\smartclient\\",
        "environment": "P1217",
        "includeList": "D:\\Totvs\\Protheus\\include\\",
        "server": "localhost",
        "port": "12380",
        "user": "Admin",
        "passwordCipher": "dUt3M0dCeGptMVFHZlBUOUgySUUrYzJ0a2xrYjRSZ2dQbjJTQ0VjaE9vM0NPbEpxNU1Rd1dtTisxREkwRzF0WWdmcG4ySjJrUm1ONlJjQ0xiSEdCaGoyVWpsd0ZtdlRXWWNrbEIzdU82blJ6RUJXOFNuZTAwR2FZMjhpamRwdU4="
        },
        {
        "smartClientPath": "D:\\NGAP11\\bin\\smartclient\\",
        "environment": "P118COM",
        "includeList": "D:\\NGAP11\\include\\",
        "server": "localhost",
        "port": "1045",
        "user": "Admin",
        "passwordCipher": "dUt3M0dCeGptMVFHZlBUOUgySUUrYzJ0a2xrYjRSZ2dQbjJTQ0VjaE9vM0NPbEpxNU1Rd1dtTisxREkwRzF0WWdmcG4ySjJrUm1ONlJjQ0xiSEdCaGoyVWpsd0ZtdlRXWWNrbEIzdU82blJ6RUJXOFNuZTAwR2FZMjhpamRwdU4="
        }
    ],
    "advpl.selectedEnvironment": "P12116",
    //Módulo ou função que será sugerido no launch do Debug
    "advpl.startProgram": "SIGAMDI",
    //Data de geração da chave no formato yyyyMMdd
    "advpl.authorization_generation": "20170518",
    // Data de validade da chave no formato yyyymmdd
    "advpl.authorization_validation": "20170815",
    // 1 - Para permitir substiuir fontes TOTVS, 0 para Não
    "advpl.authorization_permission": "1",
    // Chave de compilação
    "advpl.authorization_code": "046SCY030ESEE0001DB671266",
    "editor.detectIndentation": false,
	"editor.insertSpaces": false,
	"files.trimTrailingWhitespace": true
}

Grato.

**Comment by killerall** [comment]
Faça um teste, vai pasta:
C:\Users\seuusuario.vscode\extensions\KillerAll.advpl-vscode-0.5.8\bin
e rode o AdvplDebugBridge (faça isso no cmd do windows).

Veja se ele fica uma tela preta, ou se da alguma mensagem.
Aproveite e remova as versoes antigas da pasta:

C:\Users\rodrigo.antonio\.vscode\extensions\

**Comment by brluni** [comment]
Como havia desinstalado o VSCode e instalado novamente, ao adicionar a extensão advpl, ficou carregando e não instalou, fechei o VSCode e tentei novamente instalar a extensão, aparentemente instalou, porém não consigo executar o comando ">cipher" para gerar minha senha criptografada.

Sobre o AdvplDebugBridge, na pasta existe somente o AdvplDebugBridgeMac, seria esse mesmo?
A extensão pode ter corrompido por conta de ter fechado o VS e tentado novamente?
ressaltando que sempre ocorre a mesma situação, não consigo adicionar a extensão de "primeira", necessitando fechar o code e abrir novamente para efetuar a instalação.

grato pelo apoio.

**Comment by killerall** [comment]
Pode ser alguma coisa relacionada a AntiVirus.
Tente remover tudo da pasta
C:\Users\rodrigo.antonio.vscode\extensions\
e remover o vscode e reintalar o mesmo.

**Comment by brluni** [comment]
Infelizmente já fiz isso mais de uma vez.
agora que mencionou acredito que possa ser o AntiVirus mesmo.
Obrigado vou ver o que consigo por aqui.

**Comment by brluni** [comment]
Obrigado pelo apoio, era realmente o antivirus.
Tanto trabalho e era o mais simples.

Obrigado pelo apoio.

**Comment by killerall** [comment]
Blz, estou fechando a issue.

Vlw
