### ISSUE TITLE
Problema ao tentar gerar Patch Protheus ADVPL

### ISSUE THREAD

**Issue by kleestadt** [killerall/advpl-vscode#92]
Boa tarde, se alguém puder me ajudar com o problema abaixo eu agradeço.

{"Line":1,"Column":0,"Type":0,"Message":"Error ao gerar o patch.System.IO.DirectoryNotFoundException: N�o foi poss�vel localizar uma parte do caminho 'C:\\Users\\rafael.kleestadt\\AppData\\Local\\Temp\\'.\r\n   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   em System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)\r\n   em System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)\r\n   em advtec.patch.PatchManager.Build(String[] sources)"}

**Comment by killerall** [comment]
Boa tarde,

Você está tentando gerar o patch em que lingua e que banco?

**Comment by kleestadt** [comment]
@killerall Espanhol, SQL, v11 o .PTM fica na pasta Temp, aguardamos a correção assim que possível então, muito obrigado.
