### ISSUE TITLE
Auxílio na configuração para compilação

### ISSUE THREAD

**Issue by AlexandreFelix** [killerall/advpl-vscode#93]
Amigos sou iniciante no ADVPL e no momento minhas configurações estão as seguintes:

{
 "advpl.environments":[{
 "smartClientPath": "C:\ \TOTVS 12\ \Microsiga\ \Protheus\ \bin\ \smartclient\ \",
 "environment": "Environment",
 "includeList": "C:\ \TOTVS 12\ \Microsiga\ \Protheus\ \include\ \ \",
 "server": "localhost",
 "port": "1234",
 "user": "Admin"}],
 "files.encoding": "windows1252"
}

Sou obrigado a informar a senha criptografada pelo Cipher? Quando dou o comando e informo a senha utilizada, dou um ENTER e não é me retornado nada na tela.

Desde já agradeço!

**Comment by killerall** [comment]
Você tem que rodar o comando de Cipher, digitar a senha do ambiente, ele ira gerar a senha criptografada na aba Output
![vscode_cip](https://user-images.githubusercontent.com/4764609/27638710-84eb6a0a-5bea-11e7-83f4-f94e6bdbc037.png)
