### ISSUE TITLE
Definir pasta a ser considerada no Debug

### ISSUE THREAD

**Issue by denisonsoares** [killerall/advpl-vscode#97]
Olá, Senhores!

No TDS, caso eu possua fontes iguais em projetos diferentes, por meio da opção Source Lookup Path em Debug Configurations é possível definir qual projeto será considerado no Debug, para que a versão correta do fonte a ser debugado seja aberta.

Como realizo esta configuração no vscode? Pois tenho 2 projetos (Ex.: P11 e P12) no mesmo diretório, com fontes iguais e versões diferentes, e ao debugar determinado fonte existente em ambos os projetos, é aberto o fonte com a versão desatualizada, mesmo que o breakpoint esteja posicionado na versão correta.

Obrigado,
Denison

**Comment by killerall** [comment]
Para fazer isso é necessário atualizar o protocolo de debug.

**Comment by vicenthy** [comment]
você pode trabalhar com workspace diferente pra cada projeto.

**Comment by paulo-afill** [comment]
Eu não posso criar outro workspace pois no meu projeto possuo o conceito de branch, tag e trunk, podendo ter assim N vezes o mesmo fonte dentro do projeto...

**Comment by killerall** [comment]
@paulo-afill 
No futuro será implementado esse recurso, para selecionar a pasta do debug.

Por hora, ao inves de abrir a raiz do seu projeto, que tem as tres pastas, abra a pasta do trunk diretamente por exemplo.

**Comment by killerall** [comment]
@denisonsoares 
O Alencar desenvolveu uma extensão que faz isso.
https://github.com/AlencarGabriel/advpl-switch-project
