### ISSUE TITLE
Apresentar histórico de programas executados

### ISSUE THREAD

**Issue by denisonsoares** [killerall/advpl-vscode#99]
Olá, Senhores!

Gostaria de sugerir a implementação do histórico de programas executados ao iniciar o smartclient por meio das teclas F5 ou CTRL+ F5, desta forma nas próximas execuções não será necessário digitar a função novamente, apenas selecioná-la (seta up/down).

Obrigado,
Denison

**Comment by afucher** [comment]
Hoje ele já traz a última execução, certo?

**Comment by denisonsoares** [comment]
Traz, mas se você limpar o campo não é possível selecionar novamente.

**Comment by afucher** [comment]
@denisonsoares nas últimas versões caso deixe em branco ou saia pelo ESC ele mantém a última função a ser executada. Irei fechar essa issue, caso não seja isso que queria, reabra explicando melhor por favor!
